Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-11, with the labels that each got.

#2140 Fixed issue #17713: broken theme name in Survey general settings
  application/views/admin/survey/subview/surveydashboard/004-generalsettingspanel.twig
Labels: Tested OK

#2139 Fixed issue #17637: wrong question order
  application/controllers/QuestionAdministrationController.php
Labels: Needs review, Needs testing

#2137 Fixed issue #17202 for v3
  application/helpers/export_helper.php
Labels: Feedback, NoMantisReport

#2141 Fixed issue #17717: Saving survey group permissions fails with error 500
  application/core/plugins/AuditLog/AuditLog.php
Labels: Needs testing

#2136 Fixed issue #17674: Impossible to add new Menu or New Menu Entry
  application/extensions/LimeScript/LimeScript.php
Labels: Needs review

#2127 Fixed issue #L41-T1509: Numeric questions prevent statistics from generating and display false data
  application/helpers/admin/statistics_helper.php
  application/helpers/common_helper.php
Labels: Needs review

#2146 Fixed issue #17729: Setting default answers for sibgle choice question type
  application/views/questionAdministration/editdefaultvalues.php
Labels: Needs testing

#2144 Fixed issue #17696: Mass changing expiration date fails (except for superadmin)
  application/controllers/SurveyAdministrationController.php
Labels: Needs review, Tested OK

#2145 Fixed issue T155: Sometimes editing survey participants doesn't show data
  assets/scripts/admin/tokens.js
Labels: Needs review

#2142 Correct bugs in API remote RPC services "set_question_properties" and "import_question"
  application/helpers/admin/import_helper.php
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: NoMantisReport

#2143 Fixed issue #17647: Strange sort order of question groups in statistics
  application/controllers/admin/statistics.php
  application/helpers/common_helper.php
  application/helpers/frontend_helper.php
  application/models/Question.php
Labels: Needs review, Tested OK

#2114 Fixed issue #17525: VVImport: "Exclude record IDs" ignores existing e…
  application/helpers/admin/import_helper.php
Labels: Needs review, Tested OK

#2154 Fixed issue #17755: remotecontrol error status inconsistent
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs testing

#2147 Fixed issue #15992: Using Expression Manager with double quotes fails for end URL field
  application/controllers/admin/database.php
  application/core/LSYii_Validators.php
Labels: Needs review, Needs testing

#2086 Fixed issue #17527: Validate before using updateAll
  application/models/LSActiveRecord.php
  application/models/QuestionAttribute.php
  application/views/survey/questions/answer/5pointchoice/config.xml
  application/views/survey/questions/answer/arrays/10point/config.xml
  application/views/survey/questions/answer/arrays/5point/config.xml
  application/views/survey/questions/answer/arrays/array/config.xml
  application/views/survey/questions/answer/arrays/column/config.xml
  application/views/survey/questions/answer/arrays/increasesamedecrease/config.xml
  application/views/survey/questions/answer/arrays/multiflexi/config.xml
  application/views/survey/questions/answer/arrays/texts/config.xml
  application/views/survey/questions/answer/arrays/yesnouncertain/config.xml
  application/views/survey/questions/answer/date/config.xml
  application/views/survey/questions/answer/hugefreetext/config.xml
  application/views/survey/questions/answer/list_dropdown/config.xml
  application/views/survey/questions/answer/list_with_comment/config.xml
  application/views/survey/questions/answer/listradio/config.xml
  application/views/survey/questions/answer/longfreetext/config.xml
  application/views/survey/questions/answer/multiplechoice/config.xml
  application/views/survey/questions/answer/multiplechoice_with_comments/config.xml
  application/views/survey/questions/answer/multiplenumeric/config.xml
  application/views/survey/questions/answer/multipleshorttext/config.xml
  application/views/survey/questions/answer/numerical/config.xml
  application/views/survey/questions/answer/ranking/config.xml
  application/views/survey/questions/answer/shortfreetext/config.xml
  docs/themes/questiontheme_example/survey/questions/answer/listradio/config.xml
  tests/TestBaseClass.php
  tests/data/file_upload/NewQuestionAttributesPlugin.zip
  tests/data/plugins/NewQuestionAttributesPlugin.php
  tests/data/surveys/limesurvey_survey_141451_testSaveQuestionAttributes.lss
  tests/functional/backend/SaveQuestionAttributesTest.php
Labels: Needs testing

#2152 Fixed issue #17698: Change of email address for survey administrator confusing
  application/controllers/admin/useraction.php
  application/views/admin/user/personalsettings.php
  assets/scripts/admin/personalsettings.js
Labels: Tested OK

#2161 Fixed issue #17762: vulnerable verson of jQuery included in qtip2
  application/config/third_party.php
  application/controllers/admin/translate.php
  third_party/qTip2/.gitignore
  third_party/qTip2/LICENSE-GPL
  third_party/qTip2/LICENSE-MIT
  third_party/qTip2/README.md
  third_party/qTip2/dist/jquery.qtip.css
  third_party/qTip2/dist/jquery.qtip.js
  third_party/qTip2/dist/jquery.qtip.min.css
  third_party/qTip2/dist/jquery.qtip.min.js
  third_party/qTip2/grunt.js
  third_party/qTip2/libs/jquery-loader.js
  third_party/qTip2/libs/jquery/jquery.js
  third_party/qTip2/package.json
  third_party/qTip2/src/ajax/ajax.js
  third_party/qTip2/src/basic.css
  third_party/qTip2/src/core.css
  third_party/qTip2/src/core.js
  third_party/qTip2/src/css3.css
  third_party/qTip2/src/ie6/ie6.css
  third_party/qTip2/src/ie6/ie6.js
  third_party/qTip2/src/imagemap/imagemap.js
  third_party/qTip2/src/intro.js
  third_party/qTip2/src/modal/modal.css
  third_party/qTip2/src/modal/modal.js
  third_party/qTip2/src/outro.js
  third_party/qTip2/src/svg/svg.js
  third_party/qTip2/src/tips/tips.css
  third_party/qTip2/src/tips/tips.js
  third_party/qTip2/src/viewport/viewport.js
Labels: Needs review

#2165 Fixed issue #17765: The order of the answer options not correct when exporting to printable survey or queXML
  application/controllers/admin/printablesurvey.php
  application/helpers/export_helper.php
  application/models/Answer.php
Labels: Needs review, Needs testing
