Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-12, with the labels that each got.

#2123 Fixed issue #T1358: Label Sets: Export multiple label sets - Export Button disabled state
  application/controllers/admin/export.php
  application/controllers/admin/labels.php
  application/views/admin/labels/exportmulti_view.php
  application/views/admin/labels/labelsetsbar_view.php
Labels: Needs review

#2160 Fixed issue #17762: vulnerable verson of jQuery used in devbridge-autocomplete
  third_party/devbridge-autocomplete/.gitignore
  third_party/devbridge-autocomplete/bower.json
  third_party/devbridge-autocomplete/content/styles.css
  third_party/devbridge-autocomplete/devbridge-autocomplete.jquery.json
  third_party/devbridge-autocomplete/dist/jquery.autocomplete.js
  third_party/devbridge-autocomplete/dist/jquery.autocomplete.min.js
  third_party/devbridge-autocomplete/gruntfile.js
  third_party/devbridge-autocomplete/index.htm
  third_party/devbridge-autocomplete/package.json
  third_party/devbridge-autocomplete/readme.md
  third_party/devbridge-autocomplete/scripts/countries.js
  third_party/devbridge-autocomplete/scripts/demo.js
  third_party/devbridge-autocomplete/scripts/jquery-1.8.2.min.js
  third_party/devbridge-autocomplete/scripts/jquery-2.1.1.js
  third_party/devbridge-autocomplete/scripts/jquery.mockjax.js
  third_party/devbridge-autocomplete/spec/autocompleteBehavior.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-1.3.1/MIT.LICENSE
  third_party/devbridge-autocomplete/spec/lib/jasmine-1.3.1/jasmine-html.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-1.3.1/jasmine.css
  third_party/devbridge-autocomplete/spec/lib/jasmine-1.3.1/jasmine.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-2.0.1/boot.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-2.0.1/console.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-2.0.1/jasmine-html.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-2.0.1/jasmine.css
  third_party/devbridge-autocomplete/spec/lib/jasmine-2.0.1/jasmine.js
  third_party/devbridge-autocomplete/spec/lib/jasmine-2.0.1/jasmine_favicon.png
  third_party/devbridge-autocomplete/spec/runner.html
  third_party/devbridge-autocomplete/src/jquery.autocomplete.js
  third_party/devbridge-autocomplete/typings/jquery-autocomplete/jquery.autocomplete-tests.ts
  third_party/devbridge-autocomplete/typings/jquery-autocomplete/jquery.autocomplete.d.ts
  third_party/devbridge-autocomplete/typings/jquery/jquery.d.ts
Labels: Needs review

#2155 New feature #17477: Make it possible to use answer option text in expression script.
  application/core/plugins/ExpressionAnswerOptions/AnswerOptionsFunctions.php
  application/core/plugins/ExpressionAnswerOptions/ExpressionAnswerOptions.php
  application/core/plugins/ExpressionAnswerOptions/LICENSE
  application/core/plugins/ExpressionAnswerOptions/README.md
  application/core/plugins/ExpressionAnswerOptions/config.xml
  application/core/plugins/ExpressionAnswerOptions/views/expressionAnswerOptionsInfo.twig
  application/libraries/PluginManager/PluginBase.php
  composer.json
  psalm.xml
  tests/data/surveys/limesurvey_survey_expressionAnswerOptionsTest.lss
  tests/functional/frontend/AnswerOptionsFunctionsPluginTest.php
Labels: Needs review

#2162 Dev #15750: Send emails only to participants with incomplete responses
  application/controllers/admin/tokens.php
  application/models/TokenDynamic.php
  application/views/admin/token/remind.php
Labels: Needs update by author, Needs review

#2167 Fixed issue #17732: Direct access to response browsing break
  application/controllers/ResponsesController.php
Labels: Needs review

#2169 Dev #T207: Make it possible to change the base language of a survey
  application/controllers/admin/database.php
  application/extensions/admin/survey/LanguagesWidget/LanguagesWidget.php
  application/extensions/admin/survey/LanguagesWidget/assets/css/LanguagesWidget.css
  application/extensions/admin/survey/LanguagesWidget/assets/js/LanguagesWidget.js
  application/helpers/common_helper.php
  application/views/admin/survey/subview/accordion/_generaloptions_panel.php
  application/views/surveyAdministration/editLocalSettings_main_view.php
Labels: Needs testing

#2125 Dev #9629: Global opt out link for CPDB missing
  application/controllers/LimereplacementfieldsController.php
  application/controllers/admin/ExpressionValidate.php
  application/core/LimeMailer.php
  application/models/Participant.php
  application/models/TokenDynamic.php
Labels: Tested OK, Code checked

#2159 Fixed issue #17527: Validate before using updateAll
  application/controllers/admin/database.php
  application/helpers/questionHelper.php
  application/models/LSActiveRecord.php
  application/models/QuestionAttribute.php
  tests/LimeSurveyWebDriver.php
  tests/TestBaseClass.php
  tests/TestBaseClassWeb.php
  tests/data/file_upload/NewQuestionAttributesPlugin.zip
  tests/data/surveys/limesurvey_survey_458461_testSaveQuestionAttributes.lss
  tests/functional/backend/SaveQuestionAttributesTest.php
Labels: Tested OK

#2171 Fixed issue #17725: Unclear error message
  application/core/LSYii_ImageValidator.php
  application/models/InstallerConfigForm.php
  application/views/installer/precheck_view.php
Labels: Tested OK

#2179 Fixed issue #17711: Cannot export selected responses (only range)
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
Labels: Needs testing

#2183 Dev #14878: Fixed order for 'Question attribute Category'
  application/helpers/common_helper.php
  application/models/services/QuestionAttributeFetcher.php
  application/models/services/QuestionAttributeHelper.php
Labels: Needs testing

#2176 Fixed issue #17790: KCFinder Image Browse Server not working due to i…
  application/helpers/admin/htmleditor_helper.php
Labels: Bugfix
