Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-06, with the labels that each got.

#1896 Fixed issue #14039: Captcha prevent panel integration. GET URL parameter not captured
  application/core/LSHttpRequest.php
  application/helpers/frontend_helper.php
Labels: Needs testing, Needs update by author

#1893 Dev #17261: Create new code artifacts to handle QuestionAttributes fetching (& saving)
  application/models/ExtensionConfig.php
  application/models/Question.php
  application/models/services/CoreQuestionAttributeProvider.php
  application/models/services/PluginQuestionAttributeProvider.php
  application/models/services/QuestionAttributeFetcher.php
  application/models/services/QuestionAttributeHelper.php
  application/models/services/QuestionAttributeProvider.php
  application/models/services/ThemeQuestionAttributeProvider.php
  tests/data/plugins/NewQuestionAttributesPlugin.php
  tests/functional/backend/QuestionAttributeTest.php
Labels: Needs update by author

#1916 Fixed issue #17276: 500: Internal Server Error - Call to a member function format() on bool
  application/controllers/RegisterController.php
  application/controllers/SurveyAdministrationController.php
  application/controllers/admin/checkintegrity.php
  application/controllers/admin/database.php
  application/controllers/admin/globalsettings.php
  application/controllers/admin/tokens.php
  application/core/QuestionTypes/Date/RenderDate.php
  application/core/Survey_Common_Action.php
  application/helpers/admin/statistics_helper.php
  application/helpers/export_helper.php
  application/helpers/expressions/em_manager_helper.php
  application/helpers/replacements_helper.php
  application/helpers/userstatistics_helper.php
  application/libraries/Date_Time_Converter.php
Labels: Needs testing

#1878 Dev #T635: Land in the Suvey Builder (Structure) when creating a survey
  application/config/config-defaults.php
  application/controllers/SurveyAdministrationController.php
  application/controllers/admin/globalsettings.php
  application/controllers/admin/useraction.php
  application/views/admin/globalsettings/_general.php
  application/views/admin/user/personalsettings.php
  application/views/surveyAdministration/tabCreate_view.php
Labels: Needs testing

#1910 Dev #T773: Question Editor: WISIWYG Editor
  application/helpers/admin/htmleditor_helper.php
  application/views/admin/survey/prepareEditorScript_view.php
  application/views/questionAdministration/textElements.php
  assets/packages/ckeditor/config.js
  assets/packages/ckeditor/plugins/editorplaceholder/plugin.js
  assets/packages/ckeditor/plugins/lsswitchtoolbars/basic.gif
  assets/packages/ckeditor/plugins/lsswitchtoolbars/full.gif
  assets/packages/ckeditor/plugins/lsswitchtoolbars/plugin.js
Labels: Tested failed

#1932 [ENH] transfer delete response to 3.x-LTS
  application/helpers/remotecontrol/remotecontrol_handle.php
  application/models/Response.php
  tests/data/surveys/survey_archive_deleteResponseTest.lsa
  tests/helpers/RemoteControlTest.php
Labels: Needs update by author
