Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-08, with the labels that each got.

#1933 Dev #17350: Question theme should be a separate database column, not an attribute
  application/config/config-defaults.php
  application/config/version.php
  application/controllers/QuestionAdministrationController.php
  application/extensions/GeneralOptionWidget/settings/QuestionThemeGeneralOption.php
  application/helpers/admin/import_helper.php
  application/helpers/common_helper.php
  application/helpers/update/updatedb_helper.php
  application/models/Question.php
  application/models/QuestionAttribute.php
  application/models/QuestionBaseDataSet.php
  application/models/QuestionCreate.php
  application/models/QuestionTemplate.php
  application/models/QuestionTheme.php
  application/models/services/ThemeQuestionAttributeProvider.php
  application/views/questionAdministration/create.php
  application/views/questionAdministration/summary.php
  application/views/questionAdministration/typeSelector.php
  assets/scripts/admin/questionEditor.js
  installer/create-database.php
  tests/functional/backend/QuestionAttributeTest.php
  tests/functional/backend/QuestionGroupEditorTest.php
  tests/unit/models/QuestionTest.php
Labels: Needs update by author, Needs review

#1979 Fixed issue #17457: Close button on the survey groups creation screen takes you to the wrong screen
  application/controllers/admin/SurveysGroupsController.php
Labels: Needs testing

#1959 Fixed issue #17422: Survey Deletion view/read permission seems to be granted
  application/controllers/admin/surveypermission.php
  application/extensions/UserPermissionsWidget/views/table.php
  application/models/Survey.php
  application/models/SurveysGroups.php
  application/models/services/PermissionManager.php
Labels: Tested failed

#1942 Fixed issue #17223: With mandatory attribute : lost all current value when create a token
  application/controllers/admin/tokens.php
  application/views/admin/token/tokenform.php
  assets/scripts/admin/tokens.js
Labels: Needs testing

#1982 Dev #17375: Unify upper/lower case in question type
  application/config/version.php
  application/helpers/update/updatedb_helper.php
  application/views/survey/questions/answer/5pointchoice/config.xml
  application/views/survey/questions/answer/arrays/10point/config.xml
  application/views/survey/questions/answer/arrays/5point/config.xml
  application/views/survey/questions/answer/hugefreetext/config.xml
  application/views/survey/questions/answer/multiplenumeric/config.xml
  application/views/survey/questions/answer/multipleshorttext/config.xml
  application/views/survey/questions/answer/numerical/config.xml
  themes/question/image_select/survey/questions/answer/listradio/config.xml
  themes/question/image_select/survey/questions/answer/multiplechoice/config.xml
  themes/question/ranking_advanced/survey/questions/answer/ranking/config.xml
Labels: Needs update by author

#1939 Fixed issue #17379: Question types can be uninstalled
  application/models/QuestionTheme.php
Labels: Discussion ongoing
