Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-02, with the labels that each got.

#1745 Update SurveyAdministrationController.php
  application/controllers/SurveyAdministrationController.php
Labels: tested OK

#1736 Fixed issue #17041: Error with SUM on array text
  assets/packages/questions/arraynumeric/scripts/array-totalsum.js
  assets/packages/questions/arraynumeric/scripts/array-totalsum.min.js
Labels: tested OK

#1729 Fixed issue #17008: Bad label and id in Question editor
  application/views/questionAdministration/textElements.php
Labels: tested OK

#1714 Fixed issue #16949: Uploading an image through the theme options fails
  application/controllers/admin/themes.php
Labels: tested OK

#1738 Fixed issue #16416: image_select question theme : set width mlake invalid HTML
  themes/question/image_select/survey/questions/answer/listradio/rows/answer_row.twig
  themes/question/image_select/survey/questions/answer/multiplechoice/rows/answer_row.twig
Labels: tested OK

#1737 Fixed issue #16756: Error with SUM on array text
  assets/packages/questions/arraynumeric/scripts/array-totalsum.js
  assets/packages/questions/arraynumeric/scripts/array-totalsum.min.js
Labels: tested OK

#1733 Fixed Issue #17026: Custom themes not uploading files
  application/controllers/admin/themes.php
Labels: tested OK

#1750 fix composer.json license format to match composer standard-V3
  composer.json
Labels: tested OK

#1731 Fixed issue #16882: Unable to set Html editor in Personnal settings
  application/models/User.php
  application/views/admin/user/personalsettings.php
Labels: tested OK

#1749 Display actual model errors when survey import fails V3
  application/helpers/admin/import_helper.php
Labels: tested OK

#1748 Display actual model errors if survey import fails
  application/helpers/admin/import_helper.php
Labels: tested OK

#1739 Fixed issue #16920: LimeReplacement Fields not working
  application/controllers/LimereplacementfieldsController.php
Labels: tested OK

#1753 Fixed issue #17030: Can't add a question to a group
  application/controllers/QuestionAdministrationController.php
Labels: tested OK

#1740 Fixed issue #17010: Admin personal setting not implemented
  application/controllers/QuestionAdministrationController.php
  application/models/QuestionCreate.php
  application/views/layouts/sidemenu.php
Labels: tested OK

#1752 Fixed issue #17055: Public stats don't use the theme set at survey, but at global settings
  application/controllers/Statistics_userController.php
Labels: tested OK

#1741 16953: HTML Editor missing in Assessment mode
  application/controllers/AssessmentController.php
  application/views/assessment/assessments_edit.php
  application/views/assessment/assessments_view.php
Labels: tested OK

#1747 Fixed issue #17054: Public stats don't use the theme set at survey, but at global settings
  application/controllers/Statistics_userController.php
Labels: tested OK

#1768 Fixed issue #15539: queXML PDF shows JS script
  application/helpers/export_helper.php
Labels: tested OK

#1660 Fixed issue #16777: Add list_survey_groups to RemoteControl API
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/unit/helpers/RemoteControlListSurveyGroupsTest.php
Labels: feedback

#1767 Fixed issue #16455: Public statistics for Ranking question not shown
  application/controllers/Statistics_userController.php
  application/helpers/userstatistics_helper.php
Labels: tested OK

#1777 Fixed issue #15514: Image "save" button no response action after click
  application/controllers/admin/surveyadmin.php
Labels: tested OK

#1781 Fixed issue #16449: Error with CLI password reset
  application/commands/ResetPasswordCommand.php
Labels: Needs update by author

#1773 Fixed issue #17018: No simple selector for Question type
  application/controllers/QuestionAdministrationController.php
  application/extensions/admin/PreviewModalWidget/assets/previewModalWidget.js
  application/extensions/admin/PreviewModalWidget/views/simple_grouped_select.php
  application/views/questionAdministration/create.php
Labels: tested OK

#1761 Fixed issue #16976: Date format problem
  application/views/admin/token/tokenform.php
Labels: Needs testing
