Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-07, with the labels that each got.

#1940 Fixed issue #17062: Restore-button, no error message if no old token table selected
  application/views/admin/token/tokenwarning.php
Labels: Needs testing

#1923 Fixed issue #17046: When copy question : can not update text and help
  application/controllers/QuestionAdministrationController.php
  application/datavalueobjects/CopyQuestionTextValues.php
  application/datavalueobjects/CopyQuestionValues.php
  application/extensions/TopbarWidget/views/includes/copyQuestionTopbarRight_view.php
  application/models/services/CopyQuestion.php
  application/views/questionAdministration/_copyQuestionTabsLanguages.php
  application/views/questionAdministration/copyQuestionForm.php
  application/views/questionAdministration/create.php
  application/views/questionAdministration/questionCode.php
  assets/scripts/admin/questionEditor.js
Labels: Tested failed

#1958 Fixed issue #17425: Missusage of progressbar
  application/helpers/SurveyRuntimeHelper.php
  assets/styles-public/lime-progress.css
  themes/survey/vanilla/views/subviews/header/progress_bar.twig
Labels: Needs testing

#1953 Fixed issue #17373: Missusage of progressbar
  application/helpers/SurveyRuntimeHelper.php
  assets/styles-public/lime-progress.css
  themes/survey/vanilla/views/subviews/header/progress_bar.twig
Labels: Needs update by author

#1938 Fixed issue #17363: Survey data policy error message not displayed
  themes/survey/vanilla/config.xml
  themes/survey/vanilla/scripts/theme.js
  themes/survey/vanilla/views/subviews/content/firstpage.twig
  themes/survey/vanilla/views/subviews/messages/warnings.twig
  themes/survey/vanilla/views/subviews/privacy/allinone_mode_welcome_privacy.twig
  themes/survey/vanilla/views/subviews/privacy/privacy.twig
  themes/survey/vanilla/views/subviews/privacy/privacy_modal.twig
  themes/survey/vanilla/views/subviews/privacy/privacy_text.twig
Labels: Needs testing

#1951 Dev #T864: Sticky Bar
  application/core/Survey_Common_Action.php
  application/helpers/LayoutHelper.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
  assets/scripts/admin/questionEditor.js
  assets/scripts/admin/topbar.js
  tests/functional/backend/QuestionGroupEditorTest.php
  themes/admin/Apple_Blossom/css/lime-admin-colors.css
  themes/admin/Bay_of_Many/css/lime-admin-colors.css
  themes/admin/Black_Pearl/css/lime-admin-colors.css
  themes/admin/Dark_Sky/css/lime-admin-colors.css
  themes/admin/Free_Magenta/css/lime-admin-colors.css
  themes/admin/Noto_All_Languages/css/lime-admin-colors.css
  themes/admin/Purple_Tentacle/css/lime-admin-colors.css
  themes/admin/Sea_Green/css/lime-admin-colors.css
  themes/admin/Sunset_Orange/css/lime-admin-colors.css
Labels: Needs testing

#1937 Fixed issue #17367: Survey policy error not show in vanilla
  themes/survey/vanilla/config.xml
  themes/survey/vanilla/scripts/theme.js
  themes/survey/vanilla/views/subviews/content/firstpage.twig
  themes/survey/vanilla/views/subviews/messages/warnings.twig
  themes/survey/vanilla/views/subviews/privacy/allinone_mode_welcome_privacy.twig
  themes/survey/vanilla/views/subviews/privacy/privacy_modal.twig
  themes/survey/vanilla/views/subviews/privacy/privacy_text.twig
Labels: Needs testing

#1986 Fixed issue #17480: Unable to reload with token + persistence + allow edit
  application/helpers/frontend_helper.php
  application/models/Response.php
Labels: Needs testing
