Repository LimeSurvey/LimeSurvey, pull requests merged in 2021-03, with the labels that each got.

#1770 Fixed issue #16867: Randomization happen in survey logic file and in export
  application/controllers/admin/export.php
  application/controllers/admin/expressions.php
Labels: Needs testing

#1780 Fixed issue #17113: Randomization happen in survey logic file and in export
  application/controllers/admin/export.php
  application/controllers/admin/expressions.php
Labels: Needs testing

#1784 Fixed issue #15854: Cannot open pop up editor - subquestions (an extra page refresh needed)
  application/views/admin/survey/Question/subquestionsAndAnswers/_subquestion.twig
Labels: Needs testing, Tested OK

#1792 Fixed issue #15239: Brute-force attack with tokens to enter survey is possible
  application/helpers/frontend_helper.php
Labels: Needs review

#1795 New PHPMailer factory
  application/controllers/admin/tokens.php
  application/helpers/admin/token_helper.php
  application/helpers/common_helper.php
  application/helpers/mailHelper.php
Labels: Needs testing

#1763 Fixed issue #17090: Email continue not shown clearly after activation
  application/views/admin/token/emailwarning.php
Labels: Needs testing

#1769 New Feature #13853: Allow test & basic feedback of the email functionality.
  application/controllers/admin/globalsettings.php
  application/views/admin/globalsettings/_email.php
  application/views/admin/globalsettings/_emailTestConfirmation.php
  application/views/admin/globalsettings/_emailTestResults.php
  assets/scripts/admin/globalsettings.js
Labels: Needs testing

#1774 Fixed issue #17093: Unable to fix invalid survey after import bad TSV
  application/helpers/admin/import_helper.php
  application/models/Survey.php
  application/models/services/SurveyIntegrity.php
Labels: Needs testing

#1786 Fixed issue #15904: Default survey admin & admin email not copied from user profile
  application/controllers/SurveyAdministrationController.php
  application/datavalueobjects/SimpleSurveyValues.php
  application/models/services/CreateSurvey.php
  application/views/surveyAdministration/tabCreate_view.php
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.css
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js.map
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/lib/surveysettings.js
  tests/unit/models/CreateSurveyServiceTest.php
Labels: Needs testing

#1791 Fixed issue #16939: exporting list question with 'other' to SPSS does not read all data
  application/controllers/admin/export.php
  application/helpers/export_helper.php
Labels: Needs testing

#1782 Fixed issue #16288: Bad character encoding when export file as zip
  application/controllers/admin/responses.php
Labels: Needs testing

#1799 Fixed bug #15919: Cannot import custom question theme based on an array question
  application/controllers/admin/themes.php
  application/models/QuestionTheme.php
  application/views/admin/themes/importuploaded_view.php
Labels: Needs testing

#1787 Fixed issue #17082: text display in plain italics not possible
  assets/fonts/noto.css
Labels: Needs review, Needs update by author, Tested failed

#1297 New feature #16781: autodetection of path in spss syntax
  application/controllers/admin/export.php
  application/views/admin/export/spss_view.php
Labels: Needs update by author

#1804 Remove sourceMappingURL from assets
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/build/adminbasics.min.js.map
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/rollup.config.js
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.css
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js.map
  assets/packages/adminsidepanel/build/css/adminsidepanel.css
  assets/packages/adminsidepanel/build/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/vue.config.js
  assets/packages/bootstrap/bootstrap.min.css
  assets/packages/lstutorial/build/lstutorial.js
  assets/packages/lstutorial/build/lstutorial.min.js
  assets/packages/lstutorial/build/lstutorial.min.js.map
  assets/packages/lstutorial/rollup.config.js
  assets/packages/pjax/pjax.js
  themes/survey/bootswatch/css/variations/basic.min.css
  third_party/moment/moment-with-locales.min.js
Labels: Needs review

#1421 Fixed issue : Unable to upload heic or heiv files (and other)
  application/core/LSFileHelper.php
  application/core/utils/fileExtensions.php
Labels: Bugfix

#1316 fix: Modify the exported stata file encoding to utf-8
  application/core/plugins/ExportSTATAxml/STATAxmlWriter.php
Labels: feedback
