Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-06, with the labels that each got.

#2444 Fixed issue #18158: `Property "CDbCriteria.qid" is not defined` status returned by delete_question
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs testing, Code checked

#2423 Fixed issue #18114: permission will now be checked for user when open…
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK, Code checked

#2455 Fixed issue #17976: Bad place for pencil in edit question
  application/views/questionAdministration/textElements.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
Labels: Tested OK, Code checked

#2228 Fixed issue #17740: Script : Set for all languages didn't work
  application/config/version.php
  application/controllers/QuestionAdministrationController.php
  application/helpers/admin/import_helper.php
  application/helpers/export_helper.php
  application/helpers/update/updates/Update_488.php
  application/models/Question.php
  application/models/QuestionBaseRenderer.php
  application/views/questionAdministration/textElements.php
  assets/scripts/admin/questionEditor.js
  installer/create-database.php
Labels: Needs testing, Code checked

#2467 Fixed issue #18189: Fonts showing differently on mobile Vs desktop
  themes/survey/bootswatch/css/theme.css
Labels: Needs review, Needs testing

#2440 Fixed issue #18108: Unable to save existing question with button
  application/controllers/QuestionAdministrationController.php
  application/extensions/TopbarWidget/views/includes/copyQuestionTopbarRight_view.php
  application/views/admin/survey/Question/_subQuestionsAndAnwsersJsVariables.php
  application/views/questionAdministration/_copyQuestionTabsLanguages.php
  application/views/questionAdministration/questionCode.php
  application/views/questionAdministration/topbars/copyQuestiontopbar_view.php
  assets/scripts/admin/questionEditor.js
  tests/functional/backend/CreateQuestionTest.php
Labels: Tested OK

#2457 Fixed issue #18153: 'Export this question to PDF' button in View Statistics - HTML does nothing
  application/views/admin/export/generatestats/_statisticsoutput_graphs.php
  application/views/admin/export/generatestats/_statisticsoutput_header.php
Labels: Tested OK, Discussion ongoing, Code checked

#2439 Dev #18033: Model errors need friendlier messages
  application/controllers/QuestionAdministrationController.php
  application/controllers/SurveysController.php
  application/core/LSJsonException.php
  application/core/LSUserException.php
  application/core/LSYii_Application.php
Labels: Tested OK, Code checked

#2474 Fixed issue #18186: Language changer does not work in registration page
  assets/packages/limesurvey/survey.js
Labels: Tested OK, Code checked

#2459 Fixed issue #17700: Custom logo disappears in extended themes
  application/models/TemplateConfiguration.php
  assets/packages/themeoptions-core/themeoptions-core.js
Labels: Needs testing, Code checked

#2475 Fixed issue #17804: InputOnDemand is not loading all prior rows when navigating back
  themes/question/inputondemand/survey/questions/answer/multipleshorttext/assets/scripts/inputondemand.js
Labels: Tested OK, Code checked

#2477 Fixed issue #18171: Timings are not saved on MSSQL DB
  application/models/SurveyTimingDynamic.php
Labels: Tested OK, Code checked

#2479 Fixed issue #18209: Missing RemoteControl function to get the field mapping
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/limesurvey_survey_remote_api_get_fieldmap.lss
  tests/unit/helpers/RemoteControlTest.php
Labels: Needs review, Needs testing

#2374 Fixed issue #18042: Path-relative stylesheet import (PRSSI) vulnerability
  third_party/kcfinder/tpl/tpl_browser.php
Labels: Tested OK, Code checked
