Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-12, with the labels that each got.

#2657 Fixed issue #18250: admin css hide logic file part
  application/views/admin/expressions/test/survey_logic_file.php
Labels: Tested OK, Code review done

#2591 Fixed issue #18337: Placeholders VALIDFROM and VALIDUNTIL at email templates do not use localized dates
  application/core/plugins/dateFunctions/EMFunctions.php
  application/core/plugins/dateFunctions/config.xml
  application/core/plugins/dateFunctions/dateFunctions.php
Labels: Tested OK, Code review done

#2593 Fixed issue #17818: Copy a multiple choice question send a DB error (MSSQL)
  application/controllers/admin/database.php
Labels: Needs testing, Code review done, minor impact

#2768 fixed issue: Add attribute modal in CPDB - inline form fix
  application/views/admin/participants/modal_subviews/_editAttribute.php
Labels: Needs testing

#2770 fixed issue: multi numerical input slider labels out of place
  application/views/survey/questions/answer/multiplenumeric/rows/sliders/answer_row.twig
  assets/packages/questions/numeric-slider/css/numeric-slider.css
  themes/survey/vanilla/css/noTablesOnMobile.css
  themes/survey/vanilla/scripts/theme.js
Labels: Needs code review, Needs testing

#2769 fixed issue: question editor notifier now auto hides again
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/src/parts/ajaxAlerts.js
Labels: Tested OK

#2760 Fixed issue [security] #18514 : no CSRF control when delete token table
  application/controllers/admin/tokens.php
Labels: Tested OK, Code review done

#2773 fix mobile issue in the survey taking part
  themes/survey/vanilla/views/subviews/header/nav_bar.twig
Labels: Tested OK, Code review done

#2776 Fix welcome page scroll issue after export survey
  application/views/admin/super/welcome.php
Labels: Tested OK, Code review done

#2761 Fixed issue #18250: admin css hide logic file part
  application/views/admin/expressions/test/survey_logic_file.php
  assets/styles-public/expressionlogicfile.css
Labels: Tested OK, Code review done

#2749 Fixed issue 18086: Custom "other" label text not applied to Bootstrap button layout
  application/helpers/qanda_helper.php
  application/views/survey/questions/answer/multiplechoice/answer.twig
  themes/question/bootstrap_buttons/survey/questions/answer/multiplechoice/answer.twig
Labels: Tested OK, Code review done

#2748 Fixed issue #18449: Impossible to add participant after correcting an e-mail address error
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code review done

#2726 Fixed issue #18338: For participants, expiration date can be set before start date
  application/views/admin/token/tokenform.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/src/parts/globalMethods.js
  assets/scripts/admin/surveysettings.js
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code review done

#2709 Fixed issue #18415: Copy Survey: New Title shouldn't be mandatory
  application/controllers/SurveyAdministrationController.php
  application/views/surveyAdministration/tabCopy_view.php
Labels: Tested OK, Code review done

#2790 Fixed issue [security] #18553: SQL injection on surveygroup update
  application/extensions/admin/survey/ListSurveysWidget/ListSurveysWidget.php
  application/models/Survey.php
  application/models/TemplateConfiguration.php
  application/views/admin/surveysgroups/update.php
  application/views/themeOptions/surveythemelist.php
Labels: Needs testing, Code review done

#2784 Cr 570 gc14 datetimepicker
  assets/admin_themes/Sea_Green/datetimepicker/datetimepicker.scss
  assets/admin_themes/Sea_Green/sea_green.scss
  assets/admin_themes/Sea_Green/sea_green_variables.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#2796 Fixed issue #18503: Label sets: When adding a label set e.g. at the edit responses screen, the loaded label sets can not be searched
  assets/scripts/admin/questionEditor.js
Labels: Tested OK, Code review done

#2797 Fixed issue #18471: Data Entry: Data entry with multiple languages does not work
  application/helpers/common_helper.php
Labels: Tested OK, Code review done
