Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-04, with the labels that each got.

#2332 Fixed issue #17968: conditions designer does not show the right questions to select
  application/controllers/admin/ConditionsAction.php
  application/helpers/common_helper.php
Labels: Tested OK, Code checked

#2271 DEV: Fix config.xml
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/config.xml
Labels: Tested failed

#2331 Fixed issue #17929: Bad code can be entered and saved in answer code
  application/models/Answer.php
Labels: Needs review, Tested OK

#2325 Fixed issue #17989: Check integrity delete all existing condition
  application/controllers/admin/CheckIntegrity.php
Labels: Needs review, Tested OK

#2326 Fixed issue #18008: Broken condition using self.sgqa (static)
  application/helpers/expressions/em_core_helper.php
Labels: Needs review, Tested OK

#2330 Fixed issue #17895: Error in multiple-numeric "Equals sum value" setting
  application/helpers/expressions/em_manager_helper.php
Labels: Needs review, Tested OK

#2329 Fixed issue #17895: Error in multiple-numeric "Equals sum value" setting
  application/helpers/expressions/em_manager_helper.php
Labels: Needs review, Tested OK

#2328 Fixed issue #18018: Static string variable can broke expression
  application/helpers/expressions/em_core_helper.php
Labels: Needs review, Tested OK

#2333 Fixed issue #17882: Base language for new surveys is English instead of default language
  application/controllers/SurveyAdministrationController.php
  application/helpers/surveytranslator_helper.php
  application/views/surveyAdministration/tabCreate_view.php
Labels: Needs review, Tested OK

#2317 Fixed issue #17902: Question theme error: Missing metadata (Type: M)
  application/config/version.php
  application/core/LsDefaultDataSets.php
  application/helpers/update/updates/Update_486.php
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/answer.twig
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/assets/bootstrap_buttons_multiplechoice.png
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/assets/scripts/bootstrapbuttons.css
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/assets/scripts/bootstrapbuttons.js
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/config.xml
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/rows/answer_row.twig
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/rows/answer_row_other.twig
Labels: Tested OK, Code checked

#2366 Fixed issue #18046: Conditions not working as expected in All in One
  application/helpers/expressions/em_manager_helper.php
Labels: Bugfix, Needs review, Needs testing

#2334 Fixed issue #17972: events are dispatched if the plugin is deactivated
  application/controllers/admin/PluginManagerController.php
  application/libraries/PluginManager/PluginManager.php
Labels: Bugfix, Needs review

#2327 New feature #18017: Have a solution to force expression as static
  application/core/plugins/FunctionStatic/FunctionStatic.php
  application/core/plugins/FunctionStatic/README.md
  application/core/plugins/FunctionStatic/StaticFunctions.php
  application/core/plugins/FunctionStatic/config.xml
  application/core/plugins/FunctionStatic/views/StaticFunctionsInfo.twig
Labels: Needs review, Plugin

#2295 Fixed issue #17955: newtest/Y in URL is not clearing session
  application/controllers/survey/index.php
Labels: Tested OK

#2294 Fixed issue #17955: newtest/Y in URL is not clearing session
  application/controllers/survey/index.php
Labels: Tested OK

#2268 Dev #17859: Disable core plugins from config file
  application/config/config-defaults.php
  application/libraries/PluginManager/PluginManager.php
Labels: Tested OK, Code checked

#2371 Fixed issue #17174: Array dual scale doesn't show previously selected…
  application/core/QuestionTypes/ArrayMultiscale/RenderArrayMultiscale.php
  application/views/survey/questions/answer/arrays/dualscale/answer.twig
Labels: Needs review, Needs testing

#2372 Fixed issue #17174: Array dual scale doesn't show previously selected…
  application/helpers/qanda_helper.php
  application/views/survey/questions/answer/arrays/dualscale/answer.twig
Labels: Needs review, Needs testing

#2336 Fixed issue #17811: Theme options for logo and background images are not saved
  application/helpers/SurveyThemeHelper.php
  themes/survey/bootswatch/config.xml
  themes/survey/fruity/config.xml
  themes/survey/vanilla/config.xml
Labels: Code checked

#2342 17804: InputOnDemand is not loading all prior rows when navigating back
  themes/question/inputondemand/survey/questions/answer/multipleshorttext/assets/scripts/inputondemand.js
Labels: Tested OK, Code checked

#2345 Fixed issue #17984: Using method="list_questions" does not give the subquestions
  application/helpers/remotecontrol/remotecontrol_handle.php
  application/models/QuestionGroup.php
Labels: Needs review, Tested OK

#2344 Fixed issue #17864: Regenerate questions codes returns CDbCommand failed to execute the SQL statement: Incorrect syntax near the keyword 'group'
  application/controllers/SurveyAdministrationController.php
Labels: Tested OK, Code checked

#2282 Fixed issue #17862: Invalid url in admin (usage of HTTP_HOST)
  application/views/layouts/sidemenu.php
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
Labels: Needs review, Code checked

#2343 Fixed issue #18019: 500 error in question edition (bad code on question)
  application/controllers/QuestionAdministrationController.php
Labels: Needs review, Tested OK
