Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-07, with the labels that each got.

#2488 Fixed issue #18189: Fonts showing differently on mobile Vs desktop
  themes/survey/bootswatch/css/theme.css
Labels: Code checked, minor impact

#2473 Fixed issue #18201: Unable to import LSA file with MSSQL and debug set
  application/helpers/admin/activate_helper.php
Labels: Tested OK, Code checked

#2452 Fixed issue #18136: Core plugin PasswordRequirement shows duplicate setting fields
  application/core/plugins/PasswordRequirement/PasswordRequirement.php
Labels: Tested OK, Code checked

#2427 Fixed issue #18092: File upload show title/comment=off not yet fully respected
  application/views/survey/questions/answer/file_upload/answer.twig
Labels: Tested OK, Code checked

#2443 Fixed issue #18146: Unable to use "other" as subquestion code
  application/controllers/QuestionAdministrationController.php
  application/models/Question.php
  application/models/QuestionTheme.php
  application/models/QuestionType.php
  application/views/survey/questions/answer/list_dropdown/config.xml
  application/views/survey/questions/answer/listradio/config.xml
  application/views/survey/questions/answer/multiplechoice/config.xml
  application/views/survey/questions/answer/multiplechoice_with_comments/config.xml
Labels: Needs review, Tested OK, Code checked

#2413 Fixed issue #17938: Deleting first question group jumps to system frontpage
  application/controllers/QuestionGroupsAdministrationController.php
Labels: Tested OK, Code checked

#2420 Fixed issue #18073: Can't change reminder / invitation date
  application/controllers/admin/Tokens.php
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code checked

#2293 Fixed issue #17952: Command action potentially try to open uneeded session
  application/core/ConsoleHttpSession.php
  application/helpers/expressions/em_core_helper.php
Labels: Tested OK, Code checked

#2495 Fixed issue [security] #18042: Path-relative stylesheet import (PRSSI) vulnerability (#2374)
  third_party/kcfinder/tpl/tpl_browser.php
Labels: Tested OK, minor impact

#2491 Fixed issue #18200: User with only reponse export can export Survey + token (survey archive)
  application/controllers/admin/export.php
  application/views/admin/survey/surveybar_displayexport.php
Labels: Tested OK, Code checked

#2436 Fixed issue #18085: Renamed custom theme not updated in global survey settings
  application/models/Template.php
Labels: Needs testing, Code checked, minor impact

#2360 Fixed issue #17488: Cannot view survey after updating to version 3.27.9 with custom twig extension (breaks survey)
  application/core/LSETwigViewRenderer.php
Labels: Tested OK, Code checked

#2501 Fixed issue #18235: No control on response and token export on survey archive export
  application/controllers/admin/Export.php
  application/core/TopbarConfiguration.php
  application/extensions/TopbarWidget/views/includes/surveyTopbarLeft_view.php
  application/views/admin/survey/surveybar_displayexport.php
Labels: Tested OK, Code checked, minor impact

#2483 Fixed issue #18203: Return arrays instead of strings from `update_response`
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs testing, Code checked

#2493 Fixed issue #18183: Date filter at statistics is not applied correctly
  application/helpers/admin/statistics_helper.php
  application/views/admin/export/statistics_subviews/_question.php
Labels: Tested OK, Code checked, minor impact

#2508 Fixed issue #16328: invite_participants exits on first error
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: No impact

#2509 Fixed issue #18106: Missing survey ID replacements at registration sc…
  application/controllers/RegisterController.php
Labels: Needs testing, minor impact

#2500 Fixed issue #18141: changing display mode from extended to compact in survey responses windows causes freeze
  assets/scripts/admin/listresponse.js
Labels: Tested OK, Code checked, minor impact

#2489 Dev #18099: Automatic testing for navigation buttons
  tests/data/surveys/limesurvey_survey_navigation.lss
  tests/functional/frontend/SurveyNavigationTest.php
Labels: minor impact, technical

#2426 Fixed issue #17671: Grammar Correct: User management -> Selected user(s)
  application/views/userManagement/massiveAction/_selector.php
Labels: Needs review, Tested OK

#2511 Fixed issue #18239: "Theme options for this survey group" gridview filter not working
  application/controllers/admin/SurveysGroupsController.php
Labels: Tested OK, Code checked, minor impact

#2313 Fixed issue #17458: Check integrty broke for subquestion with only number
  application/controllers/admin/CheckIntegrity.php
Labels: Tested OK

#2456 Fixed issue #18155: Translation missing in question editor
  application/extensions/AdvancedSettingWidget/AdvancedSettingWidget.php
  application/helpers/twig_translation_helper.php
Labels: Needs testing, Code checked

#2312 Fixed issue #17458: Check integrity broke with SQL error
  application/controllers/admin/checkintegrity.php
Labels: Needs testing

#2492 Fixed issue #18119: Batch Edit: Dates are saved as Y/N
  application/views/admin/token/massive_actions/_update.php
  application/views/admin/token/tokenform.php
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code checked

#2514 Fixed issue #18212: Edit label sets - cannot drag&drop
  assets/scripts/admin/labels.js
Labels: Tested OK, Code checked, minor impact

#2381 Fixed issue #18128 : Broken javascript on welcome page
  application/helpers/expressions/em_manager_helper.php
Labels: Needs testing, Code checked, technical

#2498 Fixed issue #18224: Can't set Survey Permissions for User Group when …
  application/controllers/SurveysGroupsPermissionController.php
  application/controllers/admin/SurveyPermission.php
  application/helpers/common_helper.php
Labels: Needs testing, Code checked, technical

#2335 Fixed issue #17972: events are dispatched if the plugin is deactivated
  application/controllers/admin/PluginManagerController.php
  application/libraries/PluginManager/PluginManager.php
Labels: Needs testing, Code checked, technical

#2550 Fixed issue #18284: Function editlocalsettings seems gone in master branch
  application/controllers/SurveyAdministrationController.php
Labels: Needs testing, Code checked, minor impact

#2319 Fixed issue #18006: Unable to use statCountIf to have a "unicity" control
  application/core/plugins/statFunctions/config.xml
  application/core/plugins/statFunctions/countFunctions.php
  application/core/plugins/statFunctions/statFunctions.php
Labels: Feature, Needs review

#2469 Fixed issue #18196: Property "Question.same_script" is not defined.
  application/models/Question.php
Labels: Code checked, minor impact, technical
