Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-03, with the labels that each got.

#2217 Fixed issue #17773: Code name change while we updated from Edit Question screen
  application/config/version.php
  application/helpers/update/updates/Update_483.php
  application/views/admin/labels/_labelviewtabcontent_view.php
  application/views/questionAdministration/modals.twig
  assets/scripts/admin/questionEditor.js
  installer/create-database.php
Labels: Tested OK, Code checked

#2259 Fixed issue #15057: Translation screen not working correctly when there are long question text
  application/controllers/admin/translate.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/006-quickTranslate.scss
  assets/packages/adminbasics/scss/loadSass.js
Labels: Tested OK

#2276 Zoho/l41 t1704 duplicate comfort update checker plugin
  application/config/version.php
  application/helpers/update/updates/Update_484.php
Labels: Tested OK

#2280 Fixed issue #17926: No quotas adjustable
  application/views/admin/quotas/newanswer_view.php
Labels: Needs review, Needs testing

#2279 Fixed issue #17844: Deleting or Adding in the middle of a loaded label set not possible
  assets/scripts/admin/questionEditor.js
Labels: Needs review, Needs testing

#2085 Fixed issue #T386: Font is Different for Different Question Types in Response Filter
  application/views/admin/export/statistics_subviews/_question.php
  themes/admin/Apple_Blossom/css/statistics-rtl.css
  themes/admin/Apple_Blossom/css/statistics.css
  themes/admin/Bay_of_Many/css/statistics-rtl.css
  themes/admin/Bay_of_Many/css/statistics.css
  themes/admin/Black_Pearl/css/statistics-rtl.css
  themes/admin/Black_Pearl/css/statistics.css
  themes/admin/Dark_Sky/css/statistics-rtl.css
  themes/admin/Dark_Sky/css/statistics.css
  themes/admin/Free_Magenta/css/statistics-rtl.css
  themes/admin/Free_Magenta/css/statistics.css
  themes/admin/Noto_All_Languages/css/statistics-rtl.css
  themes/admin/Noto_All_Languages/css/statistics.css
  themes/admin/Purple_Tentacle/css/statistics-rtl.css
  themes/admin/Purple_Tentacle/css/statistics.css
  themes/admin/Sea_Green/css/statistics-rtl.css
  themes/admin/Sea_Green/css/statistics.css
  themes/admin/Sunset_Orange/css/statistics-rtl.css
  themes/admin/Sunset_Orange/css/statistics.css
Labels: Feedback

#2235 Fixed issue #17873: Remote Control `delete_language` fails to remove language
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs testing

#2273 Fixed issue #17677: Valid TSV file can not be used in VV import
  application/controllers/admin/DataEntry.php
  application/helpers/admin/import_helper.php
Labels: Bugfix

#2226 Fixed issue #17321: Array question are not split up on mobile devices when using vanilla theme
  application/config/version.php
  application/core/LsDefaultDataSets.php
  application/helpers/update/updates/Update_485.php
Labels: Needs update by author, Tested OK, Code checked

#2281 Fixed issue #17374: aSurveyInfo.datasecurity_notice_label does not return only the label
  application/config/internal.php
  application/models/Survey.php
  themes/survey/vanilla/views/subviews/privacy/privacy_datasecurity_notice_label.twig
Labels: Tested OK

#2269 Fixed issue #17846: Expression manager on file upload question type don't work on same page
  application/helpers/expressions/em_manager_helper.php
  application/views/survey/questions/answer/file_upload/answer.twig
  assets/scripts/expressions/em_javascript.js
  assets/scripts/modaldialog.js
  assets/scripts/uploader.js
Labels: Bugfix, Needs testing

#2299 Fixed issue #17964: View saved but not submitted responses don't work
  application/controllers/AdminController.php
Labels: Tested OK

#2290 Task/zoho l41 t1700 #17919 add new class for menu button
  application/libraries/MenuObjects/Menu.php
  application/libraries/MenuObjects/MenuButton.php
  application/libraries/MenuObjects/MenuButtonInterface.php
  application/libraries/MenuObjects/views/_extraMenu.php
  application/views/layouts/adminmenu.php
Labels: Tested OK

#2288 Fixed issue #17940: Array filter in combination with 'equals sum value' feature does not sum up values correctly
  application/core/QuestionTypes/MultipleNumericalQuestion/RenderMultipleNumerical.php
  application/views/survey/questions/answer/multiplenumeric/rows/dynamic.twig
  application/views/survey/questions/answer/multiplenumeric/rows/dynamic_slider.twig
Labels: Tested OK, Code checked

#2298 Fixed issue #17846: Expression manager on file upload question type don't work on same page
  application/helpers/expressions/em_manager_helper.php
  application/views/survey/questions/answer/file_upload/answer.twig
  assets/packages/expressions/em_javascript.js
  assets/packages/questions/upload/build/uploadquestion.js
  assets/packages/questions/upload/build/uploadquestion.min.js
  assets/packages/questions/upload/build/uploadquestion.min.js.map
  assets/packages/questions/upload/src/modaldialog.js
  assets/packages/questions/upload/src/uploader.js
Labels: Needs review, Tested OK

#2305 Fixed issue #17963: Numbers on text question does not detect blanks
  assets/scripts/expressions/em_javascript.js
Labels: Needs review, Tested OK

#2310 Fixed issue #17973: Error 404 for statisctics_user/action
  application/config/routes.php
  application/helpers/SurveyRuntimeHelper.php
Labels: Tested OK, Code checked

#2304 Dev #T355: Improvements: Label set
  application/controllers/QuestionAdministrationController.php
  application/views/admin/survey/Question/_subQuestionsAndAnwsersJsVariables.php
  application/views/questionAdministration/modals.twig
  assets/scripts/admin/questionEditor.js
Labels: Needs review, Tested OK

#2182 Fixed issue #17602: Errors while installing 5.1 with MySQL 8 and InnoDB
  application/models/InstallerConfigForm.php
Labels: Needs review, Tested OK

#2314 Fixed issue #17966: twig processString assumes wrong question Id
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/expressions/em_manager_helper.php
  application/helpers/replacements_helper.php
Labels: Needs review, Tested OK

#2315 Fixed issue #17966: twig processString assumes wrong question Id
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/expressions/em_manager_helper.php
Labels: Needs review, Tested OK

#2285 Fixed issue [security] : Missing password policy when saving a survey
  application/core/plugins/PasswordRequirement/PasswordRequirement.php
  application/core/plugins/PasswordRequirement/config.xml
  application/libraries/Save.php
Labels: Needs review, Tested OK

#2311 Fixed issue #17982: Malformed DSN when using MySQL socket and DB name during installation
  application/models/InstallerConfigForm.php
Labels: Bugfix, Tested OK, Code checked

#2308 Fixed issue #17974: Text input with numbers only are not filtered
  application/helpers/qanda_helper.php
  application/views/survey/questions/answer/shortfreetext/text/item.twig
  application/views/survey/questions/answer/shortfreetext/textarea/item.twig
Labels: Tested OK

#2297 Fixed issue #15057: Translation screen not working correctly when there are long question text
  application/controllers/admin/Translate.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/006-quickTranslate.scss
  assets/packages/adminbasics/scss/loadSass.js
Labels: Needs review, Tested OK
