Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-09, with the labels that each got.

#2575 Fixed issue #15195: Expiration date can be set before start date
  application/controllers/SurveyAdministrationController.php
  application/views/surveyAdministration/editLocalSettings_main_view.php
Labels: Tested OK, Code checked

#2521 Fixed issue #18183: Date filter at statistics is not applied correctly
  application/helpers/admin/statistics_helper.php
  application/views/admin/export/statistics_subviews/_question.php
Labels: Tested OK, Code checked, minor impact

#2574 Fixed issue #18301: Mass action drop-up menu looks like overflow hidden in question list
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
Labels: Tested OK, Code checked

#2284 Dev #8436: Enable / disable users and fields to manage users
  application/config/version.php
  application/controllers/UserManagementController.php
  application/core/plugins/Authdb/Authdb.php
  application/helpers/update/updates/Update_491.php
  application/models/User.php
  application/views/userManagement/partial/addedituser.php
  assets/packages/usermanagement/js/usermanagement.js
  installer/create-database.php
Labels: Tested OK, Code checked

#2520 Fixed issue #18247: php version 8 and remote control, error in bigdata.php
  application/libraries/BigData.php
Labels: Needs testing, Code checked, technical

#2600 Fixed issue #18351: Extra token placeholder show as invalid in expression
  application/helpers/common_helper.php
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code checked

#2604 Fixed issue #17870: Default value with line feed broke Expression Script
  application/helpers/expressions/em_manager_helper.php
Labels: Needs review, Needs testing, minor impact

#2564 Fixed issue #18133: Set "Other" state has no clue about current state
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/admin/survey/Question/massive_actions/_set_questions_other.php
Labels: Needs update by author, Tested OK

#2595 Fixed issue #18240: QuestioinTheme browserdetect, Show Platform information didn't work
  themes/question/browserdetect/survey/questions/answer/shortfreetext/text/item.twig
Labels: Tested OK, Code checked, minor impact

#2609 Fixed issue #16697: «inherit everything» still not translated
  application/helpers/twig_translation_helper.php
Labels: Needs testing, Code checked

#2610 Dev: fix really seacrh Question, not with language
  application/controllers/admin/CheckIntegrity.php
Labels: Needs review, minor impact

#2605 Fixed issue #17870: Default value with line feed broke Expression Script
  application/helpers/expressions/em_manager_helper.php
Labels: Needs testing, Tested OK, minor impact

#2601 Fixed issue #18351: Extra token placeholder show as invalid in expression
  application/helpers/common_helper.php
  application/helpers/expressions/em_manager_helper.php
Labels: Needs testing, Code checked

#2611 Dev: Allow beforeEmail events to update core replacement
  application/core/LimeMailer.php
Labels: Code checked, No impact

#2632 Fixed issue #18330: SurveySetting type date doesnt show datepicker
  application/extensions/SettingsWidget/SettingsWidget.php
Labels: Tested OK, Code review done, minor impact

#2597 Fixed issue #18287: Question List: Filtering doesn't work on type description
  application/models/Question.php
Labels: Feedback, Tested OK, Code review done
