Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-11, with the labels that each got.

#2695 Lsc 561 gc05 buttons
  application/core/TopbarConfiguration.php
  application/extensions/ButtonWidget/ButtonWidget.php
  application/extensions/ButtonWidget/README.md
  application/extensions/ButtonWidget/views/button.php
  application/extensions/TopbarWidget/views/includes/editGroupTopbarLeft_view.php
  application/extensions/TopbarWidget/views/includes/editQuestionTopbarLeft_view.php
  application/extensions/TopbarWidget/views/includes/groupTopbarLeft_view.php
  application/extensions/TopbarWidget/views/includes/languagesDropdownItems.php
  application/extensions/TopbarWidget/views/includes/previewGroupButton_view.php
  application/extensions/TopbarWidget/views/includes/previewOrRunButton_view.php
  application/extensions/TopbarWidget/views/includes/previewQuestionButton_view.php
  application/extensions/TopbarWidget/views/includes/previewSurveyAndGroupButtons_view.php
  application/extensions/TopbarWidget/views/includes/questionTopbarLeft_view.php
  application/extensions/TopbarWidget/views/includes/responsesExportDropdownItems.php
  application/extensions/TopbarWidget/views/includes/responsesImportDropdownItems.php
  application/extensions/TopbarWidget/views/includes/responsesTopbarLeft_view.php
  application/extensions/TopbarWidget/views/includes/surveyToolsDropdownItems.php
  application/extensions/TopbarWidget/views/includes/surveyTopbarLeft_view.php
  application/extensions/TopbarWidget/views/includes/tokensCreateDropdownItems.php
  application/extensions/TopbarWidget/views/includes/tokensInvRemDropdownItems.php
  application/extensions/TopbarWidget/views/includes/tokensTopbarLeft_view.php
  application/extensions/admin/grid/MassiveActionsWidget/views/listOfActions.php
  application/extensions/admin/grid/MassiveActionsWidget/views/selector.php
  application/extensions/admin/survey/ListSurveysWidget/views/massive_actions/_selector.php
  application/models/Survey.php
  application/views/admin/survey/subview/_survey_quickaction.php
  application/views/admin/survey/surveybar_activation.php
  application/views/admin/survey/surveybar_displayexport.php
  application/views/layouts/fullpagebar_view.php
  assets/admin_themes/Sea_Green/buttons/btn-group.scss
  assets/admin_themes/Sea_Green/buttons/buttons.scss
  assets/admin_themes/Sea_Green/lime-admin-colors.scss
  assets/admin_themes/Sea_Green/sea_green.scss
  assets/admin_themes/default_lime-admin-common.scss
  assets/bootstrap_5/scss/customizations.scss
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
  assets/packages/adminsidepanel/scss/custom.scss
  themes/admin/Sea_Green/css/lime-admin-common-rtl.css
  themes/admin/Sea_Green/css/lime-admin-common-rtl.min.css
  themes/admin/Sea_Green/css/lime-admin-common.css
  themes/admin/Sea_Green/css/lime-admin-common.min.css
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#2663 Fixed issue #16187: No proper error message when copying survey and ID already exists
  application/helpers/admin/import_helper.php
  application/views/surveyAdministration/tabCopy_view.php
Labels: Needs update by author, Tested OK, Code review done, minor impact

#2628 Fixed issue #15310: Display dropdown boxes - Date/Time question type not working correctly if minimum date < 1900
  application/helpers/expressions/em_manager_helper.php
  application/helpers/qanda_helper.php
Labels: Tested OK, Code review done, Decision needed

#2561 Fixed issue #17883: QueXML formatting cannot be changed
  application/controllers/PrintanswersController.php
  application/controllers/admin/export.php
  application/controllers/admin/responses.php
  application/libraries/admin/quexmlpdf.php
  application/views/admin/survey/queXMLSurvey_view.php
Labels: Tested OK, Code review done

#2218 New feature #8239: Allow for user friendly survey URLS
  application/config/version.php
  application/controllers/LimereplacementfieldsController.php
  application/controllers/SurveyAdministrationController.php
  application/controllers/admin/Database.php
  application/controllers/admin/ExpressionValidate.php
  application/core/LSYii_Application.php
  application/core/LSYii_Controller.php
  application/core/LSYii_ShortUrlValidator.php
  application/core/LimeMailer.php
  application/helpers/update/updates/Update_494.php
  application/models/Survey.php
  application/models/SurveyLanguageSetting.php
  application/views/admin/survey/editLocalSettings_view.php
  application/views/admin/survey/subview/surveydashboard/001-sharingpanel.twig
  installer/create-database.php
  tests/data/surveys/limesurvey_survey_shortUrlOpen.lss
  tests/data/surveys/survey_archive_shortUrlClosed.lsa
  tests/functional/frontend/ShortUrlTest.php
Labels: Test failed, Code review done

#2714 Fixed issue #15195: Expiration date can be set before start date
  application/models/Survey.php
Labels: Needs code review, Needs testing

#2719 Lsc 575 gc19 footer
  assets/admin_themes/Sea_Green/footer/footer.scss
  assets/admin_themes/Sea_Green/lime-admin-colors.scss
  assets/admin_themes/Sea_Green/sea_green.scss
  assets/admin_themes/adminbasics_temporary/000-lime-admin-common.scss
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.css
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build/css/adminsidepanel.css
  assets/packages/adminsidepanel/build/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/scss/custom.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#2721 Lsc 572 gc16 box
  assets/admin_themes/Sea_Green/box/box.scss
  assets/admin_themes/Sea_Green/lime-admin-colors.scss
  assets/admin_themes/Sea_Green/sea_green.scss
  assets/admin_themes/adminbasics_temporary/000-lime-admin-common.scss
  assets/admin_themes/default_statistics.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#2727 Fixed issue #15195: Expiration date can be set before start date
  application/models/Survey.php
Labels: Needs code review, Needs testing

#2733 Fixed issue #18488: Conditions are not properly highlighted if they have additional spaces
  application/helpers/expressions/em_manager_helper.php
  application/models/Question.php
  application/models/QuestionGroup.php
  application/views/questionAdministration/summary.php
Labels: Needs code review, Needs testing

#2706 Dev LB-34: Missing well styling for question group description
  themes/survey/vanilla/css/base.css
Labels: Tested OK, Code review done

#2722 Fixed issue #18463: List of uploaded files should be sorted alphabetically
  application/models/TemplateConfiguration.php
Labels: Tested OK, Code review done

#2725 Fixed issue #16187: Cant Create Custom Survey ID (need proper error message)
  application/helpers/admin/import_helper.php
  application/views/admin/survey/subview/tabCopy_view.php
Labels: Tested OK, Code review done

#2691 Fixed issue #17648: Email received by participant is empty
  application/controllers/admin/Tokens.php
Labels: Tested OK, Code review done

#2705 Fixed issue #18424: typo in debug message
  application/views/admin/globalsettings/globalSettings_view.php
  modules/admin/globalsettings/views/_overview.php
  modules/admin/globalsettings/views/globalSettings_view.php
Labels: Code review done, Technical

#2645 New feature #18375: [security] Some plugin settings need encryption
  application/libraries/PluginManager/PluginBase.php
  tests/data/plugins/SettingsPlugin.php
  tests/functional/backend/SettingsPluginTest.php
Labels: Needs testing, Code review done, Technical

#2656 Fixed issue #18373: Saving statistics exports to excel fails
  application/config/vendor.php
Labels: Code review done

#2741 Fiex issue #18086: Custom "other" label text not applied to Bootstrap button layout
  application/core/QuestionTypes/MultipleChoice/RenderMultipleChoice.php
  application/views/survey/questions/answer/multiplechoice/answer.twig
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/answer.twig
Labels: Tested OK, Code review done

#2655 Fixed issue #18395: Access to limereplacementfields didn't check read permission on survey
  application/controllers/LimereplacementfieldsController.php
Labels: Tested OK, Code review done

#2643 Fixed issue #14310: Google Analytics functionality doesn't work
  application/config/internal.php
  application/controllers/PrintanswersController.php
  application/controllers/Statistics_userController.php
  application/controllers/survey/index.php
  application/core/LS_Twig_Extension.php
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/common_helper.php
  application/helpers/replacements_helper.php
  application/models/Survey.php
  themes/survey/vanilla/views/subviews/header/google_analytics.twig
Labels: Tested OK, Code review done
