Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-05, with the labels that each got.

#2367 Fixed issue #18047: Conditional filters attachments for confirmation mail doesn't work
  application/core/LimeMailer.php
  application/views/admin/emailtemplates/emailtemplates_view.php
Labels: Bugfix, Needs testing, Code checked

#2354 Fixed issue #18036: Database error when renumbering a scenario
  application/controllers/admin/ConditionsAction.php
  application/views/admin/conditions/includes/conditions_scenario.php
Labels: Tested OK, Code checked

#2346 Fixed issue #17739: list_surveys JSON-RPC API method does not obey if set
  application/models/Survey.php
Labels: Code checked

#2369 Fixed issue #14123: Slider left/right labels not displayed correctly on iPad
  application/config/version.php
  themes/survey/bootswatch/css/theme.css
  themes/survey/vanilla/css/theme.css
Labels: Tested OK, Code checked

#2356 Fixed issue #17889: Setting to correct server time not taken into account when sending email invitations
  application/controllers/admin/tokens.php
Labels: Tested OK, Code checked

#2406 Fixed issue : beforeActivate event don't happen
  application/controllers/admin/PluginManagerController.php
Labels: Bugfix, Needs review, Needs testing, Plugin, NoMantisReport

#2384 Fixed issue #18066: RPC method `upload_file` does not honor `$sFileName` argument in response
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs review, Needs testing

#2377 Fixed issue #18051: API: Deleting a question crashes in 3.x
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs review, Needs testing

#2347 Fixed issue #18027: Unable to create a label set
  application/views/admin/labels/_labelviewtabcontent_view.php
  assets/scripts/admin/labels.js
Labels: Needs review, Tested OK

#2349 Fixed issue #17991: Importing a question from the "List questions" menu fails with 400 error
  application/controllers/admin/questions.php
  application/views/admin/survey/surveybar_addgroupquestion.php
Labels: Tested OK, Code checked

#2283 Fixed issue #17678: VV export didn't shown sub question
  application/controllers/admin/Export.php
  application/views/admin/export/vv_view.php
Labels: Tested OK

#2373 Fixed issue #18041: Security Vulnerability: KCFInder using old JQuery/jQuery UI version
  third_party/kcfinder/cache/base.js
  third_party/kcfinder/js/000._jquery.js
  third_party/kcfinder/js/002._jqueryui.js
  third_party/kcfinder/js/060.toolbar.js
Labels: Needs testing, Code checked

#2409 Fixed issue #16154: Not all files imported with custom question theme
  application/config/config-defaults.php
Labels: Tested OK, Code checked

#2408 Fixed issue #18076: Input on demand question type not working when setting multiple rows
  themes/question/inputondemand/survey/questions/answer/multipleshorttext/rows/answer_row_textarea.twig
Labels: Tested OK, Code checked

#2401 Fixed issue #17889: Setting to correct server time not taken into account when sending email invitations
  application/controllers/admin/Tokens.php
Labels: Tested OK, Code checked

#2361 Fixed issue #17900: Response date is incorrect when there is a mis-match in date format
  application/controllers/ResponsesController.php
Labels: Tested OK, Code checked

#2364 Fixed issue #18020: Notification emails are sent in the base language
  application/helpers/frontend_helper.php
Labels: Needs review, Needs testing

#2428 Fixed issue #18113: removed unused controller action getAdvancedOptio…
  application/controllers/QuestionAdministrationController.php
Labels: Bugfix, Needs review, Needs testing

#2395 Fixed issue #17987 : quota url need to be decoded
  application/controllers/admin/quotas.php
  application/helpers/frontend_helper.php
Labels: Bugfix, Needs review, Needs testing

#2396 Fixed issue #17987 : quota url need to be decoded
  application/controllers/admin/Quotas.php
  application/helpers/frontend_helper.php
Labels: Bugfix, Needs review, Needs testing

#2383 Fixed issue #17852: SPSS data file doesn't include participants records
  application/helpers/export_helper.php
Labels: Needs review, Needs testing

#2402 Fixed issue #18045: User details last login is not shown completed
  application/models/User.php
Labels: Needs review, Tested OK

#2415 Fixed issue #17709: DB session lifetime ignore GUI settings
  application/core/LSYii_Application.php
  application/core/web/DbHttpSession.php
Labels: Bugfix, Needs review, Needs testing

#2416 Fixed issue #17709: Session timeout ignoring settings
  application/core/LSYii_Application.php
Labels: Bugfix, Needs review, Needs testing

#2376 RemoteControl: Fix remaining invalid session key error message
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Needs update by author, Needs testing

#2389 Fixed Issue #17978: Public stat show all response and not only submitted
  application/helpers/userstatistics_helper.php
Labels: Needs review, Needs testing

#2378 Fixed issue #17980: Txt Import Crashing with just exported survey
  application/helpers/admin/import_helper.php
  application/models/AnswerL10n.php
  application/models/QuestionL10n.php
Labels: Needs review, Needs testing

#2362 Fixed issue #17994: Comments at question type "List with comments" are missing at print answer overview
  application/models/SurveyDynamic.php
  themes/survey/vanilla/views/subviews/printanswers/question_types/template_list-with-comment.twig
Labels: Needs testing, Code checked

#2316 New feature #17835: Add custom token attributes to Response details screen
  application/controllers/ResponsesController.php
Labels: Tested OK, Code checked

#2386 Fixed issue #18060: 'Save as default values' question setting not working properly
  application/extensions/GeneralOptionWidget/settings/SaveAsDefaultGeneralOption.php
  application/models/services/QuestionAttributeFetcher.php
  application/models/services/QuestionAttributeHelper.php
Labels: Needs review, Needs testing

#2435 Fixed issue #18086: Custom 'other' label text not applied to Bootstrap button layout
  application/core/QuestionTypes/ListRadio/RenderListRadio.php
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/answer.twig
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/rows/answer_row_other.twig
Labels: Tested OK, Code checked

#2447 Fixed Issue #18152: Unable to manage theme with debug set
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/config.xml
Labels: Needs testing, Code checked

#2441 Fixed issue #17837: Directly show edit mode: some quirks
  application/controllers/QuestionGroupsAdministrationController.php
  application/extensions/TopbarWidget/views/includes/groupToolsDropdownItems.php
Labels: Needs review, Needs testing

#2433 Fixed issue #18129 : Check of json data for upload question
  application/helpers/expressions/em_manager_helper.php
  application/helpers/frontend_helper.php
Labels: Needs review, Needs testing

#2337 Fixed issue #18026: Session expire message when submit button is clicked twice
  assets/packages/limesurvey/survey.js
Labels: Needs update by author, Needs review, Needs testing, Discussion ongoing
