Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-08, with the labels that each got.

#2549 Fixed issue #18288: Can't assign groups to surveys
  application/controllers/admin/SurveyPermission.php
  application/helpers/common_helper.php
Labels: Needs review, Tested OK, minor impact

#2522 Fixed issue #18194: Link after import survey goes to subquestion edit
  application/controllers/SurveyAdministrationController.php
Labels: Tested OK, Code checked

#2545 Fixed issue #17135: activating Public statistics option causes json to display
  application/views/admin/export/statistics_subviews/_statistics_view_scripts.php
Labels: Tested OK, Code checked

#2548 Fixed issue #18280: Conditions Designer Crash with Database Error
  application/controllers/admin/ConditionsAction.php
Labels: Needs review, Tested OK, minor impact

#2524 Fixed issue #18249: INSERTANS correction broken when import
  application/helpers/common_helper.php
Labels: Tested OK, Code checked, minor impact

#2559 Fixed issue #18298: Saving in question organizer always prompts
  assets/scripts/admin/organize.js
Labels: Needs review, Needs testing, minor impact

#2553 Fixed issue #17067: Subquestion Relevance in array by column does not work
  application/views/questionAdministration/subquestionRow.twig
  application/views/questionAdministration/subquestions.twig
Labels: Needs testing, Discussion ongoing, Code checked

#2557 Fixed issue #18299: Simple statistics, "Text Display" questions are shown
  application/controllers/admin/Statistics.php
Labels: Needs review, Needs testing, minor impact

#2554 Fixed issue #18261: Simple statistics, 'Array (5 point choice)' dont show subquestions
  application/helpers/admin/statistics_helper.php
  application/views/admin/export/generatestats/simplestats/_statisticsoutput_header.php
Labels: Needs review, Needs testing, minor impact

#2547 Fixed issue #18271: Blank page after clicking "Close"
  application/controllers/QuestionAdministrationController.php
  application/extensions/TopbarWidget/views/includes/editQuestionTopbarRight_view.php
Labels: Needs testing, Code checked

#2437 Fixed issue #17872: Answerfilters reset after pagination changed
  application/extensions/LimeGridView/LimeGridView.php
  application/views/admin/token/browse.php
  application/views/questionAdministration/listquestions.php
  application/views/questionGroupsAdministration/listquestiongroups.php
  application/views/responses/listResponses_view.php
Labels: Tested OK, Code checked

#2552 Fixed issue #18162: Design options: missing translation / icon
  application/helpers/twig_translation_helper.php
Labels: Tested OK, Code checked, minor impact

#2546 Fixed issue #18270: Language switch is not repopulated correctly after change question type
  assets/scripts/admin/questionEditor.js
Labels: Tested OK, Code checked

#2519 Fixed issue #18259: add surveyId to select box
  application/views/admin/participants/modal_subviews/_addToSurvey.php
Labels: Tested OK, Code checked, minor impact

#2555 Fixed issue #17745: Incomplete instructions to export response data to SPSS using Python
  application/views/admin/export/spss_view.php
Labels: Needs review, Needs testing, minor impact

#2523 Fixed issue #18199: Top menu language changer didn't appear for register
  themes/survey/vanilla/views/subviews/content/register.twig
Labels: Tested OK

#2558 Fixed issue #15195: Expiration date can be set before start date
  application/models/Survey.php
  application/views/admin/survey/subview/accordion/_publication_panel.php
  application/views/surveyAdministration/editLocalSettings_main_view.php
  assets/scripts/admin/surveysettings.js
Labels: Needs review, Tested OK

#2573 Fixed issue #16795: typo in default text for confirmation email (in english)
  application/core/LsDefaultDataSets.php
Labels: Needs review, Needs testing, minor impact

#2572 Fixed issue #16795: typo in default text for confirmation email (in english)
  application/core/LsDefaultDataSets.php
Labels: Needs review, Needs testing, minor impact

#2569 Fixed issue 17485: The getAnswerQuery method cannot be used in the Answers model
  application/models/Answer.php
Labels: Tested OK, Code checked, minor impact, technical

#2527 Fixed model relations referring to in-existing objects, add unit test…
  application/models/QuestionGroupL10n.php
  application/models/Survey.php
  application/models/SurveyLink.php
  tests/bootstrap.php
  tests/unit/models/AnswerL10nTest.php
  tests/unit/models/AnswerTest.php
  tests/unit/models/BaseModelTestCase.php
  tests/unit/models/ConditionTest.php
  tests/unit/models/DefaultValueTest.php
  tests/unit/models/Label10nTest.php
  tests/unit/models/LabelSetTest.php
  tests/unit/models/LabelTest.php
  tests/unit/models/ParticipantAttributeNameTest.php
  tests/unit/models/ParticipantAttributeTest.php
  tests/unit/models/ParticipantTest.php
  tests/unit/models/PermissionTest.php
  tests/unit/models/QuestionAttributeTest.php
  tests/unit/models/QuestionGroupL10nTest.php
  tests/unit/models/QuestionGroupTest.php
  tests/unit/models/QuestionL10nTest.php
  tests/unit/models/QuestionTest.php
  tests/unit/models/QuotaLanguageSettingTest.php
  tests/unit/models/QuotaMemberTest.php
  tests/unit/models/QuotaTest.php
  tests/unit/models/SurveyLanguageSettingTest.php
  tests/unit/models/SurveyLinkTest.php
  tests/unit/models/SurveyMenuEntriesTest.php
  tests/unit/models/SurveyMenuTest.php
  tests/unit/models/SurveyTest.php
  tests/unit/models/SurveyUrlParameterTest.php
  tests/unit/models/SurveysGroupSettingsTest.php
  tests/unit/models/SurveysGroupsTest.php
  tests/unit/models/TutorialTest.php
  tests/unit/models/UserGroupTest.php
  tests/unit/models/UserInPermissionRoleTest.php
  tests/unit/models/UserTest.php
Labels: Code checked, technical

#2490 Fixed issue #18209: Missing RemoteControl function to get the field mapping
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/limesurvey_survey_remote_api_get_fieldmap.lss
  tests/helpers/RemoteControlTest.php
Labels: Feature, Needs testing, Code checked, minor impact, technical

#2566 Fixed issue #18134: Present subquestions/answer options in random order has no clue about current state
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/admin/survey/Question/massive_actions/_set_subquestansw_order.php
Labels: Tested OK, Code checked

#2577 Fixed issue #18316: User role cannot be deleted with action button
  application/controllers/UserRoleController.php
  application/models/Permissiontemplates.php
Labels: Needs testing, Code checked

#2576 Fixed issue #18286: Filter by group name in Group List, does not work
  application/controllers/QuestionGroupsAdministrationController.php
Labels: Needs update by author, Needs review, Tested OK, minor impact

#2567 Fixed issue #18305: Deleting a user that owns survey participans causes error on view CPDB
  application/controllers/UserManagementController.php
  application/models/Participant.php
Labels: Tested OK, Code checked, minor impact

#2556 Fixed issue #18242: Quick translation: end note not shown
  application/controllers/admin/Translate.php
  application/views/admin/translate/translatefields_view.php
Labels: Tested OK, Code checked, minor impact
