Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-10, with the labels that each got.

#2642 Fixed issue #17950: is_int(false) returns true
  application/helpers/expressions/em_core_helper.php
  tests/unit/helpers/ExpressionCoreFunctionsTest.php
Labels: Needs testing, Code review done, minor impact

#2431 Fixed issue #17950: is_int(false) returns true
  application/helpers/expressions/em_core_helper.php
Labels: Needs code review, Needs testing, minor impact, Technical

#2636 New feature #8436: Enable / disable users and fields to manage users
  application/core/plugins/Authdb/Authdb.php
  application/models/User.php
  tests/TestBaseClassWeb.php
  tests/TestHelper.php
  tests/functional/backend/UserManagementTest.php
Labels: Needs code review

#2626 Fixed issue: HTML tags are not allowed for admins in participant attributes
  application/controllers/RegisterController.php
  application/models/Token.php
Labels: Needs code review, Needs testing

#2637 Fixed issue #17825: Strings “LimeSurvey internal database” not available for translation in GlotPress
  application/core/plugins/Authdb/Authdb.php
  application/libraries/PluginManager/AuthPluginBase.php
  application/views/admin/authentication/login.php
Labels: Tested OK, Code review done

#2644 Fixed issue #18323: When copying a question with sub-questions, the sub-questions are not copied
  application/models/services/CopyQuestion.php
Labels: Needs testing, Tested OK, Code review done

#2608 Fixed issue #18307: A comment string starting with a '<' is not saved using Multiple choice with comments
  application/controllers/ResponsesController.php
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#2551 Fixed issue #15195: Expiration date can be set before start date
  application/controllers/admin/surveyadmin.php
  application/models/Survey.php
  application/views/admin/survey/editLocalSettings_main_view.php
  application/views/admin/survey/subview/accordion/_publication_panel.php
  assets/scripts/admin/surveysettings.js
Labels: Tested OK, Code review done

#2571 17117: 'Send invitations' button does nothing after failed send invitations
  application/controllers/admin/tokens.php
Labels: Tested OK, Code review done, minor impact

#2544 Fixed issue #17173: Publication and access setting 'listed publicly' not displayed correctly
  application/views/admin/survey/surveySummary_view.php
Labels: Tested OK, Code review done, minor impact

#2659 Uqt013 bootstrap dropdown
  assets/packages/expressions/em_javascript.js
  assets/survey_themes/fruity/src/definitions.scss
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/answer.twig
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/assets/scripts/bootstrapbuttons.js
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/rows/answer_row.twig
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/rows/answer_row_noanswer.twig
  themes/question/bootstrap_buttons/survey/questions/answer/listradio/rows/answer_row_other.twig
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/answer.twig
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/assets/scripts/bootstrapbuttons.css
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/assets/scripts/bootstrapbuttons.js
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/rows/answer_row.twig
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/rows/answer_row_other.twig
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/answer.twig
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/assets/scripts/bootstrap-select.min.css
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/assets/scripts/bootstrap-select.min.js
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/rows/othertext.twig
  themes/survey/bootswatch/css/theme.css
  themes/survey/fruity/css/variations/apple_blossom.css
  themes/survey/fruity/css/variations/bay_of_many.css
  themes/survey/fruity/css/variations/black_pearl.css
  themes/survey/fruity/css/variations/free_magenta.css
  themes/survey/fruity/css/variations/purple_tentacle.css
  themes/survey/fruity/css/variations/sea_green.css
  themes/survey/fruity/css/variations/skyline_blue.css
  themes/survey/fruity/css/variations/sunset_orange.css
  themes/survey/vanilla/css/theme.css
Labels: Tested OK, Code review done

#2658 Uqt01.2 bootstrap buttons
  themes/survey/bootswatch/css/theme.css
  themes/survey/fruity/css/variations/apple_blossom.css
Labels: Tested OK, Code review done

#2662 Fixed issue #18410: LDAP authentication option labelled as PluginBase
  application/libraries/PluginManager/AuthPluginBase.php
Labels: Needs code review

#2667 Uqt01.6 list radio
  application/views/survey/questions/answer/listradio/rows/answer_row_other.twig
Labels: Tested OK, Code review done

#2668 Lsc 401 uqt03.1 bootstrap buttons
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/answer.twig
  themes/survey/bootswatch/css/theme.css
Labels: Tested OK, Code review done

#2669 Lsc 404 uqt03.4 multiple choice with comment
  application/views/survey/questions/answer/multiplechoice_with_comments/answer.twig
  application/views/survey/questions/answer/multiplechoice_with_comments/rows/answer_row.twig
  application/views/survey/questions/answer/multiplechoice_with_comments/rows/answer_row_other.twig
  assets/packages/template-core/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css
Labels: Tested OK, Code review done

#2671 simplified usage of datepickerInit.js while enhancing features.
  application/extensions/DateTimePickerWidget/DateTimePicker.php
  application/views/admin/token/massive_actions/_update.php
  application/views/admin/token/tokenform.php
  assets/packages/datetimepicker/README.md
  assets/packages/datetimepicker/datepickerInit.js
  assets/packages/usermanagement/js/usermanagement.js
  assets/scripts/admin/listresponse.js
  assets/scripts/admin/tokens.js
Labels: Code review done

#2649 Fixed issue #18403: Dump when loading demo site
  locale/te/te.mo
Labels: Tested OK, Code review done

#2633 UQT04.3 File upload
  application/views/survey/questions/answer/file_upload/answer.twig
  assets/bootstrap_5/build/css/bootstrap_5-rtl.css
  assets/bootstrap_5/build/css/bootstrap_5-rtl.min.css
  assets/bootstrap_5/build/css/bootstrap_5.css
  assets/bootstrap_5/build/css/bootstrap_5.min.css
  assets/bootstrap_5/scss/customizations.scss
  assets/packages/questions/upload/build/uploadquestion.js
  assets/packages/questions/upload/build/uploadquestion.min.js
  assets/packages/questions/upload/build/uploadquestion.min.js.map
Labels: Test failed, Code review done

#2641 UQT04.6 Multiple numerical input
  application/views/survey/questions/answer/multiplenumeric/rows/input/answer_row.twig
Labels: Tested OK, Code review done

#2685 Fixed issue #18427: LDAP plugin error when try to create new user on PHP8.1
  application/core/plugins/AuthLDAP/AuthLDAP.php
Labels: Needs code review, Needs testing, Tested OK

#2635 Fixed issue #18358: Statistics filter feature is not working properly
  application/helpers/admin/statistics_helper.php
Labels: Needs code review, Tested OK

#2673 Fixed issue #18102: Export Duplicate entries in the Excel Form
  application/core/db/MssqlCommandBuilder.php
  application/core/db/MssqlSchema.php
Labels: Tested OK, Code review done, Technical

#2678 Fixed issue #18414: 'Add line' button label can not be translated
  application/commands/TwigCommand.php
Labels: Tested OK, Code review done, Technical
