Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-02, with the labels that each got.

#2208 17719: Question list not updated when adding/changing questions (jest)
  assets/packages/adminsidepanel/.gitignore
  assets/packages/adminsidepanel/babel.config.cjs
  assets/packages/adminsidepanel/babel.config.js
  assets/packages/adminsidepanel/eventbus.js
  assets/packages/adminsidepanel/jest.config.cjs
  assets/packages/adminsidepanel/old.eslintrc.json
  assets/packages/adminsidepanel/old.webpack.config.js
  assets/packages/adminsidepanel/package.json
  assets/packages/adminsidepanel/src/adminsidepanelmain.js
  assets/packages/adminsidepanel/src/components/sidebar.vue
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
  assets/packages/adminsidepanel/src/components/subcomponents/_sidemenu.vue
  assets/packages/adminsidepanel/src/components/subcomponents/_submenu.vue
  assets/packages/adminsidepanel/src/components/subcomponents/questionexplorer/_addQuestionGroupAndAddQuestionButtons.vue
  assets/packages/adminsidepanel/src/components/subcomponents/questionexplorer/_listOfAllQuestionGroupsWithQuestions.vue
  assets/packages/adminsidepanel/src/components/subcomponents/questionexplorer/_questionExplorer.vue
  assets/packages/adminsidepanel/src/mixins/pjaxMixins.js
  assets/packages/adminsidepanel/src/mixins/toolTipsMixins.js
  assets/packages/adminsidepanel/src/mixins/translateMixins.js
  assets/packages/adminsidepanel/src/store/state.js
  assets/packages/adminsidepanel/tests/AdminSidePanel.spec.js
  assets/packages/adminsidepanel/vue.config.cjs
  assets/packages/adminsidepanel/yarn.lock
Labels: Needs testing

#2212 Fixed issue #17790: KCFinder Image Browse Server not working due to incorrect cookieDomain
  application/helpers/admin/htmleditor_helper.php
Labels: Bugfix

#2225 Various file upload issues
  application/controllers/ResponsesController.php
  application/controllers/UploaderController.php
  application/helpers/common_helper.php
  application/helpers/expressions/em_manager_helper.php
  application/helpers/qanda_helper.php
  application/helpers/sanitize_helper.php
  application/models/SurveyDynamic.php
  application/views/survey/questions/answer/file_upload/answer.twig
  assets/packages/questions/upload/build/uploadquestion.js
  assets/packages/questions/upload/build/uploadquestion.min.js
  assets/packages/questions/upload/src/modaldialog.js
  assets/packages/questions/upload/styles/uploader.css
  assets/styles-public/browse.css
Labels: Tested OK, Code checked

#2211 Fixed issue #16230: Reload survey (token answer persistence) don't really reload
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/expressions/em_manager_helper.php
  application/helpers/frontend_helper.php
Labels: Needs review, Tested OK

#2223 Fixed issue #17833: Multiple choice: 'Text input box size' has no effect.
  application/views/survey/questions/answer/multiplechoice/config.xml
Labels: Bugfix, Tested OK, Code checked

#2206 Dev #T238: Enable duplication of survey including pictures
  application/controllers/SurveyAdministrationController.php
  application/helpers/admin/import_helper.php
  application/models/services/CopySurveyResources.php
  application/views/surveyAdministration/tabCopy_view.php
  tests/data/surveys/limesurvey_survey_994476_CopySurveyResources.lss
  tests/unit/helpers/CopySurveyResourcesTest.php
Labels: Code checked

#2222 Fixed issue #17770: New Version: Error with answercodes
  assets/scripts/admin/questionEditor.js
Labels: Code checked

#2138 Fixed issue #T1055: Optimization open/closed-access mode and survey activation screens
  application/controllers/admin/Tokens.php
  application/views/admin/token/afterDeleteParticipantsTable.php
Labels: Needs update by author

#2230 exclude build/devel/test files from export to zip/tarball
  .gitattributes
Labels: Needs testing, Code checked

#2210 Fixed issue #17798: Set authwebserver as default didn't deactivate AuthDB usage
  application/core/plugins/Authwebserver/Authwebserver.php
Labels: Needs testing

#2177 Fixed issue #17677: Valid TSV file can not be used in VV import
  application/helpers/admin/import_helper.php
Labels: Needs testing

#2202 Dev #T266: Implement CPDB blacklist functions
  application/config/routes.php
  application/controllers/LimereplacementfieldsController.php
  application/controllers/OptinController.php
  application/controllers/OptoutController.php
  application/controllers/admin/ExpressionValidate.php
  application/controllers/admin/ParticipantsAction.php
  application/core/LimeMailer.php
  application/datavalueobjects/BlacklistResult.php
  application/models/Participant.php
  application/models/Token.php
  application/models/services/ParticipantBlacklistHandler.php
  application/views/admin/participants/blacklist_view.php
  tests/data/surveys/survey_archive_993688_participantBlacklist.lsa
  tests/unit/helpers/ParticipantBlacklistHandlerTest.php
  themes/survey/vanilla/views/subviews/content/optin.twig
  themes/survey/vanilla/views/subviews/content/optout.twig
Labels: Needs review, Needs testing

#2262 Fixed issue #12105: Scroll bar partially broken at browse response screen
  application/views/responses/listResponses_view.php
  assets/scripts/admin/listresponse.js
Labels: Tested OK

#2175 Fixed issue #17787: open_base_dir + debug can throw error when load s…
  application/models/QuestionTemplate.php
Labels: Bugfix, Discussion ongoing

#2090 Fixing wrong sort order in statisstics output (# 17647)
  application/helpers/common_helper.php
Labels: Needs review, Needs testing

#2009 New feature #17520: Auto-create LDAP users without bind DN
  application/core/plugins/AuthLDAP/AuthLDAP.php
Labels: Feedback

#2072 Fixed issue: Survey participant data with quotes are not properly exported in CSV
  application/helpers/export_helper.php
Labels: Feedback, NoMantisReport

#2073 Fixed issue: Survey participant data with quotes are not properly exported in CSV
  application/helpers/export_helper.php
Labels: Feedback, NoMantisReport

#2102 Fix notice "Trying to access array offset on value of type bool"
  application/helpers/admin/statistics_helper.php
Labels: Feedback, NoMantisReport

#2251 Fixed issue #17322: [security] Separate settings for administration & participants for handling failed login attempts
  application/config/config-defaults.php
  application/config/version.php
  application/controllers/admin/Authentication.php
  application/controllers/admin/GlobalSettings.php
  application/controllers/survey/index.php
  application/core/LSUserIdentity.php
  application/helpers/frontend_helper.php
  application/helpers/update/updates/Update_481.php
  application/models/FailedLoginAttempt.php
  application/views/admin/globalsettings/_security.php
  installer/create-database.php
Labels: Needs testing, Code checked

#2266 Fixed issue #17838: Add javascript in script tab only works for superadmin
  application/core/LsDefaultDataSets.php
  application/views/admin/user/personalsettings.php
Labels: Needs review, Tested OK
