Repository LimeSurvey/LimeSurvey, pull requests merged in 2022-01, with the labels that each got.

#2174 Fixed issue: Deactivate / Stop Survey Message Change
  application/views/surveyAdministration/deactivateSurvey_view.php
Labels: Needs testing

#2189 Fixed issue #17751: Date stamped throw php notice when data edit and debug
  application/controllers/admin/dataentry.php
Labels: Bugfix, Needs review, Tested OK

#2197 Fixed issue #17802: Error shown when try to load a saved survey
  application/controllers/survey/index.php
Labels: Needs review, Needs testing

#2195 Fixed issue #17801: No way to go to submit button in create group or question form with keyboard
  application/extensions/TopbarWidget/views/includes/addGroupTopbarRight_view.php
  application/extensions/TopbarWidget/views/includes/editQuestionTopbarRight_view.php
Labels: Tested OK

#2190 Fixed issue #17774: Dual scale answer texts are not exported correctly when using full text option
  application/helpers/admin/export/SurveyObj.php
Labels: Tested OK, Code checked

#2203 Fixed issue #17720: Wrong statistics with Other answers in single choice questions
  application/helpers/admin/statistics_helper.php
Labels: Tested OK, Code checked

#2166 Fixed issue #17618: Conversion failed when converting the nvarchar value 'NaN' to data type int
  assets/scripts/admin/questionEditor.js
Labels: Needs testing, Code checked

#2201 Fixed issue #17773: Code name change while we updated from Edit Quest…
  application/config/version.php
  application/helpers/update/updatedb_helper.php
  application/views/admin/labels/_labelviewtabcontent_view.php
  application/views/admin/survey/Question/question_subviews/_modals.twig
  assets/scripts/admin/answers.js
  installer/create-database.php
Labels: Needs testing, Code checked

#2199 Fixed issue #17791: 'Condition' vs. 'Relevance equation'
  application/views/questionGroupsAdministration/addGroup_view.php
  application/views/questionGroupsAdministration/editGroup_view.php
  application/views/questionGroupsAdministration/group_view.php
Labels: Tested OK

#2128 Fixed issue: Show full name of a deleted user correctly
  application/controllers/admin/useraction.php
  application/models/User.php
  application/views/admin/user/deluser.php
  assets/scripts/admin/users.js
Labels: Feedback, NoMantisReport

#2188 Fixed issue #17751: Date stamped throw php notice when data edit and debug
  application/controllers/admin/dataentry.php
Labels: Bugfix

#2191 Dev #7367: 'Other answer' at a certain position in the list
  application/core/QuestionTypes/ListDropdown/RenderListDropdown.php
  application/core/QuestionTypes/ListRadio/RenderListRadio.php
  application/core/QuestionTypes/MultipleChoice/RenderMultipleChoice.php
  application/core/QuestionTypes/MultipleChoiceWithComments/RenderMultipleChoiceWithComments.php
  application/views/survey/questions/answer/list_dropdown/config.xml
  application/views/survey/questions/answer/listradio/config.xml
  application/views/survey/questions/answer/multiplechoice/config.xml
  application/views/survey/questions/answer/multiplechoice_with_comments/config.xml
  tests/data/surveys/limesurvey_survey_767665_ListRadioOtherPositionTest.lss
  tests/functional/frontend/ListRadioOtherPositionTest.php
Labels: Tested OK

#2193 Fixed issue #17518: Non-ascii characters in email addresses
  application/core/LimeMailer.php
  application/third_party/idna-convert/LICENCE
  application/third_party/idna-convert/ReadMe.txt
  application/third_party/idna-convert/idna_convert.class.php
  application/third_party/idna-convert/transcode_wrapper.php
  application/third_party/idna-convert/uctc.php
Labels: Code checked

#2219 Fixed issue #17851: Placeholder {name.NAOK} gets replaced with survey title
  application/helpers/frontend_helper.php
  application/helpers/replacements_helper.php
Labels: Bugfix, Needs testing

#2198 Fixed issue #17776: New security settings
  application/config/config-defaults.php
  application/controllers/admin/PluginManagerController.php
  application/libraries/ExtensionInstaller/PluginInstaller.php
  application/libraries/PluginManager/PluginManager.php
  application/views/admin/super/fullpagebar_view.php
Labels: Needs testing
