Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-12, with the labels that each got.

#3645 Fixed issue #18961: {SURVEYURL} not complete URL
  application/core/LSYii_Application.php
  application/core/Traits/LSApplicationTrait.php
Labels: Tested OK, Code review done

#3607 Fixed issue : unable to update from pre 495 version
  application/models/User.php
Labels: Needs code review, Needs testing

#3642 Fixed issue #19262: Invalid fruity_twentythree template directory on …
  application/helpers/update/updates/Update_617.php
Labels: Tested OK, Code review done

#3660 fixed url when directLogin true
  application/controllers/RegisterController.php
Labels: Code review done

#3647 Fixed issue #19282: Statistics of a survey: response filters disapear after first excel exported
  application/extensions/AccordionWidget/AccordionWidget.php
  application/extensions/AccordionWidget/views/accordion.php
  application/views/admin/export/statistics_subviews/_response_filter_choice.php
  application/views/admin/export/statistics_view.php
  assets/scripts/admin/statistics.js
Labels: Tested OK, Code review done

#3656 Fixed issue #19290: Wrong Row Total in Array (Texts)
  assets/packages/questions/arraynumeric/scripts/array-totalsum.js
Labels: Tested OK, Code review done

#3658 Fixed issue #19293: Can't take survey after adding language in PHP 8.1
  application/helpers/SurveyRuntimeHelper.php
Labels: Tested OK, Code review done

#3662 Fixed issue #19245: Search surveys status options do not work
  application/models/Survey.php
Labels: Tested OK, Code review done

#3661 Fixed issue #19245: Search surveys status options do not work
  application/models/Survey.php
Labels: Tested OK, Code review done

#3657 Fixed issue #19251: Can't add Regex condition in survey
  assets/scripts/admin/conditions.js
Labels: Tested OK, Code review done

#3665 Fixed issue [security] #19117: Account past their expiration date can be still active
  application/controllers/admin/Authentication.php
  application/core/LSWebUser.php
  application/core/Traits/LSApplicationTrait.php
  application/models/User.php
Labels: Needs testing, Code review done

#3659 New feature #19308: Preview survey in modal (MW-728)
  application/controllers/survey/SurveyIndex.php
  application/helpers/SurveyRuntimeHelper.php
  application/views/surveyAdministration/sidebody.php
  themes/survey/fruity_twentythree/views/subviews/header/nav_bar.twig
  themes/survey/fruity_twentythree/views/subviews/messages/warnings.twig
  themes/survey/fruity_twentythree/views/subviews/navigation/navigator.twig
  themes/survey/vanilla/views/subviews/header/nav_bar.twig
  themes/survey/vanilla/views/subviews/messages/warnings.twig
  themes/survey/vanilla/views/subviews/navigation/navigator.twig
Labels: Tested OK

#3630 Fixes issue #19254: With debug=2 going to Email Templates from Survey…
  application/controllers/admin/EmailTemplates.php
Labels: Tested OK, Code review done
