Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-02, with the labels that each got.

#2863 Fixed issue #18579: Question theme are not shown in Survey Logic file
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done

#2860 Fixed issue #18555: Wrong escaping in Mandatory setting help
  application/extensions/GeneralOptionWidget/settings/MandatoryGeneralOption.php
Labels: Tested OK, Code review done

#2859 Fixed issue #18572: The 'duration' type field has an invalid value for 'name'
  application/views/themeOptions/options_core.php
Labels: Tested OK, Code review done

#2750 Fixed issue [security] #18514 : no CSRF control when delete token table
  application/controllers/admin/Tokens.php
  application/views/admin/token/afterDeleteParticipantsTable.php
  application/views/admin/token/deleteParticipantsTable.php
Labels: Needs testing, Code review done

#2869 Fixed issue #18428: Image select QuestionTheme settings are shown on Core theme settings
  application/views/survey/questions/answer/listradio/config.xml
Labels: Tested OK, Code review done, minor impact

#2894 Fixed issue #18625: Cannot copy a survey when using a survey alias
  application/helpers/admin/import_helper.php
Labels: Tested OK, Code review done

#2889 Fixed issue #17486: Current Page Values not saved if saving pressing Enter
  application/helpers/SurveyRuntimeHelper.php
Labels: Needs testing, Code review done

#2855 Fixed issue #18599: Placeholders {GID} and {SGQ} not replaced for "script"
  application/models/QuestionBaseRenderer.php
Labels: Tested OK, Code review done, minor impact

#2881 Fixed issue #18587: Question type button not visible after having chosen the type
  themes/admin/Apple_Blossom/css/lime-admin-colors.css
  themes/admin/Bay_of_Many/css/lime-admin-colors.css
  themes/admin/Black_Pearl/css/lime-admin-colors.css
  themes/admin/Dark_Sky/css/lime-admin-colors.css
  themes/admin/Free_Magenta/css/lime-admin-colors.css
  themes/admin/Noto_All_Languages/css/lime-admin-colors.css
  themes/admin/Purple_Tentacle/css/lime-admin-colors.css
  themes/admin/Sea_Green/css/lime-admin-colors.css
Labels: Tested OK, Code review done

#2870 Fixed issue #18521: checkbox issue in the permission modal
  assets/packages/usermanagement/js/usermanagement.js
Labels: Tested OK, Code review done, JavaScript, minor impact

#2862 Fixed issue #18590: Filenames containing an apostrophe (') cause uploaded file-list to unlist upon Resume later or Next then Previous
  application/views/survey/questions/answer/file_upload/answer.twig
Labels: Tested OK, Code review done

#2799 Fixed issue #18559: Potential 500 error with LimeMailer and PHP8
  application/core/LimeMailer.php
Labels: Tested OK, Code review done, Hard to Test

#2916 DEV: Update GitHub actions to make screenshots available
  .github/workflows/main.yml
Labels: Needs code review

#2830 Fixed issue #18577: Update Moment.js
  vendor/moment/moment-with-locales.js
  vendor/moment/moment-with-locales.min.js
Labels: Needs testing

#2914 Fixed Issue #18581: Blocking users after X failed attempts counts incorrectly (off by 1)
  application/models/FailedLoginAttempt.php
  tests/unit/models/FailedLoginAttemptTest.php
Labels: Tested OK, Code review done, Has auto test

#2893 Fixed Issue #18438: Fixed Show popups, wrong text in inherit-button
  application/views/themeOptions/options_core.php
Labels: Tested OK, Code review done

#2892 Fixed Issue #18548: Quick add function "Code ; Title" doesn't work.
  application/views/questionAdministration/modals.twig
Labels: Tested OK, Code review done

#2676 Fixed issue #18407: On-page conditions not working when pre-filling q…
  application/helpers/expressions/em_core_helper.php
Labels: Needs testing, Code review done

#2890 Fixed issue #18619: QuestionGroup->getGroupDescription() fails
  application/models/QuestionGroup.php
  tests/data/surveys/limesurvey_survey_594264_getGroupDescription.lss
  tests/unit/models/QuestionGroupTest.php
Labels: Code review done, Has auto test

#2788 Fixed issue #18220: Question image theme don't seems to work
  application/config/internal.php
  application/helpers/sanitize_helper.php
  tests/unit/helpers/CheckAbsoluteUrlTest.php
  themes/question/image_select-listradio/survey/questions/answer/listradio/answer.twig
  themes/question/image_select-listradio/survey/questions/answer/listradio/assets/css/imageselect.css
  themes/question/image_select-listradio/survey/questions/answer/listradio/assets/scripts/imageselect.js
  themes/question/image_select-listradio/survey/questions/answer/listradio/columns/column_footer.php
  themes/question/image_select-listradio/survey/questions/answer/listradio/columns/column_footer.twig
  themes/question/image_select-listradio/survey/questions/answer/listradio/columns/column_header.twig
  themes/question/image_select-listradio/survey/questions/answer/listradio/config.xml
  themes/question/image_select-listradio/survey/questions/answer/listradio/rows/answer_row.twig
  themes/question/image_select-listradio/survey/questions/answer/listradio/rows/answer_row_noanswer.twig
  themes/question/image_select-listradio/survey/questions/answer/listradio/rows/answer_row_other.twig
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/answer.twig
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/assets/css/imageselect.css
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/assets/scripts/imageselect.js
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/columns/column_footer.twig
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/columns/column_header.twig
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/config.xml
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/rows/answer_row.twig
  themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/rows/answer_row_other.twig
Labels: Needs code review, Needs testing

#2755 Fixed issue #18532: Data entry screen incorrectly assigns 0 value to …
  application/controllers/admin/dataentry.php
Labels: Needs testing, Code review done

#2900 Fixed issue #18527: Can't validate phone number usign Regex if phone number starts with +
  vendor/decimal/decimal.js
  vendor/decimal/decimal.min.js
Labels: Needs testing, Code review done

#2907 Feature #18197: Allow GA4 tracking
  themes/survey/vanilla/views/subviews/header/google_analytics.twig
Labels: Needs code review, Needs testing

#2932 Dev #18578: Internal server error (HTTP 500) in RemoteControl get_participant_properties for removed participant
  tests/data/surveys/survey_archive_getParticipantPropertiesTest.lsa
  tests/unit/helpers/remotecontrol/GetParticipantPropertiesTest.php
  tests/unit/helpers/remotecontrol/RemoteControlListParticipantsTest.php
  tests/unit/helpers/remotecontrol/RemoteControlListSurveyGroupsTest.php
  tests/unit/helpers/remotecontrol/RemoteControlTest.php
Labels: Code review done, Has auto test

#2607 Fixed issue #18300: Panel Integration is failing to load
  application/controllers/SurveyAdministrationController.php
  application/models/SurveyURLParameter.php
  application/views/admin/survey/subview/accordion/_integration_panel.php
  application/views/surveyAdministration/addPanelIntegrationParameter_view.php
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.css
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/lib/surveysettings.js
  assets/scripts/admin/surveysettings.js
Labels: Needs code review, Tested OK

#2921 Fixed issue #18407: On-page conditions not working when pre-filling q…
  application/helpers/expressions/em_core_helper.php
Labels: Needs testing, Code review done

#2946 Fixed issue #18655: Data loss if field in response table it missing
  application/helpers/expressions/em_manager_helper.php
  application/models/Response.php
Labels: Tested OK, Code review done

#2952 Fixed issue #18658: Upload file question type
  assets/packages/questions/upload/build/uploadquestion.js
  assets/packages/questions/upload/build/uploadquestion.min.js
  assets/packages/questions/upload/build/uploadquestion.min.js.map
  assets/packages/questions/upload/src/uploader.js
Labels: Tested OK, Code review done
