Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-06, with the labels that each got.

#3135 Fixed issue #17491: Multiple Short Text subquestions missing from Export Printable Survey
  application/controllers/admin/PrintableSurvey.php
Labels: Tested OK, Code review done

#3133 Fixed issue #17491: Multiple Short Text subquestions missing from Export Printable Survey
  application/controllers/admin/PrintableSurvey.php
Labels: Tested OK, Code review done

#3042 Fixed issue #18737: Missing response action: View response as queXML PDF
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#3145 Fixed issue #18720: Script show as updatable for simple user with XSS
  application/views/questionAdministration/textElements.php
  assets/packages/jquery-ace/jquery.ace.js
Labels: Needs testing, Code review done

#3120 Fixed issue #18808: Mandatory soft only works once per survey if over multiple pages/groups
  application/helpers/SurveyRuntimeHelper.php
  tests/data/surveys/limesurvey_survey_MandatorySoftMultiPage.lss
  tests/functional/frontend/MandatorySoftTest.php
Labels: Tested OK, Code review done, Has auto test

#3119 Fixed issue #18808: Mandatory soft only works once per survey if over multiple pages/groups
  application/helpers/SurveyRuntimeHelper.php
  tests/LimeSurveyWebDriver.php
  tests/data/surveys/limesurvey_survey_MandatorySoftMultiPage.lss
  tests/functional/frontend/MandatorySoftTest.php
Labels: Tested OK, Code review done, Has auto test

#3165 Fixed issue #18814: Array question statistics fail for Remote Control.
  application/helpers/common_helper.php
  tests/data/surveys/survey_statistics_three.lsa
  tests/unit/helpers/remotecontrol/ExportStatisticsArrayQuestionsTest.php
Labels: Code review done, Has auto test

#3168 Fixed issue #18459: When filtering the survey list by a parent survey group, surveys assigned to a child survey group are not listed
  application/models/Survey.php
Labels: Tested OK, Code review done

#3004 Fixed issue #18669: XSS simple admin via Google key
  application/models/Survey.php
Labels: Tested OK, Code review done

#3193 Fixed issue #18585: Click again on link by email submit again the survey
  application/controllers/survey/index.php
Labels: Tested OK, Code review done

#3192 Fixed issue #18852: Gender question repopulation
  application/views/survey/questions/answer/gender/buttons/answer.twig
Labels: Tested OK, Code review done

#3178 Fixed issue #18725: Reorder questions/question groups can break survey (Tests)
  application/controllers/SurveyAdministrationController.php
  application/models/services/GroupHelper.php
  tests/TestBaseClass.php
  tests/bootstrap.php
  tests/data/surveys/survey_fixMovedQuestionConditionsDefault.lss
  tests/data/surveys/survey_fixMovedQuestionConditionsNew.lss
  tests/data/surveys/survey_groupHelper_test.lss
  tests/unit/helpers/FixMovedQuestionConditionsTest.php
  tests/unit/helpers/GenerateSimpleStatisticsTest.php
  tests/unit/helpers/GroupHelperTest.php
  tests/unit/helpers/remotecontrol/RemoteControlQuestionPropertiesTest.php
Labels: Code review done, Has auto test

#3206 Fixed issue #18833: mobile phone issue with formulas on columns headings with array numbers on checkbox layout
  application/views/survey/questions/answer/arrays/multiflexi/rows/cells/answer_td_checkboxes.twig
Labels: Tested OK, Code review done, minor impact

#3207 Fixed issue #18833: mobile phone issue with formulas on columns headings with array numbers on checkbox layout
  application/views/survey/questions/answer/arrays/multiflexi/rows/cells/answer_td_checkboxes.twig
Labels: Tested OK, Code review done

#3152 Fixed issue #16409: Emoticon style is different if emoticon is chosen
  assets/packages/questions/5pointchoice/scripts/slider-rating.js
Labels: Tested OK, Code review done

#3189 cleared old bs switch files
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/admin/dataentry/vvimport.php
  application/views/admin/export/exportresults_view.php
  application/views/admin/export/statistics_view.php
  application/views/admin/globalsettings/globalSettings_view.php
  application/views/admin/globalsettings/surveySettings.php
  application/views/admin/participants/modal_subviews/_editAttribute.php
  application/views/admin/participants/modal_subviews/_editParticipant.php
  application/views/admin/participants/participantsPanel_view.php
  application/views/admin/survey/queXMLSurvey_view.php
  application/views/admin/surveysgroups/surveySettings.php
  application/views/admin/token/csvupload.php
  application/views/admin/token/exportdialog.php
  application/views/admin/token/invite.php
  application/views/admin/token/managetokenattributes.php
  application/views/admin/token/massive_actions/_update.php
  application/views/admin/token/remind.php
  application/views/admin/token/tokenform.php
  application/views/surveyAdministration/editLocalSettings_main_view.php
  assets/admin_themes/adminbasics_temporary/000-lime-admin-common.scss
  assets/packages/adminbasics/src/parts/globalMethods.js
  modules/admin/globalsettings/views/globalSettings_view.php
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Needs testing, Code review done

#3214 Fixed issue #18401: Unable to use checkdate function if debug set
  application/helpers/expressions/em_core_helper.php
  tests/unit/helpers/CheckDateWrapTest.php
Labels: Code review done, Has auto test

#3157 Fixed issue #18731: Edit a question "script" tab has disappeared
  application/controllers/QuestionAdministrationController.php
  application/core/LsDefaultDataSets.php
  application/models/SettingsUser.php
Labels: Tested OK, Code review done

#3109 Fixed issue #18693: Using checkbox question for yes/no loses data when data entry view
  application/controllers/admin/DataEntry.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
  assets/packages/adminbasics/src/parts/save.js
  assets/scripts/admin/dataentry.js
Labels: Tested OK, Code review done

#2404 Fixed issue #17992: unable to reimport tokens from old table
  application/config/version.php
  application/helpers/update/updates/Update_607.php
Labels: Needs testing, Code review done, Major impact

#3167 Fixed issue #18459: When filtering the survey list by a parent survey group, surveys assigned to a child survey group are not listed
  application/models/Survey.php
  tests/unit/models/SurveySearchTest.php
Labels: Tested OK, Code review done, Has auto test

#2700 Fixed issue #18181: "no answer" still shown after turning it off
  application/config/config-defaults.php
  application/controllers/SurveyAdministrationController.php
  application/controllers/admin/Database.php
  application/helpers/qanda_helper.php
Labels: Needs testing, Code review done

#3211 Fixed issue [security] #18866: Label sets can be created by any admin user
  application/controllers/admin/Labels.php
Labels: Tested OK, Code review done

#3205 Fixed issue #18694: Invalid HTML for list radio questions due to missing closing ul element
  application/core/QuestionTypes/ListRadio/RenderListRadio.php
Labels: Tested OK, Code review done

#3018 Fixed issue #18693: Using checkbox question for yes/no loses data when data entry view
  application/controllers/admin/DataEntry.php
  assets/admin_themes/adminbasics_temporary/000-lime-admin-common.scss
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/src/parts/save.js
  assets/scripts/admin/dataentry.js
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#3147 Fixed issue 18459: When filtering the survey list by a parent survey group, surveys assigned to a child survey group are not listed
  application/extensions/admin/survey/ListSurveysWidget/ListSurveysWidget.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3220 Fixed issue #18823: STATA Export fails with certain question types
  tests/unit/helpers/remotecontrol/ExportResponsesStataXmlTest.php
Labels: Code review done, Has auto test

#3218 Fixed issue #18793: Quick Translation crash with MS SQL Database Error
  application/models/services/QuickTranslation.php
Labels: Needs testing, Code review done

#3224 Fixed issue #18793: Quick Translation crash with MS SQL Database Error
  application/models/services/QuickTranslation.php
Labels: Needs testing, Code review done

#3144 Fixed issue #18818: dump when using getQuestions API
  application/libraries/PluginManager/LimesurveyApi.php
  tests/data/surveys/survey_GetQuestionTest.lss
  tests/unit/plugins/LimesurveyApi/GetQuestionsTest.php
Labels: Discussion ongoing, Code review done, minor impact

#3215 Fixed issue #18871: Can't add email attachment in email templates
  application/views/admin/emailtemplates/email_language_template_tab.php
  assets/packages/emailtemplates/emailtemplates.js
Labels: Tested OK, Code review done

#3212 Fixed issue [security] #18866: Label sets can be created by any admin user
  application/controllers/admin/Labels.php
Labels: Needs code review, Tested OK

#3210 Fixed issue [security] #18866: Label sets can be replaced by any admin user
  application/controllers/admin/labels.php
Labels: Needs code review, Tested OK

#3111 Fixed issue #18798: Out-of-memory problem in statistics export
  application/helpers/admin/statistics_helper.php
Labels: Needs testing, Code review done

#3204 Fixed issue #18706: Cannot use expression in End url description
  application/helpers/SurveyRuntimeHelper.php
Labels: Tested OK, Code review done

#3231 Fixed issue #18798: Out-of-memory problem in statistics export
  application/helpers/admin/statistics_helper.php
Labels: Needs code review, Needs testing

#3243 Fixed issue #18885: CSRF Leading to reset Boxes
  application/controllers/HomepageSettingsController.php
  application/views/homepageSettings/index.php
  application/views/layouts/fullpagebar_view.php
  assets/scripts/admin/homepagesettings.js
Labels: Tested OK, Code review done

#3239 Fixed issue #18885: CSRF Leading to reset Boxes
  application/controllers/HomepageSettingsController.php
  application/views/homepageSettings/index.php
  application/views/homepageSettings/partial/topbarBtns/rightSideButtons.php
  assets/scripts/admin/homepagesettings.js
Labels: Tested OK, Code review done

#3228 Fixed issue 18821: Public url is not used for SURVEYURL
  application/core/LSYii_Application.php
  application/core/LSYii_Controller.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3229 Fixed issue 18821: Public url is not used for SURVEYURL
  application/core/LSYii_Application.php
  application/core/LSYii_Controller.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3241 Bug/18884 fix stored xss in surveygroup
  application/controllers/admin/SurveysGroupsController.php
  application/core/LSYii_Validators.php
  application/extensions/admin/grid/CLSGridView.php
  application/extensions/admin/grid/assets/rowLink.js
  application/extensions/admin/survey/ListSurveysWidget/views/listSurveys.php
  application/models/SurveysGroups.php
  application/views/surveyAdministration/listSurveys_view.php
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/src/adminbasicsmain.js
  assets/packages/adminbasics/src/pages/surveyGrid.js
Labels: Tested OK, Code review done

#2625 Fixed issue #18356: User with only user update allowed can set/remove any role to any user
  application/controllers/UserManagementController.php
  application/models/User.php
  application/models/services/UserManager.php
  application/views/userManagement/partial/addrole.php
  application/views/userManagement/partial/editpermissions.php
Labels: Tested OK, Code review done

#3232 Fixed issue #18630: Survey list showing wrong icon for surveys.
  application/models/Survey.php
  tests/unit/models/SurveyTest.php
Labels: Tested OK, Has auto test
