Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-03, with the labels that each got.

#2953 Fixed issue #18662: Update DB from 491 break on home page
  application/models/SurveyLanguageSetting.php
Labels: Needs testing, Code review done

#2963 CT-41: Response editor value defaults to empty space
  application/controllers/admin/DataEntry.php
Labels: Tested OK, Code review done

#2934 Fixed issue #18644: YII_DEBUG was not used inside KCFinder
  index.php
  setdebug.php
  vendor/kcfinder/core/bootstrap.php
Labels: Tested OK, Code review done

#2950 fix tooltip wrong position issue
  assets/admin_themes/Sea_Green/admin_customizations.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#2941 Fixed issue #18476: CPDB - Add attribute modal - delete language does not work
  application/views/admin/participants/modal_subviews/_editAttribute.php
  application/views/admin/participants/participantsPanel_view.php
Labels: Tested OK, Code review done

#2813 Fixed issue #18336: Placeholder fields VALIDFROM and VALIDUNTIL not listed at email templates
  application/controllers/LimereplacementfieldsController.php
Labels: Tested OK, Code review done

#2379 Dev #18040: Add buttons submit the whole labelset instead of only add…
  application/controllers/admin/Labels.php
  application/helpers/admin/label_helper.php
  application/models/LabelSet.php
  application/views/admin/labels/_labelviewtabcontent_view.php
  application/views/admin/labels/labelRow.twig
  application/views/admin/labels/labelview_view.php
  assets/scripts/admin/labels.js
Labels: Needs update by author, Needs code review, Tested OK

#2848 Fixed Issue #18370: Password suggestions sometimes doens't match rules
  application/core/plugins/PasswordRequirement/PasswordRequirement.php
  tests/TestBaseClass.php
  tests/unit/plugins/PassordRequirementTest.php
Labels: Needs update by author, Tested OK, Code review done

#2962 Feature #18197: Allow GA4 tracking
  themes/survey/vanilla/views/subviews/header/google_analytics.twig
Labels: Tested OK, Code review done

#2905 Fixed Issue #18620: Column relevance disabling not working as expected
  application/views/questionAdministration/subquestionRow.twig
  application/views/questionAdministration/subquestions.twig
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
Labels: Tested OK, Code review done, minor impact

#2942 Fixed issue #18318: Empty line at the end of csv export
  application/helpers/admin/export/CsvWriter.php
Labels: Tested OK, Code review done

#2972 Fixed issue #18071: Import question
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/limesurvey_question_import_question_test.lsq
  tests/data/surveys/limesurvey_question_import_question_test_II.lsq
  tests/data/surveys/limesurvey_survey_import_question_test.lss
  tests/unit/helpers/RemoteControlImportQuestionTest.php
Labels: Tested OK, Code review done, Has auto test

#2968 Fixed issue #18653: getSuperAdmin return simple user
  application/models/User.php
  tests/unit/models/UserTest.php
Labels: Tested OK, Code review done, Has auto test

#2948 Fixed issue #18657: Encrypted token attributes are shown encrypted when piped into a question body
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done

#2899 Fixed issue #18504: Date Calendar Selection Question
  application/core/QuestionTypes/Date/RenderDate.php
  assets/scripts/date.js
Labels: Tested OK, Code review done

#2998 Fixed issue #18655: Data loss if field in response table it missing.
  .github/workflows/main.yml
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/survey_export_responses_with_tokens.lsa
  tests/unit/helpers/remotecontrol/RemoteControlExportResponsesTest.php
  tests/unit/helpers/remotecontrol/RemoteControlTest.php
  tests/unit/models/QuestionGroupTest.php
Labels: Code review done, Has auto test

#2956 Fixed issue #18655: Data loss if field in response table it missing
  application/helpers/expressions/em_manager_helper.php
  application/models/Response.php
Labels: Needs testing, Code review done

#2983 Fixed issue #18674: Simple user can update javascript with XSS and di…
  application/core/LSYii_NoUpdateValidator.php
  application/core/LSYii_Validators.php
  application/models/QuestionL10n.php
  application/views/questionAdministration/textElements.php
  tests/TestBaseClass.php
  tests/data/surveys/limesurvey_survey_XssAndScriptCheck.lss
  tests/functional/backend/XssAndScriptCheckTest.php
  vendor/jquery-ace/jquery.ace.js
Labels: Needs code review, Needs testing, Has auto test

#3017 Fixed issue #18698: Vulnerable javascript dependency used in adminsidepanel.js in limesurvey/limesurvey
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.css
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/css/adminsidepanel.css
  assets/packages/adminsidepanel/build/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/package.json
  assets/packages/adminsidepanel/yarn.lock
Labels: Needs testing, Code review done

#2465 Fixed issue #18180: Calling set_participant_properties with an invalid token id throws an internal server error
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/limesurvey_survey_get_participant_properties.lsa
  tests/unit/helpers/remotecontrol/EncryptedCoreParticipantPropertiesTest.php
  tests/unit/helpers/remotecontrol/GetParticipantPropertiesTest.php
Labels: Code review done, Technical, Has auto test

#2753 Fixed issue #18381: PluginSetting type date must be saved as a common datetime string
  .gitignore
  application/extensions/SettingsWidget/SettingsWidget.php
  application/libraries/PluginManager/LimesurveyApi.php
  application/libraries/PluginManager/PluginBase.php
  plugins/Demo/DemoDateSetting/DemoDateSetting.php
  plugins/Demo/DemoDateSetting/LICENSE
  plugins/Demo/DemoDateSetting/config.xml
  tests/data/plugins/SettingsPlugin.php
  tests/functional/backend/SettingsPluginTest.php
Labels: Code review done, Has auto test
