Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-08, with the labels that each got.

#3304 Fixed issue [security] #18979: User can put survey in surveygroup without access permission
  application/controllers/admin/Database.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3323 Fixed issue #19001: participant list won't show since update 230731 - version 5.6.32
  application/models/TokenDynamic.php
Labels: Tested OK, Code review done

#3306 Fixed issue #18936: User count in group is not OK after deleting a user
  application/controllers/UserManagementController.php
  application/datavalueobjects/OperationResult.php
  application/datavalueobjects/TypedMessage.php
  application/models/services/UserManager.php
Labels: Tested OK, Code review done

#3312 Fixed issue #18832: Participants can't re-enter a submitted survey if setting is using "inherit" at participant settings
  application/helpers/expressions/em_manager_helper.php
  application/models/TokenDynamic.php
  tests/functional/backend/NoGreenBarTest.php
  tests/unit/models/TokenDynamicTest.php
Labels: Tested OK, Code review done

#3342 MW-458: ls cli command
  application/commands/ImportSurveyCommand.php
Labels: Tested OK

#3311 Fixed issue #18949: Responses filters are case sensitive
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#3339 Fixed issue #18949: Responses filters are case sensitive
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#3003 Fixed issue #18610: Email attachments expose absolute path when exporting LSS
  application/helpers/admin/import_helper.php
  application/helpers/common_helper.php
  application/helpers/export_helper.php
  application/models/SurveyLanguageSetting.php
Labels: Tested OK, Code review done

#3333 Fixed issue #19000 Privacy policy view is not rendered per tab, it is stacked below each other in the same view.
  application/views/admin/survey/editDataSecurityLocalSettings_view.php
Labels: Tested OK, Code review done

#3297 Fixed issue #18958: Multiple numerical input text input box width not having an effect (alternative)
  application/models/QuestionBaseRenderer.php
Labels: Tested OK, Code review done

#3183 Fixed issue #18856 - buildXMLFromQuery fails to implement LIMIT and can end…
  application/helpers/export_helper.php
Labels: Needs testing, Code review done

#3060 Fixed issue #18315 Uses left value goes to negative
  application/views/admin/survey/subview/accordion/_tokens_panel.php
Labels: Tested OK, Code review done

#3307 Fixed issue [security] #18977: Improper Authorization in add role function leads to privilege escalation
  application/controllers/UserManagementController.php
Labels: Needs testing, Code review done

#3308 Fixed issue [security] #18977: Improper Authorization in add role fun…
  application/controllers/UserManagementController.php
Labels: Needs testing, Code review done

#3278 New feature: Export responses by multiple tokens
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/survey_export_responses_by_token_955579.lsa
  tests/unit/helpers/remotecontrol/RemoteControlExportResponsesByTokenTest.php
Labels: Needs code review, Needs testing

#3369 Fixed issue #19003: XSS Reflected via import file function
  application/views/admin/participants/uploadSummary_view.php
Labels: Tested OK, Code review done

#3346 CR-1285: User should be able to reorder questions within a group of an activated survey
  application/controllers/QuestionGroupsAdministrationController.php
  application/views/questionAdministration/listquestions.php
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/package.json
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
  assets/packages/adminsidepanel/yarn.lock
Labels: Tested OK, Code review done

#3327 Fixed issue #18904: Stored XSS with Expression Script in End page
  application/helpers/SurveyRuntimeHelper.php
Labels: Tested OK, Code review done

#3394 Fixed issue #19036: Stored XSS via user's Username
  application/views/userManagement/partial/addedituser.php
Labels: Needs code review, Needs testing

#3362 CR-925: Inherited options do not match value inherited
  application/config/version.php
  application/core/LsDefaultDataSets.php
  application/helpers/update/updates/Update_614.php
  themes/survey/bootswatch/config.xml
  themes/survey/fruity/config.xml
  themes/survey/vanilla/config.xml
Labels: Needs testing, Code review done

#3392 Fixed issue #18610: Email attachments expose absolute path when exporting LSS
  application/helpers/admin/import_helper.php
  application/helpers/common_helper.php
  application/helpers/export_helper.php
  application/models/SurveyLanguageSetting.php
Labels: Tested OK, Code review done

#3395 Fixed bug #19002: Unauthorized access to Survey menu entries
  application/controllers/admin/SurveymenuController.php
Labels: Needs code review, Code review done

#3385 DEV CR-1275: Password length 12 characters bring down to 8
  application/core/plugins/PasswordRequirement/PasswordRequirement.php
Labels: Tested OK, Code review done

#3403 Fixed issue #18557: Email Template Attachments appear to carry over with copied survey, but do not work
  application/helpers/admin/import_helper.php
  application/helpers/common_helper.php
  tests/unit/helpers/TranslateLinksTest.php
Labels: Tested OK, Code review done

#3373 Fixed bug #18911 import of theme fails if it contains resource with uppercase extension
  application/helpers/admin/template_helper.php
Labels: Needs code review, Tested OK

#3413 DEV CR-1274: Add user: Set expiration date by default 1Y in the future.
  assets/packages/usermanagement/js/usermanagement.js
Labels: Tested OK, Code review done

#3404 Fixed issue #19027: Editing a selected survey from the survey list does not work after performing table action like pagination
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/extensions/admin/survey/ListSurveysWidget/views/listSurveys.php
Labels: Tested OK, Code review done

#3417 Fixed bug #18911 import of theme fails if it contains resource with uppercase extension
  application/helpers/admin/template_helper.php
Labels: Needs testing, Code review done

#3378 Fixed issue #18905: Create automatic test for XSS Purifier: Broken HTML
  tests/unit/LSYiiValidatorsTest.php
Labels: Code review done, Has auto test

#3410 Fixed issue #18905: Create automatic test for XSS Purifier: Broken HTML
  tests/unit/LSYiiValidatorsTest.php
Labels: Code review done, Has auto test
