Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-04, with the labels that each got.

#3025 Fixed issue #18679 API Access to Question Type Array Dual Scale merge scales if answer code is not unique.
  application/helpers/remotecontrol/remotecontrol_handle.php
  application/models/Question.php
  tests/data/surveys/survey-dual-scale-question-api-test.lss
  tests/unit/helpers/remotecontrol/RemoteControlQuestionPropertiesTest.php
Labels: Needs testing, Code review done, Has auto test

#2464 Fixed issue #18184: cpd_importParticipants with encryption turned on, fails to save the participant encrypted in CPDB, causing 500 error to CPDB
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/unit/helpers/remotecontrol/CPDImportParticpantsTest.php
Labels: Code review done, Technical, Has auto test

#2825 Fixed issue #18324: mandSoft POST parameter may be passed to bypass mandatory questions
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/expressions/em_manager_helper.php
  tests/data/surveys/limesurvey_survey_MandatorySoftBrokeMandatory.lss
  tests/functional/frontend/MandatorySoftTest.php
Labels: Needs testing, Code review done, Has auto test

#3008 DEV #18099: Automatic testing for navigation buttons.
  tests/data/surveys/survey_index_navigation_test.lss
  tests/functional/frontend/SurveyIndexNavigationTest.php
Labels: Needs code review, Has auto test

#2688 Fixed issue #18423: SQL error when quota enabled on postgresql
  application/helpers/frontend_helper.php
Labels: Tested OK, Code review done, minor impact

#3046 Fixed issue #18684: missing translation
  application/commands/XmlTranslationCommand.php
Labels: Needs code review, Needs testing

#3051 Dev: improve the response time of gh action
  .github/workflows/main.yml
Labels: Needs code review, Needs testing

#3001 Fixed issue #18633: Inherited value doesn't match any attribute option
  application/views/themeOptions/options_core.php
Labels: Tested OK, Code review done

#3028 Fixed issue #17883: QueXML formatting cannot be changed (master)
  application/controllers/PrintanswersController.php
  application/controllers/ResponsesController.php
  application/controllers/admin/Export.php
  application/libraries/admin/quexmlpdf.php
  application/views/admin/survey/queXMLSurvey_view.php
Labels: Tested OK, Code review done

#2692 Fixed issue #14108: No error proper error message when LDAP login fails due to case-sensitivity
  application/core/plugins/AuthLDAP/AuthLDAP.php
Labels: Needs code review, Needs testing

#3056 Fixed issue #18191: Cannot use statCount in specific condition
  application/core/plugins/statFunctions/config.xml
  application/core/plugins/statFunctions/countFunctions.php
  application/libraries/PluginManager/LimesurveyApi.php
Labels: Plugin, Tested OK, Code review done, minor impact, Hard to Test

#3058 Fixed issue #18756: Unable to set non-integer values for initial slider value
  application/views/survey/questions/answer/multiplenumeric/rows/sliders/answer_row.twig
  assets/packages/questions/numeric-slider/scripts/numeric-slider.js
Labels: Needs code review, Tested OK, JavaScript, minor impact

#3057 Fixed issue #18756: Unable to set non-integer values for initial slider value
  application/views/survey/questions/answer/multiplenumeric/rows/sliders/answer_row.twig
  assets/packages/questions/numeric-slider/scripts/numeric-slider.js
Labels: Needs code review, Tested OK, JavaScript, minor impact

#3047 Fixed issue #18739: ComfortUpdate notification not being shown
  application/core/SurveyCommonAction.php
  application/models/UpdateForm.php
Labels: Tested OK, Code review done

#3015 Fixed issue #18703: Upload files show error if not seen (using index)
  application/helpers/expressions/em_manager_helper.php
Labels: Needs testing, Code review done, minor impact

#3053 Fixed issue #18684: Missing translation.
  application/commands/XmlTranslationCommand.php
Labels: Needs testing, Code review done

#3079 Fixed issue #18782: Bad width set for Array dual scale
  application/core/QuestionTypes/ArrayMultiscale/RenderArrayMultiscale.php
Labels: Tested OK, Code review done

#2865 Fixed issue #18604: Set empty to maximum number of files not working
  application/controllers/UploaderController.php
Labels: Tested OK, Code review done

#3083 Fixed issue #18604: Set Minimum number of files for File Upload not working
  application/controllers/UploaderController.php
Labels: Tested OK, Code review done

#3081 Fixed issue #18639: Token browse can be unusable with lot of data in some attribute
  application/config/version.php
  application/extensions/CustomFormatter.php
  application/models/TokenDynamic.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/grid.scss
Labels: Tested OK, Code review done

#2915 Fixed issue #18639: Token browse can be unusable with lot of data in attribute
  application/config/version.php
  application/extensions/CustomFormatter.php
  application/models/TokenDynamic.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/grid.scss
  assets/packages/adminbasics/yarn.lock
Labels: Tested OK, Code review done

#3076 Fixed issue #18771: Superadmin unable to rename theme
  application/controllers/admin/Themes.php
Labels: Tested OK, Code review done

#3073 Fixed issue #18678: missing translation in bread crumbs.
  application/controllers/SurveyAdministrationController.php
Labels: Tested OK, Code review done
