Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-10, with the labels that each got.

#2581 Fixed issue #18294: User was not added to group created automatically
  application/controllers/UserGroupController.php
Labels: Tested OK, Code review done, minor impact

#3504 Fixed issue #18294: User can not see group created and user in group created
  application/helpers/common_helper.php
Labels: Tested OK, Code review done

#3503 Fixed issue #19112: Store XSS at Label sets list
  application/views/admin/labels/labelRow.twig
Labels: Tested OK, Code review done, minor impact

#3457 Fixed issue #18817: Editing a question deletes default answers
  application/controllers/QuestionAdministrationController.php
  application/models/Question.php
Labels: Tested OK, Code review done

#3506 Fixed issue #19126: Incorrect Authorization check in add User role
  application/controllers/UserManagementController.php
  application/models/User.php
  application/models/services/UserManager.php
  tests/unit/models/UserManagerServiceTest.php
Labels: Tested OK, Code review done

#3509 Fixed issue [security] #19134: User with "Users" permission only can add arbitrary users to the not owned user group
  application/controllers/UserManagementController.php
  application/views/userManagement/massiveAction/_addtousergroup.php
Labels: Tested OK, Code review done

#3433 New feature #18880: New imagefile option type for theme options
  application/models/TemplateConfiguration.php
  application/views/themeOptions/options_core.php
Labels: Tested OK, Code review done

#3479 Fixed issue #18957: Ranking Advanced: Visualization Types are not working
  themes/question/ranking_advanced/survey/questions/answer/ranking/answer.twig
  themes/question/ranking_advanced/survey/questions/answer/ranking/config.xml
  themes/question/ranking_advanced/views/bubbles.twig
Labels: Tested OK, Code review done

#3510 Fixed issue #18439: Link set when create user are unusuable in text view
  application/core/LimeMailer.php
Labels: Tested OK, Code review done

#3493 Fixed issue [security] #19106: Deleted account still has permissions
  application/core/ConsoleApplication.php
  application/core/LSYii_Application.php
  application/core/Traits/LSApplicationTrait.php
  application/models/Permission.php
  application/models/Survey.php
  application/models/SurveysGroups.php
  application/models/User.php
Labels: Tested OK, Code review done

#3487 Fixed issue [security] #19106: Deleted account still has permissions
  application/core/ConsoleApplication.php
  application/core/LSYii_Application.php
  application/core/Traits/LSApplicationTrait.php
  application/models/Permission.php
  application/models/Survey.php
  application/models/SurveysGroups.php
  application/models/User.php
Labels: Tested OK, Code review done

#3423 Fixed issue #19038: Privilege escalation bug to creation survey-group with others group as parent
  application/controllers/admin/SurveysGroupsController.php
  application/models/SurveysGroups.php
  application/models/services/SurveysGroupCreator.php
Labels: Tested OK, Code review done

#3517 Fixed issue #19142: CSRF in Save Box Settings
  application/controllers/HomepageSettingsController.php
  assets/scripts/admin/homepagesettings.js
Labels: Tested OK, Code review done

#3482 Fixed issue #18339: Need Way to Modify Question Props in question_l10ns
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/unit/helpers/remotecontrol/QuestionPropertiesTest.php
Labels: Tested OK, Code review done, Has auto test

#3505 Fixed issue [security] #19146: Store XSS when editing label set
  application/models/LabelSet.php
  application/views/admin/labels/exportmulti_view.php
Labels: Tested OK, Code review done

#3507 Fixed issue #19126: Incorrect Authorization check in add User role
  application/controllers/UserManagementController.php
  application/models/User.php
  application/models/services/UserManager.php
  tests/unit/models/UserManagerServiceTest.php
Labels: Tested OK, Code review done

#3414 Dev: Generate simple statistics test.
  tests/data/surveys/survey_simple_statistics.lsa
  tests/unit/helpers/GenerateSimpleStatisticsTest.php
  tests/unit/helpers/remotecontrol/RemoteControlQuestionPropertiesTest.php
Labels: Needs code review, Has auto test

#3522 Fixed issue #18776: Question ordering not correct
  application/models/services/GroupHelper.php
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
Labels: Tested OK, Code review done

#3529 Fixed issue #18648: Unable to upload a file with theme animations enabled
  themes/survey/fruity/views/subviews/header/custom_header.twig
Labels: Tested OK, Code review done

#3528 Fixed issue #18968: User with "View/read Users" permission needs to have "User details" action available for all users, not just itself
  application/models/User.php
Labels: Tested OK, Code review done

#3534 Fixed issue #18776: Question ordering not correct
  application/controllers/SurveyAdministrationController.php
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
Labels: Tested OK, Code review done

#3519 Fixed issue #19094: Input Validation Vulnerability Leading to 500 on responses page
  application/helpers/expressions/em_manager_helper.php
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#3520 Fixed issue #19094: Input Validation Vulnerability Leading to 500 on responses page
  application/helpers/common_helper.php
  application/helpers/expressions/em_manager_helper.php
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#3466 Fixed issue #19094: Input Validation Vulnerability Leading to 500 on responses page
  application/helpers/expressions/em_manager_helper.php
  application/models/SurveyDynamic.php
Labels: Tested OK, Code review done

#3524 Fixed issue #19117: Account past their expiration date can be still active
  application/controllers/admin/Authentication.php
  application/core/LSWebUser.php
  application/core/Traits/LSApplicationTrait.php
  application/models/User.php
Labels: Tested OK, Code review done

#3546 Bug/19160 v5 subquestion save
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK

#3539 Qe 356 rest api json error handlers
  application/core/LSHttpRequest.php
  application/core/LSYii_Application.php
  application/libraries/Yii/Application/AppErrorHandler.php
Labels: Tested OK

#3542 Fixed issue #19114: Admin with Settings & Plugins permission only can store XSS in Survey menus
  application/models/SurveymenuEntries.php
Labels: Tested OK, Code review done

#3535 Fixed issue #19170: Inserting a subquestion/answer option creates multiple rows
  assets/scripts/admin/questionEditor.js
Labels: Tested OK, Code review done

#3551 Fixed issue #19180: SMTP settings are not enabled when SMTP is selected in global settings
  assets/scripts/admin/globalsettings.js
Labels: Needs testing, Code review done

#3536 Fixed issue #19170: Inserting a subquestion/answer option creates multiple rows
  assets/scripts/admin/questionEditor.js
Labels: Tested OK, Code review done

#3556 Fixed issue #19161: invalid adminemail/bounce_email address in lss results in white screen on import
  application/core/LSYii_EmailIDNAValidator.php
  application/core/LSYii_FilterValidator.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3495 Fixed issue [security] #19107: Superadmin can update any admin's information
  application/controllers/UserManagementController.php
  application/models/User.php
  application/models/services/UserManager.php
  tests/unit/controllers/UserManagementTest.php
Labels: Tested OK, Code review done

#3500 Fixed issue #19101: Array by Column Has Incorrect Table Row/Column Ids
  application/helpers/qanda_helper.php
  application/views/survey/questions/answer/arrays/column/answer.twig
Labels: Tested OK, Code review done

#3565 Fixed issue #19163: Reflected XSS in HtmlEditorPop - Bypassing XSS sanitization function
  application/controllers/admin/HtmlEditorPop.php
Labels: Tested OK, Code review done

#3563 Fixed issue #19181: Array[Number] statistics infinite loop when step …
  application/controllers/admin/DataEntry.php
  application/helpers/admin/statistics_helper.php
  application/helpers/export_helper.php
  application/helpers/qanda_helper.php
  application/helpers/userstatistics_helper.php
  application/views/admin/export/statistics_subviews/_question.php
  application/views/survey/questions/answer/arrays/multiflexi/config.xml
Labels: Tested OK, Code review done

#3548 Fixed issue #19177: no able to change admin theme
  application/views/themeOptions/index.php
Labels: Tested OK, Code review done

#3515 Fixed issue #19132: Icon selection in the "Dashboard editor/create box" does not work
  assets/scripts/admin/homepagesettings.js
Labels: Tested OK, Code review done

#3560 Fixed issue #19183: No editing possible after setting the survey background
  application/views/themeOptions/options_core.php
Labels: Tested OK, Code review done

#3559 Fixed issue #19183: No editing possible after setting the survey background
  application/views/themeOptions/options_core.php
Labels: Tested OK, Code review done

#3561 Fixed issue #19085: Theme Options with an on/off switch are not disabled when page loads
  assets/packages/themeoptions-core/themeoptions-core.js
Labels: Tested OK, Code review done

#3570 Fixed issue [security] #19107: Superadmin can update any admin's information
  application/controllers/UserManagementController.php
  application/models/User.php
  application/models/services/UserManager.php
  tests/unit/controllers/UserManagementTest.php
Labels: Tested OK, Code review done, Has auto test

#3571 Fixed issue #18436: RC API : Inviting members with invalid language s…
  application/helpers/admin/token_helper.php
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/TestBaseClass.php
  tests/data/plugins/DummyMailer.php
  tests/unit/helpers/remotecontrol/InviteParticipantsTest.php
Labels: Tested OK, Code review done, Has auto test

#3577 Fixed bug #19165: CSRF edit Blacklist settings (YES to NO)
  application/controllers/admin/ParticipantsAction.php
Labels: Tested OK, Code review done

#3575 Fixed bug #19165: CSRF edit Blacklist settings (YES to NO)
  application/controllers/admin/ParticipantsAction.php
Labels: Tested OK, Code review done

#3513 Fixed issue #19093: Improper Authorization in Import Question function
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK, Code review done

#3530 Fixed issue #19093: Improper Authorization in Import Question function
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK, Code review done

#3568 Fixed issue #19057: incorrect handling of wrong input in create dummy participant form
  application/controllers/admin/Tokens.php
  application/views/admin/token/dummytokenform.php
Labels: Tested OK, Code review done

#3547 Fixed issue [security] #19169: Privilege escalation to edit survey
  application/controllers/SurveyAdministrationController.php
Labels: Tested OK, Code review done

#3567 Fixed issue #19057: incorrect handling of wrong input in create dummy participant form
  application/controllers/admin/Tokens.php
  application/views/admin/token/dummytokenform.php
Labels: Tested OK, Code review done

#3578 Fixed issue [security] #19169: Privilege escalation to edit survey
  application/controllers/SurveyAdministrationController.php
Labels: Tested OK, Code review done

#3525 Fixed issue #19117: Account past their expiration date can be still active
  application/controllers/admin/Authentication.php
  application/core/LSWebUser.php
  application/core/Traits/LSApplicationTrait.php
  application/models/User.php
Labels: Tested OK, Code review done

#3583 Fixed issue #19163: [security] Reflected XSS in HtmlEditorPop - Bypassing XSS sanitization function
  application/controllers/admin/HtmlEditorPop.php
Labels: Tested OK, Code review done
