Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-07, with the labels that each got.

#3222 Fixed issue #18669: XSS simple admin via Google key
  application/helpers/sanitize_helper.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3221 Fixed issue #18669: XSS simple admin via Google key
  application/helpers/sanitize_helper.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3185 Fixed issue #18495: configuration tab is not visible to a user with only create label set permission
  application/config/version.php
  application/controllers/admin/Labels.php
  application/helpers/admin/import_helper.php
  application/helpers/admin/label_helper.php
  application/helpers/update/updates/Update_608.php
  application/helpers/update/updates/Update_609.php
  application/models/Interfaces/PermissionInterface.php
  application/models/LabelSet.php
  application/models/Survey.php
  application/views/admin/labels/_labelviewtabcontent_view.php
  application/views/admin/labels/labelview_view.php
  application/views/admin/super/_configuration_menu.php
  application/views/admin/survey/Question/_subQuestionsAndAnwsersJsVariables.php
  assets/scripts/admin/questionEditor.js
  installer/create-database.php
  tests/functional/backend/LabelSetsCreateUpdate.php
Labels: Needs code review, Needs testing

#3238 Fixed issue #17536: Create automatic test for XSS Purifier
  tests/unit/LSYiiValidatorsTest.php
  tests/unit/models/PermissionTest.php
Labels: Code review done, Has auto test

#3234 Fixed issue #18818: dump when using getQuestions API
  application/libraries/PluginManager/LimesurveyApi.php
  tests/data/surveys/survey_GetQuestionTest.lss
  tests/unit/plugins/LimesurveyApi/GetQuestionsTest.php
Labels: Code review done, Has auto test

#3225 Fixed issue: #18823 STATA Export fails with certain question types.
  tests/unit/helpers/remotecontrol/ExportResponsesStataXmlTest.php
Labels: Code review done, Has auto test

#3271 Fixed issue #18934: Stored XSS in label set administration
  application/helpers/admin/label_helper.php
  application/models/Label.php
  application/views/admin/labels/labelRow.twig
Labels: Tested OK, Code review done

#3268 Fixed issue #18356: [security] User with only user update allowed can set/remove any role to any user
  application/controllers/UserManagementController.php
  application/models/User.php
  application/models/services/UserManager.php
  application/views/userManagement/partial/addrole.php
  application/views/userManagement/partial/editpermissions.php
  tests/unit/models/UserManagerServiceTest.php
Labels: Tested OK, Code review done, Has auto test

#3259 Fixed issue #18356: User with only user update allowed can set/remove any role to any user
  tests/unit/models/UserManagerServiceTest.php
Labels: Code review done, Has auto test

#3240 Fixed issue #18882: Stored XSS in End page
  application/core/LSYii_Validators.php
  tests/unit/LSYiiValidatorsTest.php
Labels: Tested OK, Code review done

#3270 Fixed issue #18928: Stored XSS on Survey "Notification and data function"
  application/views/admin/survey/subview/accordion/_notification_panel.php
Labels: Tested OK, Code review done

#3273 Fixed issue #18932: 404 error after importing responses from a old response table
  application/controllers/admin/DataEntry.php
Labels: Tested OK, Code review done

#3216 Fixed issue #18368: export_statistics from API Yields error
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/unit/helpers/remotecontrol/ExportStatisticsTest.php
Labels: Code review done, Has auto test

#3275 Fixed issue #18837: unable to replace record during reimport of VV files
  application/views/admin/dataentry/vvimport.php
Labels: Needs testing, Tested OK, JavaScript, minor impact

#2565 Fixed issue #18281: Users in group are not deleted
  application/controllers/UserGroupController.php
  application/controllers/UserManagementController.php
  application/models/UserGroup.php
Labels: Tested OK, Code review done

#3244 Fixed issue #18368: export_statistics from API Yields error
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/unit/helpers/remotecontrol/ExportStatisticsTest.php
Labels: Code review done, Has auto test

#3269 Fixed issue #18927: Export user roles without authorization
  application/controllers/UserRoleController.php
Labels: Tested OK, Code review done

#3265 Fixed issue #18929: Cannot edit data notification entries
  application/controllers/FailedEmailController.php
  application/views/layouts/adminmenu.php
  application/views/surveyAdministration/editLocalSettings_main_view.php
  assets/scripts/admin/failedEmail.js
  assets/scripts/admin/text-option-inherit.js
Labels: Needs testing, Code review done

#3282 Fixed issue #18937: Action menu stop work after any action on any user
  application/extensions/admin/grid/CLSGridView.php
  application/extensions/admin/grid/GridActionsWidget/assets/action_dropdown.js
  assets/admin_themes/Sea_Green/tables/tables.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#3283 Fixed issue #18876: Plugin expose full path when an error is reported in the plugin list
  application/models/Plugin.php
Labels: Tested OK, Code review done

#3289 Fixed issue #18573 Insert new box with overlapping position, makes the dashboard to show duplicate boxes
  application/models/Box.php
Labels: Tested OK, Code review done

#3284 Fixed issue #18281: Users in group are not deleted
  application/controllers/UserGroupController.php
  application/controllers/UserManagementController.php
  application/models/UserGroup.php
  application/views/userGroup/usergroups_view.php
Labels: Tested OK, Code review done

#3226 Fixed issue #18694: Invalid HTML for list radio questions due to missing closing ul element
  application/core/QuestionTypes/ListRadio/RenderListRadio.php
Labels: Tested OK, Code review done

#3219 Fixed issue #17992: unable to reimport tokens from old table
  application/config/version.php
  application/helpers/update/updates/Update_498.php
Labels: Tested OK, Code review done

#3291 On PHP 8.2 new DateTime() can not be invoked with null
  application/models/Survey.php
Labels: Tested OK, Code review done

#3286 Fixed issue #18936: User count in group is not OK after deleting a user
  application/controllers/UserManagementController.php
  application/datavalueobjects/OperationResult.php
  application/datavalueobjects/TypedMessage.php
  application/models/services/UserManager.php
Labels: Tested OK, Code review done

#3298 Fixed issue #18573 Insert new box with overlapping position, makes the dashboard to show duplicate boxes
  application/models/Box.php
Labels: Tested OK, Code review done

#3285 Fixed issue #18832: Participants can't re-enter a submitted survey if setting is using "inherit" at participant settings
  application/helpers/expressions/em_manager_helper.php
  application/models/TokenDynamic.php
  tests/functional/backend/NoGreenBarTest.php
Labels: Tested OK, Code review done

#3292 Fixed issue [security] #18967: User can add malicious content in User Roles
  application/models/Permissiontemplates.php
  application/views/userRole/edit.php
  application/views/userRole/partials/_form.php
  application/views/userRole/partials/_view.php
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/src/parts/confirmationModal.js
Labels: Tested OK, Code review done, JavaScript

#3294 Fixed issue [security] #18967: User can import User Roles having permission
  application/controllers/UserRoleController.php
Labels: Tested OK, Code review done

#3296 Fixed issue #18278 Quick translation: "Nothing to translate" appears wrongly.
  application/views/quickTranslation/translatetabs_view.php
Labels: Needs testing, Code review done

#3309 Fixed issue [security] #18985: Reflected XSS
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3310 Fixed issue #18985: shown real import format needed
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3303 Fixed issue [security] #18979: User can put survey in surveygroup without access permission
  application/models/Survey.php
Labels: Tested OK, Code review done

#3288 Fixed issue #18888: General issues with different questions
  themes/question/ranking_advanced/views/blocks.twig
Labels: Tested OK, Code review done
