Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-05, with the labels that each got.

#3049 Fixed issue #18679 API Access to question type array dual scale merge scales if answer code is not unique
  tests/data/surveys/survey-dual-scale-question-api-test.lss
  tests/unit/helpers/remotecontrol/RemoteControlQuestionPropertiesTest.php
Labels: Needs testing, Code review done, Has auto test

#3067 Fixed issue #18456: Interface language parmater use exotic dropdown list.
  application/views/admin/survey/subview/accordion/_generaloptions_panel.php
  application/views/admin/themes/templateeditorbar_view.php
  application/views/surveyPermissions/index.php
Labels: Needs code review, Tested OK

#3075 Fixed issue #18744: Window of User permissions is not adapting to space needed by languages.
  application/models/User.php
  application/views/userManagement/partial/editpermissions.php
Labels: Tested OK, Code review done

#3009 Fixed issue #18612: When surveys are copied without copying resources links are not handled
  application/helpers/admin/import_helper.php
  application/helpers/common_helper.php
  tests/unit/helpers/CheckOldLinksTest.php
Labels: Tested OK, Code review done

#3090 Fixed issue #18635: When you export single response : sometimes goes to a white page
  application/controllers/ResponsesController.php
  application/controllers/admin/Export.php
  application/extensions/admin/grid/MassiveActionsWidget/README.md
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/admin/export/exportresult_panels/_single-value.php
  application/views/admin/export/exportresults_view.php
  application/views/responses/massive_actions/_selector.php
Labels: Tested OK, Code review done

#2923 Fixed issue #18635: Export single response can goes to a white page
  application/controllers/ResponsesController.php
  application/controllers/admin/Export.php
  application/extensions/admin/grid/MassiveActionsWidget/README.md
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/admin/export/exportresult_panels/_single-value.php
  application/views/admin/export/exportresults_view.php
  application/views/responses/massive_actions/_selector.php
Labels: Tested OK, Code review done

#2630 Fixed issue #18343: Problem with interpreting double slash in URL (IIS)
  application/helpers/admin/htmleditor_helper.php
  application/views/admin/htmleditor/pop_editor_view.php
  application/views/admin/survey/prepareEditorScript_view.php
  assets/packages/ckeditor/plugins/limereplacementfields/dialogs/limereplacementfields.js
Labels: Needs testing, Code review done, minor impact

#2909 Fixed issue #18634: Export single selected response can export a empty line
  application/controllers/admin/export.php
  application/controllers/admin/responses.php
  application/extensions/admin/grid/MassiveActionsWidget/README.md
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/admin/export/exportresult_panels/_single-value.php
  application/views/admin/export/exportresults_view.php
  application/views/admin/responses/massive_actions/_selector.php
Labels: Tested OK, Code review done, JavaScript

#3116 replace data-toggle with data-bs-toggle
  application/extensions/AdvancedSettingWidget/views/layout.php
  application/extensions/GeneralOptionWidget/views/layout.php
  application/extensions/GeneralOptionWidget/views/switch.php
  application/extensions/admin/TextDisplaySwitch/views/default.php
  application/extensions/admin/grid/MassiveActionsWidget/README.md
  application/extensions/bootstrap5/helpers/TbHtml.php
  application/extensions/yiiwheels/assets/js/bootstrap-image-gallery.js
  application/extensions/yiiwheels/widgets/daterangepicker/assets/js/daterangepicker.js
  application/extensions/yiiwheels/widgets/formhelpers/assets/js/bootstrap-formhelpers.js
  application/extensions/yiiwheels/widgets/html5editor/assets/js/bootstrap-wysihtml5.js
  application/extensions/yiiwheels/widgets/multiselect/assets/js/bootstrap-multiselect.js
  application/helpers/admin/htmleditor_helper.php
  application/libraries/FormExtension/Inputs/DefaultBaseRenderer.php
  application/libraries/FormExtension/Inputs/GlobalSettingsRenderer.php
  application/models/FailedEmail.php
  application/models/TemplateConfig.php
  application/views/admin/survey/subview/surveydashboard/002-surveytextpanel.twig
  application/views/admin/survey/surveybar_tools.php
  application/views/admin/themes/templateeditor_surveylist_view.php
  application/views/questionAdministration/languageselector.php
  application/views/surveyAdministration/tabImport_view.php
  assets/admin_themes/Sea_Green/buttons/buttons.scss
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/coverage/lcov-report/src/components/bootstrap-sub-submenues.js.html
  assets/packages/adminbasics/coverage/lcov-report/src/parts/globalMethods.js.html
  assets/packages/adminbasics/src/components/bootstrap-sub-submenues.js
  assets/packages/adminsidepanel/src/components/subcomponents/_dropdown.vue
  assets/packages/bootstrap/plugins/datetimepicker/docs/theme/nav.html
  assets/packages/ckeditor/plugins/codemirror/plugin.js
  assets/scripts/admin/conditions.js
  assets/scripts/admin/globalsettings.js
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/answer.twig
  themes/survey/bootswatch/options/options.twig
  themes/survey/fruity/options/options.twig
  themes/survey/vanilla/options/options.twig
  themes/survey/vanilla/views/subviews/logincomponents/captcha.twig
  themes/survey/vanilla/views/subviews/logincomponents/token.twig
  themes/survey/vanilla/views/subviews/registration/register_form.twig
Labels: Tested OK, Code review done

#3117 Fixed issue #18765: Answers are not populated correct in array dual scale after clicking "Back"
  application/core/QuestionTypes/ArrayMultiscale/RenderArrayMultiscale.php
Labels: Tested OK, Code review done

#3074 Fixed issue #17560: Layout issue when setting user rights.
  application/models/User.php
  application/views/userManagement/partial/editpermissions.php
  assets/packages/adminbasics/build/adminbasics.css
  assets/packages/adminbasics/build/adminbasics.min.css
  assets/packages/adminbasics/build/adminbasics.rtl.css
  assets/packages/adminbasics/build/adminbasics.rtl.min.css
  assets/packages/adminbasics/scss/000-lime-admin-common.scss
Labels: Tested OK, Code review done

#3061 Fixed issue #18765: Answers are not populated correct in array dual scale after clicking "Back"
  application/core/QuestionTypes/ArrayMultiscale/RenderArrayMultiscale.php
Labels: Tested OK, Code review done

#3132 Dev: Generate simple statistics test.
  tests/data/surveys/survey_simple_statistics.lsa
  tests/unit/helpers/GenerateSimpleStatisticsTest.php
Labels: Needs code review, Has auto test

#3107 Fixed issue #18787: Wrong default answers are loaded for multilingual surveys
  application/helpers/common_helper.php
Labels: Needs code review, Needs testing

#3106 Fixed issue #18787: Wrong default answers are loaded for multilingual surveys
  application/helpers/common_helper.php
Labels: Needs code review, Needs testing

#3066 Fixed issue #18703: Upload files show error if not seen (using index)
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done, minor impact

#2876 Fixed issue #18605: Missing success alerts in participant view
  application/controllers/AssessmentController.php
  application/controllers/QuotasController.php
  application/controllers/admin/Themes.php
  application/controllers/admin/Tokens.php
  application/controllers/admin/globalsettings.php
  application/models/Assessment.php
  application/models/services/Quotas.php
  application/views/quotas/viewquotas_massive_selector.php
  assets/scripts/admin/assessments.js
  assets/scripts/admin/tokens.js
Labels: Needs code review, Tested OK

#3138 Fixed issue #18262: QCode.gid is not working anymore
  application/helpers/expressions/em_core_helper.php
Labels: Tested OK, Code review done

#3140 Dev: Generate simple statistics tests.
  tests/data/surveys/survey_simple_statistics.lsa
  tests/unit/helpers/GenerateSimpleStatisticsTest.php
Labels: Needs code review, Has auto test

#3141 Fixed issue #18814: Array question statistics fail for Remote Control.
  application/helpers/common_helper.php
  tests/data/surveys/survey_statistics_one.lsa
  tests/data/surveys/survey_statistics_three.lsa
  tests/data/surveys/survey_statistics_two.lsa
  tests/unit/helpers/remotecontrol/ExportStatisticsArrayQuestionsTest.php
  tests/unit/helpers/remotecontrol/ExportStatisticsTest.php
Labels: Needs code review, Has auto test

#3122 Fixed issue #18670: "Validation of quota" action button always shows 1st quota
  application/views/admin/quotas/viewquotas_quota_actions.php
Labels: Tested OK, Code review done

#3139 Fixed issue #18670: "Validation of quota" action button always shows 1st quota
  application/views/quotas/index.php
Labels: Tested OK, Code review done

#3113 Fixed issue #18805: No replacement variables available on user administration page
  application/controllers/LimereplacementfieldsController.php
Labels: Tested OK, Code review done, minor impact

#3048 New Feature #18742: Allow "User Admins" to see Users' Roles
  application/models/User.php
Labels: Tested OK, Code review done

#3091 Fixed issue #18725: Reorder questions/question groups can broke survey
  application/config/version.php
  application/controllers/SurveyAdministrationController.php
  application/core/LSYii_NoUpdateValidator.php
  application/core/LsDefaultDataSets.php
  application/helpers/update/updates/Update_497.php
  application/models/Question.php
  application/views/admin/survey/organizeGroupsAndQuestions_view.php
  assets/scripts/admin/organize.js
Labels: Needs code review, Tested OK

#2708 Fixed issue #18464: Min/max settings doesn't work for question attrib…
  application/extensions/AdvancedSettingWidget/views/integer.php
  application/models/QuestionAttribute.php
Labels: Tested OK, Code review done, minor impact

#2734 InstallerConfigForm.php: Clarification PostgreSQL complete socket path
  application/models/InstallerConfigForm.php
Labels: Code review done, minor impact

#3162 Fixed issue #18835: Array question doesn't reload anwsers
  application/core/QuestionTypes/ArrayFlexibleRow/RenderArrayFlexibleRow.php
  application/views/survey/questions/answer/arrays/array/no_dropdown/rows/cells/answer_td.twig
Labels: Needs testing, Code review done

#3121 Dev: Remote Control export statistics tests
  tests/data/surveys/survey_statistics_one.lsa
  tests/data/surveys/survey_statistics_two.lsa
  tests/unit/helpers/remotecontrol/ExportStatisticsTest.php
Labels: Needs code review, Has auto test

#3160 Fixed issue #18659: cannot install two plugins in a row
  application/libraries/ExtensionInstaller/FileFetcherUploadZip.php
Labels: Tested OK, Code review done

#3146 Fixed issue #18659: cannot install two plugins in a row
  application/libraries/ExtensionInstaller/FileFetcherUploadZip.php
Labels: Tested OK, Code review done

#3161 fix missing header in the dual scale array
  application/views/survey/questions/answer/arrays/dualscale/answer.twig
Labels: Tested OK, Code review done

#3159 Fixed issue #18462: Missing option to search for survey groups at list survey screen.
  application/extensions/admin/survey/ListSurveysWidget/views/searchBox.php
Labels: Tested OK, Code review done

#2510 Fixed issue #18246: The setting in the theme variation field (global level) is not shown
  application/models/TemplateConfiguration.php
Labels: Tested OK, minor impact

#3149 optimized response page
  application/controllers/ResponsesController.php
  application/controllers/admin/Tokens.php
  application/views/admin/token/surveyParticipantView.php
  application/views/admin/token/tokensummary.php
  application/views/responses/browseindex_view.php
  application/views/responses/partial/notSubmittedResponseListTable.php
  application/views/responses/partial/responseListTable.php
  application/views/responses/partial/responseSummary.php
  application/views/responses/partial/topbarBtns/leftSideButtons.php
  application/views/responses/partial/topbarBtns/rightSideButtons.php
  application/views/surveyAdministration/partial/topbar_tokens/leftSideButtons.php
  assets/admin_themes/Sea_Green/admin_customizations.scss
  assets/admin_themes/Sea_Green/sea_green_variables.scss
  assets/admin_themes/Sea_Green/typography/typography-mixins.scss
  assets/scripts/admin/tokens.js
  tests/data/views/adminSurveyViews.php
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Code review done

#3148 Fixed issue #18823: STATA Export fails with certain question types
  application/core/plugins/ExportSTATAxml/STATAxmlWriter.php
Labels: Tested OK, Code review done
