Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-01, with the labels that each got.

#2809 Dev #8436: Enable / disable users and fields to manage users
  tests/functional/backend/UserManagementTest.php
Labels: Needs code review

#2823 Fixed issue #18542: Plugins: PasswordRequirement plugin is not working properly
  application/core/plugins/PasswordRequirement/PasswordRequirement.php
Labels: Tested OK, Code review done, minor impact

#2820 Fixed issue #18491: Theme editor : List of fonts and colors should be sorted alphabetically
  application/config/fonts.php
  themes/survey/fruity/config.xml
  themes/survey/vanilla/config.xml
Labels: Tested OK, Code review done

#2818 Fixed issue #18481: Panel Configuration : Insert new box without position
  application/models/Box.php
Labels: Tested OK, Code review done

#2812 Fixed issue #18516: Create Survey button allows multiple clicking and may create multiple copies
  application/views/surveyAdministration/tabCopy_view.php
  application/views/surveyAdministration/tabCreate_view.php
Labels: Tested OK, Code review done

#2822 Fixed issue #18569: Survey editing : typo in error message
  application/helpers/expressions/em_manager_helper.php
  locale/_template/limesurvey.pot
Labels: Code review done

#2794 Fixed issue #18507: {ANSWERTABLE} not working in basic admin notification
  application/helpers/frontend_helper.php
Labels: Tested OK, Code review done

#2793 Fixed issue #18543: Question Type "Array (texts)" crashes when in combination with "array filter", "Array filter style": disabled and "show totals"
  assets/packages/limesurvey/survey.js
  assets/packages/questions/arraynumeric/scripts/array-totalsum.js
  assets/packages/questions/arraynumeric/scripts/array-totalsum.min.js
Labels: Tested OK, Code review done

#2792 Fixed issue #18502: STATA export of simple array question fails
  application/core/plugins/ExportSTATAxml/STATAxmlWriter.php
Labels: Tested OK, Code review done

#2744 Fixed issue #18498: Questions with custom themes not shown on question list
  application/models/Question.php
Labels: Needs code review, Tested OK

#2821 Fixed issue #18517: Survey editing : Survey creation date is wrong
  application/models/Survey.php
Labels: Tested OK, Code review done

#2795 Fixed issue #18544: Update Theme Options: Survey Group permissions are not checked correctly
  application/controllers/ThemeOptionsController.php
Labels: Tested OK, Code review done

#2843 New feature #07641: Options to use Y/N conversion in RemoteControl API export
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/survey_archive_RemoteControlExportResponses.lsa
  tests/unit/helpers/RemoteControlTest.php
Labels: Needs testing, Code review done

#2849 Fixed issue #18592: When creating a survey Default group may not be the ones preselected
  application/views/surveyAdministration/tabCreate_view.php
Labels: Needs testing, Code review done

#2867 Fixed issue #18596: Reintroduce lost unit tests from merge
  tests/unit/helpers/RemoteControlExportResponsesTest.php
  tests/unit/helpers/RemoteControlGetAvailableSiteSettingsTest.php
  tests/unit/helpers/RemoteControlTest.php
Labels: Needs code review

#2866 Fixed issue #18582: RemoteControl invite_participants unexpectedly stops after first failure
  application/helpers/admin/token_helper.php
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/data/surveys/limesurvey_survey_InviteParticipantsTest.lsa
  tests/unit/helpers/remotecontrol/BaseTest.php
  tests/unit/helpers/remotecontrol/InviteParticipantsTest.php
Labels: Tested OK, Code review done

#2811 Fixed issue #18562: Upload question type partially broken
  application/config/version.php
  application/controllers/UploaderController.php
  application/helpers/qanda_helper.php
  assets/scripts/modaldialog.js
  assets/scripts/uploader.js
Labels: Tested OK, Code review done

#2363 New feature #16619: Allow calling get_uploaded_files() remote control function by response ID
  application/helpers/remotecontrol/remotecontrol_handle.php
  tests/TestBaseClass.php
  tests/data/surveys/survey_archive_getFileUploadTest.lsa
  tests/data/surveys/survey_archive_getFileUploadTestClosed.lsa
  tests/unit/helpers/RemoteControlGetUploadedFilesTest.php
  tests/unit/helpers/RemoteControlTest.php
Labels: Tested OK, Code review done

#2858 Fixed issue #18594: Slider: Min and max values not checked if nothing selected
  assets/packages/questions/numeric-slider/scripts/numeric-slider.js
Labels: Tested OK, Code review done
