Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-09, with the labels that each got.

#3418 Fixed issue #18602: When surveys are copied without copying attachments, attachment info is copied but not updated
  application/controllers/admin/EmailTemplates.php
  application/helpers/admin/import_helper.php
  application/views/admin/emailtemplates/email_language_template_tab.php
  assets/packages/emailtemplates/emailtemplates.js
  assets/packages/emailtemplates/emailtemplates.min.js
Labels: Needs code review, Needs testing

#3420 QE-340 op handler languagesettings update
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerLanguageSettingsUpdate.php
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerSurveyTrait.php
  application/libraries/Api/Command/V1/SurveyPatch/PatcherSurvey.php
  tests/unit/api/opHandlers/OpHandlerLanguageSettingsTest.php
Labels: Tested OK, Code review done

#3397 Fixed issue #19039: Action Links Drop Down Menu Not Working In CPM
  application/models/Participant.php
  assets/scripts/admin/participantpanel.js
Labels: Needs testing, Code review done

#3411 Fixed issue #18593: Float attributes are not supported anymore
  application/extensions/AdvancedSettingWidget/AdvancedSettingWidget.php
  application/extensions/AdvancedSettingWidget/views/float.php
Labels: Tested OK, Code review done

#3202 Fixed issue #18593: Float attributes are not supported anymore
  application/extensions/AdvancedSettingWidget/AdvancedSettingWidget.php
  application/extensions/AdvancedSettingWidget/views/float.php
Labels: Tested OK, Code review done

#3326 Fixed issue #18981: using ngT to translate plurals loads wrong locale folder
  application/helpers/surveytranslator_helper.php
Labels: Needs code review, Tested OK

#2861 Fixed issue #18557: Email Template Attachments appear to carry over with copied survey, but do not work
  application/helpers/admin/import_helper.php
  application/helpers/common_helper.php
  tests/unit/helpers/TranslateLinksTest.php
Labels: Needs update by author, Tested OK

#3324 Fixed issue #18832: Participants can't re-enter a submitted survey if setting is using inherit at participant settings
  tests/unit/models/TokenDynamicTest.php
Labels: Needs code review, Tested OK

#3435 5x/cr 1160 show informative message before upgrading to ls6
  application/controllers/PluginsController.php
  application/libraries/MenuObjects/views/_extraMenu.php
  application/libraries/PluginManager/PluginBase.php
Labels: Code review done

#3359 Fixed issue #19019: Stored XSS in description of theme
  application/models/TemplateConfiguration.php
Labels: Tested OK, Code review done

#3426 Fixed issue #19056: save button in create dummy participants page actually saves and closes
  application/controllers/admin/Tokens.php
Labels: Tested OK, Code review done

#3429 Fixed issue #18601: No editor available when defining quota messages.
  application/controllers/QuotasController.php
  application/helpers/admin/htmleditor_helper.php
  application/views/quotas/_form_langsetting.php
  application/views/quotas/_form_langsettings.php
Labels: Tested OK, Code review done

#3430 Fixed issue #18602: When surveys are copied without copying attachments, attachment info is copied but not updated
  application/controllers/admin/EmailTemplates.php
  application/helpers/admin/import_helper.php
  application/views/admin/emailtemplates/email_language_template_tab.php
  assets/packages/emailtemplates/emailtemplates.js
  assets/packages/emailtemplates/emailtemplates.min.js
Labels: Tested OK, Code review done

#3441 Fixed issue #18494: TypeError during demo survey "ls205_em_tailoring"
  application/helpers/expressions/em_core_helper.php
  tests/unit/ExpressionManagerTest.php
  tests/unit/LSYiiValidatorsTest.php
Labels: Tested OK, Code review done

#3421 Fixed issue #19068: Batch actions dropdown is disabled after first use on User management page
  application/extensions/admin/grid/MassiveActionsWidget/assets/listActions.js
  application/views/userManagement/index.php
Labels: Tested OK, Code review done

#3406 Fixed issue #19037: Reflected XSS in LimeSurvey via userid parameter
  application/controllers/UserManagementController.php
Labels: Needs testing, Code review done

#3412 Fixed issue #19037: Reflected XSS in LimeSurvey via userid parameter
  application/controllers/UserManagementController.php
Labels: Needs testing, Code review done

#3401 Fixed issue #18978: User is able to change survey group's code that is by default unchangeable
  application/controllers/admin/SurveysGroupsController.php
  application/models/SurveysGroups.php
Labels: Tested OK, Code review done

#3400 Fixed issue #18978: User is able to change survey group's code that is by default unchangeable
  application/controllers/admin/SurveysGroupsController.php
  application/models/SurveysGroups.php
Labels: Tested OK, Code review done

#3398 Fixed issue #19041: Action dropdown is blocked after filter or changing rows per page
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code review done

#3443 Fixed issue #18494: TypeError during demo survey "ls205_em_tailoring"
  application/helpers/expressions/em_core_helper.php
  tests/unit/ExpressionManagerTest.php
Labels: Tested OK, Code review done

#3431 Fixed issue #19072: CDbException with Microsoft SQL Server
  application/models/Survey.php
Labels: Tested OK, Code review done

#3382 Fixed bug #18342: Default ranking help text is missing helpm icon
  assets/packages/questions/ranking/scripts/ranking.js
Labels: Tested OK, Code review done

#3372 Fixed bug #18627 Missing SQL query errors in admin mail (SQL CODE THAT FAILED)
  application/helpers/admin/import_helper.php
  application/helpers/expressions/em_manager_helper.php
  application/models/SurveyDynamic.php
  tests/TestBaseClass.php
  tests/unit/models/SurveyDynamicTest.php
Labels: Tested OK, Code review done

#3370 Fixed issue #19018: Postgres: trying to update from 5.6.31 to master caused an error
  application/helpers/update/updates/Update_605.php
Labels: Tested OK, Code review done

#3361 Fixed bug #18799 Admin user with full CPDB permissions can no access attribute section.
  application/controllers/admin/ParticipantsAction.php
  application/views/admin/participants/partial/topbarBtns/leftSideButtons.php
Labels: Tested OK, Code review done

#3353 Fixed issue #15310: Display dropdown boxes - Date/Time question type not working correctly if minimum date < 1900
  application/core/QuestionTypes/Date/RenderDate.php
  application/helpers/expressions/em_manager_helper.php
Labels: Needs testing, Code review done

#3320 Fixed issue #18942: Roles: Permissions Modal is too narrow
  application/views/userRole/partials/_permissions.php
Labels: Tested OK, Code review done

#3402 Fixed issue #18904: Stored XSS with Expression Script in End page
  application/helpers/SurveyRuntimeHelper.php
Labels: Needs code review, Needs testing

#3428 Fixed issue #CT-337: Wrong survey being picked up when using alias
  application/core/LSYii_Application.php
Labels: Needs code review, Needs testing

#3427 Fixed issue #CT-337: Wrong survey being picked up when using alias
  application/core/LSYii_Application.php
Labels: Tested OK, Code review done

#3379 Fixed issue #18957: Ranking Advanced: Visualization Types are not working
  themes/question/ranking_advanced/survey/questions/answer/ranking/answer.twig
  themes/question/ranking_advanced/survey/questions/answer/ranking/config.xml
  themes/question/ranking_advanced/views/bubbles.twig
Labels: Tested OK, Code review done

#3358 Fixed issue #19025: When there are question themes installed, can't upload survey themes
  application/views/themeOptions/availablethemelist.php
  application/views/themeOptions/index.php
Labels: Tested OK, Code review done

#3459 Fixed issue #18984: CSRF in Question Themes function
  application/controllers/admin/QuestionThemes.php
  application/views/themeOptions/installedthemelist.php
Labels: Tested OK, Code review done

#3464 Fixed issue #19096: Array by column answer options are not processed …
  application/views/survey/questions/answer/arrays/column/answer.twig
Labels: Tested OK, Code review done

#3476 Fixed issue #19096: Array by column answer options are not processed …
  application/views/survey/questions/answer/arrays/column/answer.twig
Labels: Tested OK, Code review done

#3475 Fixed issue #18968: User with "View/read Users" permission needs to have "User details" action available for all users, not just itself
  application/models/User.php
Labels: Tested OK, Code review done

#3468 Fixed issue #18938: question_template_attribute show only default value
  application/models/QuestionTemplate.php
Labels: Tested OK, Code review done, minor impact

#3481 Fixed issue #18938: question_template_attribute show only default value
  application/models/QuestionTemplate.php
Labels: Tested OK, Code review done

#3485 Fixed issue [security] #18986: superadmin without create superadmin can create superadminu
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3448 Fixed issue #18986: superadmin without create superadmin can create superadmin
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3473 Fixed issue #18984: CSRF in Question Themes function
  application/controllers/admin/QuestionThemes.php
  application/views/themeOptions/installedthemelist.php
Labels: Tested OK, Code review done

#3483 Fixed issue [security] #19099: XSS vulnerability caused by themeOptions/importManifest
  application/models/TemplateConfiguration.php
  application/views/admin/globalsettings/_general.php
  application/views/admin/survey/subview/accordion/_generaloptions_panel.php
Labels: Tested OK, Code review done

#3472 Fixed issue [security] #19099: XSS vulnerability caused by themeOptions/importManifest
  application/extensions/admin/survey/ListSurveysWidget/views/massive_actions/_select_survey_theme.php
  application/models/TemplateConfiguration.php
  application/views/admin/globalsettings/_general.php
  application/views/admin/survey/subview/accordion/_generaloptions_panel.php
Labels: Tested OK, Code review done

#3461 Fixed issue #19063: import of broken lsa file yields success message (but inactive "Go to survey" button)
  application/helpers/admin/import_helper.php
Labels: Tested OK, Code review done

#3463 Fixed issue #19063: import of broken lsa file yields success message (but inactive "Go to survey" button)
  application/helpers/admin/import_helper.php
Labels: Tested OK, Code review done

#3456 Fixed issue #19004: Can not delete or edit assessment rules
  application/models/Assessment.php
  assets/scripts/admin/assessments.js
Labels: Tested OK, Code review done

#3444 Fixed issue #19019: Stored XSS in description of theme
  application/models/TemplateConfiguration.php
Labels: Tested OK, Code review done

#3453 Fixed issue #18601: No editor available when defining quota messages.
  application/controllers/admin/Quotas.php
  application/helpers/admin/htmleditor_helper.php
  application/views/admin/quotas/_form_langsetting.php
  application/views/admin/quotas/_form_langsettings.php
Labels: Tested OK, Code review done

#3452 Fixed issue #18494: TypeError during demo survey "ls205_em_tailoring"
  tests/unit/ExpressionManagerTest.php
Labels: Code review done, Has auto test

#3367 CR-1305: Structure tab question menu should always show "Edit default answers" option
  application/config/version.php
  application/controllers/SurveyAdministrationController.php
  application/helpers/update/updates/Update_615.php
  application/models/QuestionType.php
  application/views/survey/questions/answer/5pointchoice/config.xml
  application/views/survey/questions/answer/gender/config.xml
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.css
  assets/packages/adminsidepanel/build.min/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/css/adminsidepanel.css
  assets/packages/adminsidepanel/build/css/adminsidepanel.rtl.css
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
Labels: Needs testing, Code review done

#3447 Fixed issue #18995: Confidentiality issue about username
  application/helpers/common_helper.php
  application/models/User.php
  application/models/services/SurveyUpdater/GeneralSettings.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsFactory.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsMockSet.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsMockSetFactory.php
Labels: Tested OK, Code review done

#3335 Fixed issue #18439: Link set when create user are unusuable in text view
  application/core/LimeMailer.php
Labels: Tested OK, Code review done

#3356 Fixed issue #18648: Unable to upload a file with theme animations enabled
  themes/survey/fruity/views/subviews/header/custom_header.twig
Labels: Tested OK, Code review done

#2540 Fixed issue #18268: Unable to get any page debug set an set_time_limit disable
  application/core/LSYii_Controller.php
Labels: Tested OK, Code review done, Technical

#3499 Fixed issue #19136: Undefined variable in admin global settings gener…
  application/views/admin/globalsettings/_general.php
Labels: Tested OK, Code review done, minor impact

#3494 Fixed issue #19115: Menu toggler appears when not needed
  themes/survey/vanilla/views/subviews/header/nav_bar.twig
Labels: Tested OK, Code review done
