Repository LimeSurvey/LimeSurvey, pull requests merged in 2023-11, with the labels that each got.

#3590 Fixed issue #19203: alphabetical order didn't respect survey language
  application/models/Question.php
  application/models/QuestionBaseRenderer.php
  application/models/QuestionCreate.php
Labels: Tested OK, Code review done

#3581 Fixed issue #19203: alphabetical order didn't respect survey language
  application/models/Question.php
  application/models/QuestionBaseRenderer.php
  application/models/QuestionCreate.php
Labels: Tested OK, Code review done

#3587 Fixed issue [security] #19133: User can send email to group members, while not having permissions
  application/controllers/UserGroupController.php
  application/views/userGroup/partial/topbarBtns_manageGroup/leftSideButtons.php
Labels: Tested OK, Code review done

#3586 Fixed issue #19133: User can send email to group members, while not having permissions
  application/controllers/UserGroupController.php
  application/views/userGroup/usergroupbar_view.php
Labels: Tested OK, Code review done

#3531 Fixed issue #19139: CSRF in Reset Survey menus
  application/controllers/admin/SurveymenuController.php
Labels: Tested OK, Code review done

#3588 Fixed issue #19139: CSRF in Reset Survey menus
  application/core/LSHttpRequest.php
  tests/unit/CsrfHttpRequestTest.php
Labels: Tested OK, Code review done

#3579 Fixed issue #19118: Improper permission management on bulk actions
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3580 Fixed issue [security] #19118: Improper permission management on bulk actions
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3595 Fixed issue #18350: activate_survey does not correctly set inherited …
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done

#3584 Fixed issue #19162: File Upload causes XSS in Central participant management/Import file CSV
  application/controllers/admin/ParticipantsAction.php
  application/views/admin/participants/uploadSummary_view.php
Labels: Tested OK, Code review done

#3585 Fixed issue #19162: File Upload causes XSS in Central participant management/Import file CSV
  application/controllers/admin/ParticipantsAction.php
  application/views/admin/participants/uploadSummary_view.php
Labels: Tested OK, Code review done

#3597 Fixed issue #19218: PHP error with PHP81 and debug with strpos in asSplitStringOnExpressions function
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done

#3608 Fixed issue #19224: Advanced ranking does not respect max answer when drag-n-drop
  themes/question/ranking_advanced/survey/questions/answer/ranking/assets/scripts/advanced_ranking.js
Labels: Tested OK, Code review done

#3611 Fixed issue #19214: JSON RPC response content type should be applicat…
  application/libraries/LSjsonRPCServer.php
Labels: Tested OK, Code review done

#3610 Fixed issue #19214: JSON RPC response content type should be applicat…
  application/libraries/LSjsonRPCServer.php
Labels: Tested OK, Code review done

#3601 Fixed issue [security] #19211: CSRF In Copy Survey
  application/controllers/SurveyAdministrationController.php
Labels: Tested OK, Code review done

#3543 Fixed issue #19081: Lato fonts are loaded from Google fonts instead of solely using the ones shipped with limesurvey itself
  themes/survey/bootswatch/css/variations/README.txt
  themes/survey/bootswatch/css/variations/cosmos.min.css
  themes/survey/bootswatch/css/variations/cyborg.min.css
  themes/survey/bootswatch/css/variations/darkly.min.css
  themes/survey/bootswatch/css/variations/flatly.min.css
  themes/survey/bootswatch/css/variations/journal.min.css
  themes/survey/bootswatch/css/variations/lumen.min.css
  themes/survey/bootswatch/css/variations/paper.min.css
  themes/survey/bootswatch/css/variations/readable.min.css
  themes/survey/bootswatch/css/variations/sandstone.min.css
  themes/survey/bootswatch/css/variations/simplex.min.css
  themes/survey/bootswatch/css/variations/spacelab.min.css
  themes/survey/bootswatch/css/variations/superhero.min.css
  themes/survey/bootswatch/css/variations/yeti.min.css
Labels: Tested OK, Code review done

#3562 Fixed issue #19086: Survey Theme Options: image preview does not work
  application/views/themeOptions/options_core.php
  assets/packages/themeoptions-core/themeoptions-core.js
Labels: Tested OK, Code review done

#3553 Fixed issue #19114: Admin with Settings & Plugins permission only can store XSS in Survey menus
  application/models/SurveymenuEntries.php
Labels: Tested OK, Code review done

#3512 Fixed issue #18995: Confidentiality issue about username
  application/controllers/admin/Database.php
  application/models/services/SurveyUpdater/GeneralSettings.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsExceptionsTest.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsFactory.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsMockSet.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsMockSetFactory.php
  tests/unit/services/SurveyUpdater/GeneralSettings/GeneralSettingsUpdateOwnerTest.php
Labels: Tested OK, Code review done

#3603 Fixed issue #19139: CSRF in Reset Survey menus
  application/config/internal.php
  application/core/LSHttpRequest.php
  tests/unit/CsrfHttpRequestTest.php
Labels: Tested OK, Code review done

#3609 Fixed issue #18350: activate_survey does not correctly set inherited …
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done

#3613 Fixed issue : Unable to create survey with debug = 2 and PHP8
  application/core/LSYii_Validators.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#3616 Fixed issue #19224: Advanced ranking does not respect max answer when drag-n-drop
  themes/question/ranking_advanced/survey/questions/answer/ranking/assets/scripts/advanced_ranking.js
Labels: Tested OK, Code review done

#3598 Fixed issue #19139: CSRF in Reset Survey menus
  application/config/internal.php
  application/core/LSHttpRequest.php
  tests/functional/backend/RemoteControlTest.php
  tests/unit/CsrfHttpRequestTest.php
Labels: Tested OK, Code review done

#3354 Fixed issue #18894: Not able to add theme option text input
  application/controllers/admin/Themes.php
  application/views/themeOptions/options_core.php
  assets/packages/themeoptions-core/themeoptions-core.js
Labels: Tested OK, Code review done

#2984 Fixed issue #18671: Potential loop with equation set question
  assets/packages/expressions/em_javascript.js
Labels: Tested OK, Code review done

#3612 Fixed issue #19139: CSRF in Reset Survey menus (Tests)
  tests/functional/backend/RemoteControlTest.php
Labels: Needs testing, Code review done

#3626 Fixes issue #19149: fruity_23: can't change language (languages are n…
  themes/survey/fruity_twentythree/views/layout_survey_list.twig
Labels: Tested OK, Code review done

#3635 Fixed issue #19168: XSS in Survey menus (Menu icon type and Menu icon)
  application/models/SurveymenuEntries.php
Labels: Tested OK, Code review done

#3636 Fixed issue #19168: XSS in Survey menus (Menu icon type and Menu icon)
  application/models/SurveymenuEntries.php
Labels: Tested OK, Code review done

#3617 Fixed issue #19228: Setting Bruteforce timeout values to empty string causes the administrator to be locked out
  application/models/FailedLoginAttempt.php
  application/views/admin/globalsettings/_security.php
Labels: Tested OK, Code review done

#3618 Fixed issue #19228: Setting Bruteforce timeout values to empty string causes the administrator to be locked out
  application/models/FailedLoginAttempt.php
  application/views/admin/globalsettings/_security.php
Labels: Tested OK, Code review done

#3637 Fixed issue #19206: alphabetical order can be bad with utf8 caracter
  application/helpers/SortHelper.php
  application/models/InstallerConfigForm.php
  application/models/Question.php
  application/views/installer/precheck_view.php
  tests/data/surveys/limesurvey_survey_OrderTestSurvey.lss
  tests/functional/frontend/AnswersAlphabeticalOrderTest.php
Labels: Tested OK, Code review done, Has auto test

#3619 Fixed issue #19206: alphabetical order can be bad with utf8 caracter
  application/helpers/SortHelper.php
  application/models/InstallerConfigForm.php
  application/models/Question.php
  application/views/installer/precheck_view.php
Labels: Tested OK, Code review done

#3614 Fixed issue #19232: Missing cssframework default values for survey th…
  themes/survey/bootswatch/config.xml
  themes/survey/fruity/config.xml
  themes/survey/fruity_twentythree/config.xml
Labels: Tested OK, Code review done

#3521 Fixed issue #19049: Cannot export LSS from survey where theme is set to one extended from 'bootswatch'
  application/models/TemplateConfig.php
  application/models/TemplateManifest.php
  tests/unit/models/TemplateConfigTest.php
Labels: Tested OK, Code review done

#3634 Fixed issue [security] #19252: Bad permission check when edit quota (Thanks to gblanco )
  application/controllers/admin/Quotas.php
Labels: Tested OK, Code review done

#3639 Fixed issue #19276: When a user exit on quota, the theme is not applied correctly if "inherits everything" is set to off
  application/helpers/frontend_helper.php
Labels: Tested OK, Code review done

#3638 Fixed issue #19276: When a user exit on quota, the theme is not applied correctly if "inherits everything" is set to off
  application/helpers/frontend_helper.php
Labels: Tested OK, Code review done

#3629 Fixed issue 19255: PHP8.1 + debug : survey with only stardate broke survey listing
  application/models/Survey.php
Labels: Tested OK, Code review done

#3641 Fixed issue #19271 : when copy a question : question settings are lost by default
  application/controllers/QuestionAdministrationController.php
  application/views/questionAdministration/copyQuestionForm.php
Labels: Tested OK, Code review done

#3625 Fixed issue #19243: date question type use always english for month and day
  application/core/QuestionTypes/Date/RenderDate.php
Labels: Tested OK, Code review done

#3621 New feature #18880: New imagefile option type for theme options
  application/controllers/admin/Themes.php
  application/models/TemplateConfiguration.php
  application/views/themeOptions/options_core.php
Labels: Tested OK, Discussion ongoing, Code review done

#3454 Fixed issue #18961: {SURVEYURL} didn't work with plugin using cli event
  application/core/LSYii_Application.php
  application/core/Traits/LSApplicationTrait.php
Labels: Tested OK, Code review done
