Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-12, with the labels that each got.

#4077 Fixed issue #19838: Plugin upload doesn't allow LSS, LSA, LSG and LSQ files
  application/config/config-defaults.php
Labels: Tested OK, Code review done

#4056 Fixed issue #19661: Data inconsistency in responses after importing LSA files
  application/helpers/admin/import_helper.php
  application/models/SurveyDynamic.php
  tests/data/surveys/limesurvey_survey_478651_import_export_irrelevant.lss
  tests/data/surveys/survey_simple_statistics.lsa
  tests/functional/backend/ImportExportIrrelevantTest.php
Labels: Tested OK, Code review done, Has auto test

#4104 Fixed issue CR-1364: Unchecking "Exclusive option" leaves other options disabled (multiple bootstrap buttons)
  themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/rows/answer_row.twig
Labels: Tested OK, Code review done

#4108 19661: Data inconsistency in responses after importing LSA files
  tests/unit/helpers/remotecontrol/ExportStatisticsArrayQuestionsTest.php
  tests/unit/helpers/remotecontrol/ExportStatisticsTest.php
Labels: Needs testing, Code review done

#4102 Fixed issue #19885: Wrong characters displayed in when deleting a question
  application/controllers/SurveyAdministrationController.php
Labels: Needs testing, Code review done

#4067 Fixed issue #19630: Add warning to permissions interface when assigni…
  application/models/Permission.php
  application/views/userManagement/partial/editpermissions.php
  application/views/userRole/partials/_permissions.php
Labels: Tested OK, Code review done

#4012 #19821 - Answer should deleted by delete() method
  application/models/Question.php
Labels: Needs testing

#4082 Fixed issue [security] #19864: Export question and group are not restricted
  application/controllers/admin/Export.php
  application/helpers/export_helper.php
Labels: Tested OK, Code review done

#4088 Fixed issue [security] #19870: Any user wit survey create permission can activate tokens on any survey
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done

#4106 Fixed issue [security] #19872: RC : Bad permission check on copy_survey
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done

#4085 Fixed issue [security] #19869: All group deletion accessible by any admin with one survey access
  application/helpers/remotecontrol/remotecontrol_handle.php
  application/models/QuestionGroup.php
Labels: Tested OK, Code review done

#4110 19860: Row level dropdown menu gest trimmed
  application/views/themeOptions/surveythemelist.php
Labels: Tested OK, Code review done

#4105 Fixed issue #19888: Check Remote Control API Log off admin
  application/controllers/admin/RemoteControl.php
Labels: Needs testing, Code review done

#4070 Feature/mw 1407 users cannot download db
  application/controllers/admin/dumpdb.php
  application/views/admin/dumpdb/dumpdb_view.php
Labels: Tested OK, Code review done

#4115 New feature #19881: Make survey group ID available as output or input for RPC
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done
