Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-06, with the labels that each got.

#3858 Fixed issue : Theme listing broke with invalid template
  application/models/TemplateConfiguration.php
Labels: Code review done

#3862 Fixed issue #19397: Editing menu entries not possible
  application/controllers/admin/SurveymenuEntryController.php
  application/models/SurveymenuEntries.php
  application/views/admin/surveymenu_entries/_form.php
  assets/packages/surveymenufunctions/surveymenufunctionswrapper.js
  assets/packages/surveymenufunctions/surveymenufunctionswrapper.min.js
Labels: Tested OK, Code review done

#3856 fixed issue #19570: javascript exception on survey taking on browsers…
  assets/packages/limesurvey/survey.js
  assets/packages/questions/timer/src/timeclass.js
  assets/packages/questions/timer/timer.js
  assets/packages/questions/timer/timer.min.js
  assets/scripts/timer.js
Labels: Tested OK, Code review done

#3855 MW-1040: SPSSWriter
  application/core/plugins/ExportSPSSsav/SPSSWriter.php
Labels: Tested OK, Code review done

#3854 Feature/mw 1040 statistics new
  application/controllers/admin/Statistics.php
Labels: Tested OK, Code review done

#3853 MW-1040: Refactored LS_Twig_Extension
  application/core/LS_Twig_Extension.php
Labels: Tested OK, Code review done

#3872 Fixed issue #19580: Data entry at anonymous survey with tokens crashed on save
  application/controllers/admin/DataEntry.php
Labels: Needs code review, Tested OK

#3873 Fixed issue #19580: Data entry at anonymous survey with tokens crashe…
  application/controllers/admin/DataEntry.php
Labels: Needs code review, Tested OK

#3874 Fixed issue #19457: Stored Cross-Site Scripting (XSS) in file upload question
  assets/packages/questions/upload/build/uploadquestion.js
  assets/packages/questions/upload/build/uploadquestion.min.js
  assets/packages/questions/upload/build/uploadquestion.min.js.map
  assets/packages/questions/upload/src/modaldialog.js
Labels: Tested OK, Code review done

#3880 Fixed issue [security] #19598: No CSRF protection on userManagement (thanks to paoloelia)
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3882 Fixed issue [security] #19599: Stored XSS through csv file upload (thanks to paoloelia )
  application/models/UserParser.php
Labels: Tested OK, Code review done

#3884 Fixed issue [security] #19599: Stored XSS through csv file upload (thanks to paoloelia )
  application/models/UserParser.php
Labels: Tested OK, Code review done

#3891 Fixed issue #19579: Styling of question summary breaks if there is RegEx Validation
  application/views/questionAdministration/summary.php
Labels: Tested OK, Code review done

#3890 Fixed issue #19509: Postgres error when adding language
  application/helpers/admin/label_helper.php
Labels: Tested OK, Code review done

#3770 Fixed issue #14661: Plugin development need a "Don't disable plugin"
  application/controllers/admin/PluginManagerController.php
  application/libraries/PluginManager/PluginManager.php
  application/libraries/PluginManager/PluginManagerShutdownFunction.php
  application/models/Plugin.php
Labels: Tested OK, Code review done

#3887 Fixed issue [security] #19608: XSS under user management (thanks to OIZ Stadt Zürich and Protec7)
  application/controllers/UserManagementController.php
  application/views/userManagement/partial/showuser.php
Labels: Tested OK, Code review done

#3888 Fixed issue [security] #19608: XSS under user management (thanks to OIZ Stadt Zürich and Protec7)
  application/views/userManagement/partial/showuser.php
Labels: Tested OK, Code review done

#3899 Dev: fix all plugin show as error in plugin listing
  application/models/Plugin.php
Labels: Needs code review, Needs testing

#3896 Fixed issue [security] #19603: All admin can be deactivated by user with only users delete permission
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3895 Fixed issue [security] #19604: The reset password link is reusable after password change
  application/controllers/admin/Authentication.php
  application/views/admin/authentication/newPassword.php
Labels: Tested OK, Code review done

#3885 Fixed issue [security] #19610: Security: queXML PDF discloses version specific information
  application/controllers/PrintanswersController.php
  application/controllers/ResponsesController.php
  application/libraries/admin/pdf.php
  application/libraries/admin/quexmlpdf.php
Labels: Tested OK, Code review done
