Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-01, with the labels that each got.

#3676 Fixed issue #19248: When deleting a token through the model, the AuditLog beforeDeleteToken event fails
  application/core/plugins/AuditLog/AuditLog.php
Labels: Tested OK, Code review done

#3684 Fixed issue #19325: When deleting a token the participant_id is being logged while it should be the token_id
  application/core/plugins/AuditLog/AuditLog.php
Labels: Tested OK, Code review done

#3689 feat: add TransformerOutputSurveyOwner
  application/libraries/Api/Command/V1/SurveyDetail.php
  application/libraries/Api/Command/V1/Transformer/Input/TransformerInputSurvey.php
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputSurvey.php
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputSurveyDetail.php
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputSurveyOwner.php
  application/models/Survey.php
Labels: Needs code review

#3693 [QE-9] Add preview link for survey
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputSurveyDetail.php
Labels: Needs code review

#3670 Fixed issue #19274: Attribute encryption can not be turned OFF, it can only be turned on
  application/controllers/admin/ParticipantsAction.php
  application/models/ParticipantAttributeName.php
Labels: Tested OK, Code review done

#3671 Fixed issue #19274: Attribute encryption can not be turned OFF, it can only be turned on
  application/controllers/admin/ParticipantsAction.php
  application/models/ParticipantAttributeName.php
Labels: Tested OK, Code review done

#3704 Fixed issue #CR-1393: login page UI issue
  application/views/admin/super/layout_main.php
  assets/admin_themes/Sea_Green/admin_customizations.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Needs code review

#3687 [QE-663] 3.1.4 Survey alias
  application/libraries/Api/Command/V1/Transformer/Input/TransformerInputSurveyLanguageSettings.php
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputSurveyLanguageSettings.php
Labels: Needs code review

#3710 Fixed issue #19251: Can't add Regex condition in survey
  application/views/admin/conditions/includes/quickAddConditionForm.php
  assets/scripts/admin/conditions.js
Labels: Tested OK, Code review done

#3706 Fixed issue #19372 : CDbException with Microsoft SQL Server and Group filter
  application/models/Survey.php
Labels: Tested OK, Code review done

#3686 Fixed issue #19331: Try to add a subquestion to a matrix type question throws an SQL error
  application/models/services/QuestionAggregateService/SubQuestionsService.php
  tests/unit/services/QuestionAggregateService/SubquestionsServiceTest.php
Labels: Tested OK, Code review done

#3695 Fixed issue #19313: No warning list when import same question code
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK, Code review done

#3705 Fixed issue [security] #19368: Simple admin can add XSS on adminemail
  application/models/Survey.php
  themes/survey/vanilla/views/layout_errors.twig
Labels: Tested OK

#3683 Fixed issue #19320: Error after accessing to response export view
  application/views/surveyAdministration/partial/topbar/surveyTopbarRight_view.php
Labels: Needs testing, Code review done

#3681 Fixed issue #19248: When deleting a token through the model, the Audi… …tLog beforeDeleteToken event fails
  application/core/plugins/AuditLog/AuditLog.php
Labels: Needs code review, Needs testing, Tested OK

#3677 Fixed issue #19253: CSV injection in export quota
  application/controllers/QuotasController.php
  application/core/LSYii_NonFormulaValidator.php
  application/helpers/common_helper.php
  application/models/Quota.php
Labels: Tested OK, Code review done

#3664 Fixed issue #19290: Wrong Row Total in Array (Texts)
  assets/packages/questions/arraynumeric/scripts/array-totalsum.js
  assets/packages/questions/arraynumeric/scripts/array-totalsum.min.js
Labels: Tested OK, Code review done

#3711 Fixed issue #19347: No generation of new user within first LDAP login
  application/core/plugins/AuthLDAP/AuthLDAP.php
Labels: Tested OK, Code review done

#3666 Fixed #19217: PHP8 Error Type NULL
  application/helpers/common_helper.php
  application/models/Survey.php
Labels: Tested OK
