Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-08, with the labels that each got.

#3920 Fixed issue [security] : 19639: Host Header Injection in password reset function (thanks to paoloelia)
  application/core/LSHttpRequest.php
Labels: Tested OK, Code review done

#3905 MW-1040: Refactoring usages of getQuestionAttributes at common_helper
  application/helpers/common_helper.php
Labels: Tested OK, Code review done

#3900 Fixed issue #18550: MSSQL Reponse filter with underscore or bracket not working
  application/core/LSDbCriteria.php
  application/models/Assessment.php
  application/models/LabelSet.php
  application/models/Participant.php
  application/models/ParticipantAttributeName.php
  application/models/Question.php
  application/models/QuestionGroup.php
  application/models/QuestionTheme.php
  application/models/SurveymenuEntries.php
  application/models/SurveysGroups.php
  application/models/Template.php
  application/models/TemplateConfiguration.php
Labels: Needs testing, Code review done

#3871 Fixed issue #19589: Multiple call of Survey->find for public survey
  application/models/Question.php
  application/models/Survey.php
Labels: Needs update by author, Tested OK, Code review done

#3946 Fixed issue #19717: SQL injection vulnerability when save survey
  application/helpers/common_helper.php
Labels: Needs testing, Code review done
