Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-05, with the labels that each got.

#3826 Fixed issue #19528: Bad usability when open in a new tab for participant edit
  application/controllers/admin/Tokens.php
  application/models/TokenDynamic.php
  application/views/admin/token/tokenform.php
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code review done

#3201 Fixed issue #18459: When filtering the survey list by a parent survey group, surveys assigned to a child survey group are not listed
  tests/unit/models/SurveySearchTest.php
Labels: Code review done, Has auto test

#3827 Fixed issue #19526: debug=2 PHP8.1 : unable to send email without expiry
  application/models/Survey.php
  application/views/admin/token/invite.php
  application/views/admin/token/remind.php
Labels: Tested OK, Code review done

#3811 DEV: Add comments about URLs on CLI
  application/controllers/InstallerController.php
Labels: Code review done

#3837 Fixed issue #19543: KCFinder needs to be updated when using with PHP 8.1
  vendor/kcfinder/core/bootstrap.php
  vendor/kcfinder/core/class/browser.php
  vendor/kcfinder/core/class/minifier.php
  vendor/kcfinder/core/class/uploader.php
  vendor/kcfinder/core/types/type_mime.php
  vendor/kcfinder/integration/drupal.php
  vendor/kcfinder/js_localize.php
  vendor/kcfinder/lib/class_fastImage.php
  vendor/kcfinder/lib/class_image.php
  vendor/kcfinder/lib/class_image_gd.php
  vendor/kcfinder/lib/class_image_gmagick.php
  vendor/kcfinder/lib/class_image_imagick.php
  vendor/kcfinder/lib/helper_file.php
  vendor/kcfinder/lib/helper_httpCache.php
  vendor/kcfinder/lib/helper_path.php
Labels: Tested OK, Code review done

#3848 Fixed issue #19561: popup messages come with HTML inside
  application/controllers/UserManagementController.php
  assets/packages/usermanagement/js/usermanagement.js
Labels: Tested OK, Code review done
