Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-02, with the labels that each got.

#3713 Fixed issue #19351: Limesurvey broken after 5.6.50 to 6.4.2 upgrade
  application/config/version.php
  application/helpers/update/updates/Update_619.php
  application/helpers/update/updates/Update_623.php
  application/models/User.php
Labels: Tested OK, Code review done

#3718 Fixed issue #19383: When export multiple choice filtered : loose N/A value
  application/helpers/admin/export/SurveyObj.php
Labels: Tested OK, Code review done

#3733 Fixed issue #19399: Survey do not show translated when register
  application/controllers/RegisterController.php
Labels: Tested OK, Code review done

#3732 Fixed issue #19399: Survey do not show translated when register
  application/controllers/RegisterController.php
Labels: Tested OK, Code review done

#3744 Fixed issue: Integrity check very slow when having a lot of surveys
  application/controllers/admin/CheckIntegrity.php
  application/controllers/admin/DataEntry.php
  application/helpers/common_helper.php
  application/helpers/update/updates/Update_148.php
  application/models/SurveyDynamic.php
  application/models/SurveyLight.php
  application/views/admin/checkintegrity/check_view.php
Labels: Code review done

#3739 Fixed issue: Slow performance when saving a survey with more than one language
  application/helpers/common_helper.php
Labels: Code review done

#3736 Fixed issue [security] #19087: Account takeover through Import User function
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3735 Fixed issue #19087: Account takeover through Import User function
  application/controllers/UserManagementController.php
Labels: Tested OK, Code review done

#3731 Dev: Fix PHP-DI CActiveRecord factory
  application/libraries/DI.php
  application/models/services/QuestionAggregateService/AnswersService.php
  tests/unit/services/QuestionAggregateService/AnswersServiceTest.php
Labels: Tested OK

#3737 Fixed issue #18473: Survey listing : multiple call of SurveyGroup
  application/models/SurveysGroupsettings.php
Labels: Needs testing

#3741 Fixed issue #19426: Survey listing : multiple call of same user
  application/models/Survey.php
  application/models/SurveysGroupsettings.php
Labels: Needs testing, Code review done

#3758 Fixed issue #19440: Pressing enter in question code circumvents validation
  application/config/version.php
  application/views/questionAdministration/answerOptionRow.twig
  application/views/questionAdministration/questionCode.php
  assets/scripts/admin/questionEditor.js
Labels: Tested OK, Code review done

#3743 Fixed #19217: PHP8 Error Type NULL
  application/helpers/common_helper.php
  application/models/Survey.php
Labels: Needs code review, Needs testing

#3753 Fixed issue #19435: Input validation does not work correctly with input numeric when reload response
  application/helpers/frontend_helper.php
Labels: Tested OK, Code review done

#3763 Fixed issue #CT-674: other field in list(radio) is cut off after 5 characters
  application/helpers/expressions/em_manager_helper.php
Labels: Code review done

#3764 Fixed issue #19429: Menus that don't want to disappear
  assets/packages/adminsidepanel/build.min/js/adminsidepanel.js
  assets/packages/adminsidepanel/build/js/adminsidepanel.js
  assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
Labels: Tested OK, Code review done

#3765 Fixed issue #19394: Off-button not shown in 'Create example question group and question:'
  application/controllers/admin/globalsettings.php
Labels: Tested OK, Code review done
