Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-09, with the labels that each got.

#3951 Fixed issue #19729 [security] : XSS on time_limit
  application/helpers/qanda_helper.php
  application/models/QuestionBaseRenderer.php
  application/views/survey/questions/question_timer/timer.php
  application/views/survey/questions/question_timer/timer.twig
  application/views/survey/questions/question_timer/timer_content.php
  application/views/survey/questions/question_timer/timer_content.twig
  application/views/survey/questions/question_timer/timer_footer.php
  application/views/survey/questions/question_timer/timer_footer.twig
  application/views/survey/questions/question_timer/timer_header.twig
  application/views/survey/questions/question_timer/timer_javascript.php
  application/views/survey/questions/question_timer/timer_javascript.twig
Labels: Needs testing, Code review done

#3954 Fixed issue #19733: XSS by simple user with end url
  themes/survey/fruity_twentythree/views/subviews/content/submit.twig
  themes/survey/fruity_twentythree/views/subviews/content/submit_preview.twig
  themes/survey/vanilla/views/subviews/content/submit.twig
  themes/survey/vanilla/views/subviews/content/submit_preview.twig
Labels: Needs code review, Needs testing

#3952 Fixed issue [security] #19732: XSS on date format
  application/core/QuestionTypes/Date/RenderDate.php
  application/extensions/DateTimePickerWidget/DateTimePicker.php
Labels: Needs testing, Code review done

#3950 fixed issue #19534: Survey cannot be submitted if "soft force" options are used and "full index" is active
  application/helpers/expressions/em_manager_helper.php
  application/views/survey/questions/question_help/softmandatory_input.twig
  themes/survey/fruity_twentythree/scripts/theme.js
  themes/survey/vanilla/views/subviews/messages/bootstrap_alert_modal.twig
  themes/survey/vanilla/views/subviews/navigation/navigator.twig
Labels: Tested OK, Code review done

#3943 Fixed issue #19519: When re-activating a token based survey the user is not asked to re-active the token table
  application/controllers/admin/Tokens.php
  application/libraries/DI.php
  application/models/services/SurveyDeactivate.php
Labels: Tested OK, Code review done

#3944 Fixed issue #19659: Conditions based on {LANG} variable fail
  application/helpers/expressions/em_manager_helper.php
  application/helpers/replacements_helper.php
Labels: Tested OK, Code review done

#3939 Fixed issue #19658: Condition designer - first option in Multiple short text (Type: Q) question is always assigned predefined (No Answer) value
  application/controllers/admin/ConditionsAction.php
Labels: Tested OK, Code review done

#3940 Fixed issue #19587: The theme option 'Background image' has a space in the name, so the image can't be loaded
  themes/survey/fruity/views/subviews/header/custom_header.twig
  themes/survey/fruity_twentythree/views/subviews/header/custom_header.twig
Labels: Tested OK, Code review done

#3941 Fixed issue #19677: Conversion from komma to point fails
  assets/packages/expressions/em_javascript.js
Labels: Tested OK, Code review done

#3953 Fixed issue #19700: Invalid DB value can be entered with start URL
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done

#3927 Improve .htaccess files to work with apache 2.4 w/o mod_access_compat
  application/.htaccess
  application/extensions/admin/grid/GridActionsWidget/assets/.htaccess
  application/extensions/admin/grid/MassiveActionsWidget/assets/.htaccess
  application/extensions/admin/grid/assets/.htaccess
  docs/.htaccess
  locale/.htaccess
  upload/surveys/.htaccess
Labels: Needs testing, Code review done, minor impact, Technical

#3948 New feature #19722: Unable to use ExpressionScript code when export by remote control
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done

#3966 Fixed issue #19750: Server-Side Request Forgery attack on SPSS export style settings
  application/libraries/admin/quexmlpdf.php
Labels: Tested OK, Code review done

#3969 Dev: Fixed issue #19744: showEmailInError missing documentation
  application/config/config-defaults.php
Labels: Needs code review

#3974 Fixed issue #19700: Invalid DB value can be entered with start URL
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done
