Repository LimeSurvey/LimeSurvey, pull requests merged in 2024-11, with the labels that each got.

#3983 Fixed issue #19779 : Question Type not translated
  application/models/Question.php
Labels: Tested OK, Code review done

#3990 Fixed issue #19760: When editing a response, delete current seed
  application/controllers/admin/DataEntry.php
Labels: Tested OK, Code review done

#3986 Fixed issue #19784: No access to the 'Edit Poll Settings' page view i… …n debug mode
  application/views/admin/expressions/test/surveyLogicForm.php
  application/views/admin/expressions/test/survey_logic_form.php
Labels: Tested OK, Code review done

#3999 Fixed issue #19805: Preview group throw PHP warning
  application/helpers/SurveyRuntimeHelper.php
Labels: Tested OK, Code review done

#4051 Fixed issue #19765: Unable to upload resources via drag'n'drop in KCFinder
  vendor/kcfinder/cache/base.js
  vendor/kcfinder/js/110.dropUpload.js
Labels: Tested OK, Code review done

#4050 Fixed issue #19751: Expression Manager Malfunction on Slider Answer Options
  application/views/survey/questions/answer/multiplenumeric/rows/sliders/horizontal_slider.twig
Labels: Tested OK, Code review done

#4049 Fixed issue #19718: Collapsible text not scrollable on iPhone
  themes/survey/fruity_twentythree/views/subviews/privacy/privacy_modal.twig
Labels: Tested OK, Code review done

#4043 Fixed issue #19694: [security] Update jQuery UI
  vendor/kcfinder/js/002._jqueryui.js
Labels: Tested OK

#4036 Fixed issue #19813: Duplicated Bootswatch Theme breaks File picker question
  application/models/TemplateConfig.php
  assets/packages/themeoptions-core/themeoptions-core.js
Labels: Needs testing, Code review done

#4052 Fixed issue #13732: Twig strip_tags function didn't work
  application/config/internal.php
Labels: Tested OK, Code review done

#4057 Fixed issue #19817: Can't create a new question after a between question is deleted
  application/models/QuestionCreate.php
  assets/scripts/admin/questionEditor.js
Labels: Tested OK, Code review done

#4064 Fixed issue #19820: Question Type Bootstrap Dropdown causes survey to jump to middle when starting
  themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/answer.twig
Labels: Tested OK, Code review done
