Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-07, with the labels that each got.

#4333 Fixed issue #20139: Export as QueXML with debug 2 and 8.3.22 : throw error
  application/helpers/export_helper.php
  application/libraries/admin/quexmlpdf.php
Labels: Tested OK, Code review done, Review effort 2/5

#4339 Fixed issue #20147: Unable to update from 3.X
  application/helpers/update/updates/Update_430.php
  application/models/Permission.php
  application/models/SurveysGroupsettings.php
  application/models/User.php
  application/models/UserInPermissionrole.php
Labels: Tested OK, Code review done, Review effort 3/5

#4353 LE-86: Initiate triggers after DB population
  application/helpers/update/triggers/TriggersManager.php
  installer/create-database.php
Labels: Review effort 3/5

#4355 LE-279: Ensured that datestamp is properly set
  application/models/services/SurveyActivate.php
Labels: Review effort 2/5

#4357 LE-280: Fixed timings id discrepancy
  application/helpers/admin/import_helper.php
Labels: Review effort 4/5, Possible security concern

#4312 QE-854 new create survey
  application/controllers/SurveyAdministrationController.php
  application/core/SurveyCommonAction.php
  application/extensions/admin/BoxesWidget/BoxesWidget.php
  application/extensions/admin/SearchBoxWidget/views/searchBox.php
  application/helpers/LayoutHelper.php
  application/libraries/MenuObjects/Menu.php
  application/libraries/MenuObjects/MenuItem.php
  application/libraries/MenuObjects/views/_extraMenu.php
  application/views/layouts/adminmenu.php
  assets/admin_themes/Sea_Green/navbar/navbar.scss
  tests/functional/backend/CreateSurveyTest.php
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Review effort 3/5

#4367 LE-289: prepare baseEmbed for extension
  application/libraries/Api/Command/V1/SurveyTemplate.php
  application/models/services/embeds/BaseEmbed.php
  application/models/services/embeds/StandardEmbed.php
Labels: Review effort 3/5

#4289 Fixed issue: fixed the width of buttons to create, import or copy survey
  application/views/surveyAdministration/tabCopy_view.php
  application/views/surveyAdministration/tabCreate_view.php
  application/views/surveyAdministration/tabImport_view.php
Labels: Review effort 1/5

#4374 Fixed issue #20180: Double escaping bug
  application/extensions/AdvancedSettingWidget/AdvancedSettingWidget.php
Labels: Needs testing, Tested OK, Code review done, Review effort 2/5, Possible security concern

#4377 AT-1708: changed back the default question type to "Long text"
  application/controllers/SurveyAdministrationController.php
Labels: Review effort 1/5

#4376 LE-285: ensure not dropping tokenTable on accessMode switch while pub…
  application/models/services/SurveyAccessModeService.php
Labels: Review effort 2/5

#4338 LE-257: Ensured that participants can be restored even if we have an empty participants table
  application/controllers/admin/Tokens.php
  application/models/Survey.php
  application/views/admin/token/surveyParticipantView.php
Labels: Review effort 3/5

#4373 LE-285: ensure tokensTable creation upon activation with allow regist…
  application/models/services/SurveyActivate.php
Labels: Review effort 2/5

#4372 LE-285: ensure tokensTable creation upon allowRegister toggle
  application/models/services/SurveyAggregateService/GeneralSettings.php
  tests/unit/services/SurveyAggregateService/GeneralSettings/GeneralSettingsFactory.php
  tests/unit/services/SurveyAggregateService/GeneralSettings/GeneralSettingsMockSet.php
  tests/unit/services/SurveyAggregateService/GeneralSettings/GeneralSettingsMockSetFactory.php
Labels: Review effort 3/5
