Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-10, with the labels that each got.

#4458 LE-429: Survey detail performance
  application/config/rest/v1/survey.php
  application/config/version.php
  application/helpers/update/updates/Update_637.php
  application/libraries/Api/Command/V1/SurveyDetail.php
  application/libraries/Api/Command/V1/SurveyPatch/PatcherSurvey.php
  application/models/Survey.php
  application/models/services/SurveyDetailService.php
  installer/create-database.php
Labels: Review effort 3/5, Possible security concern

#4451 Fixed issue #20274: When print survey with empty date question : curr…
  themes/survey/fruity_twentythree/views/subviews/printanswers/question_types/template_date.twig
  themes/survey/vanilla/views/subviews/printanswers/question_types/template_date.twig
Labels: Tested OK, Code review done, Review effort 1/5

#4457 Fixed issue #20260: Survey progress bar breaks on back button
  application/helpers/expressions/em_manager_helper.php
Labels: Tested OK, Code review done

#4468 LE-429: Refactor api response type and timestamp format
  application/libraries/Api/Command/V1/SurveyDetail.php
  application/libraries/Api/Command/V1/SurveyPatch/PatcherSurvey.php
  application/models/Survey.php
Labels: Review effort 2/5
