Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-08, with the labels that each got.

#4391 LE-307: adjust standard embed wrapper & fix duplicate wrappers
  application/libraries/Api/Command/V1/SurveyTemplate.php
  application/models/services/embeds/StandardEmbed.php
Labels: Review effort 2/5, Possible security concern

#4390 Fixed issue #20189: Javascript error after adding users from usergroup to survey
  assets/packages/usermanagement/js/usermanagement.js
Labels: Tested OK, Code review done, Review effort 1/5

#4385 Fixed issue #19597: Initially selected question group is not correct when adding a question directly after adding another question
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK, Code review done

#4384 Fixed issue #20185: Answer Options Not Deleted When Changing Question Type to Multiple Choice
  application/models/Question.php
Labels: Tested OK, Code review done

#4382 Fixed issue AT-1713 AT-1714: survey creation flow alert and redirect, default question type
  application/controllers/SurveyAdministrationController.php
  application/extensions/AlertWidget/AlertWidget.php
Labels: Review effort 3/5

#4331 Fixed issue #20133: Cannot use datepicker in batch editing of participants
  application/views/admin/token/massive_actions/_update.php
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code review done, Review effort 2/5

#4403 LE-292: embed button variant
  application/libraries/Api/Command/V1/SurveyTemplate.php
  application/models/services/embeds/BaseEmbed.php
  application/models/services/embeds/ButtonEmbed.php
  assets/styles-public/embed/buttonEmbed.css
Labels: Review effort 2/5, Possible security concern

#4404 LE-318: menu items
  application/libraries/Api/Command/V1/SurveyTemplate.php
  assets/scripts/survey-embed.js
  themes/survey/fruity_twentythree/views/subviews/navigation/save_links.twig
  themes/survey/vanilla/views/subviews/navigation/save_links.twig
Labels: Review effort 3/5, Possible security concern

#4414 LE-342: fix standard & popup embed styles
  application/models/services/embeds/StandardEmbed.php
  assets/styles-public/embed/popupEmbed.css
Labels: Review effort 2/5

#4420 Fixed issue #20242: Fixed the broken token mechanism
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/frontend_helper.php
Labels: Review effort 2/5

#4418 LE-345: Validate tokens in open-access mode
  application/libraries/Api/Command/V1/SurveyTemplate.php
  assets/scripts/survey-embed.js
Labels: Review effort 2/5

#4412 LE-344: Ensured that register is not supported at closed access mode
  application/controllers/survey/SurveyIndex.php
  application/helpers/SurveyRuntimeHelper.php
  application/helpers/frontend_helper.php
  application/libraries/Api/Command/V1/SurveyTemplate.php
  assets/scripts/survey-embed.js
  themes/survey/fruity_twentythree/views/subviews/navigation/save_links.twig
  themes/survey/vanilla/views/subviews/navigation/save_links.twig
Labels: Review effort 2/5

#4422 LE-345: add check to prevent API error when tokens table is missing
  application/libraries/Api/Command/V1/SurveyTemplate.php
Labels: Review effort 2/5

#4424 LE-360 Fixed conditional to check if survey response exists before getting token
  application/helpers/SurveyRuntimeHelper.php
Labels: Review effort 2/5
