Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-09, with the labels that each got.

#4306 LA-177: Survey responses endpoint
  application/config/rest/v1.php
  application/config/rest/v1/example/survey-responses-patch.json
  application/config/rest/v1/survey-responses.php
  application/extensions/admin/survey/SurveySidemenuWidget/SurveySidemenuWidget.php
  application/helpers/common_helper.php
  application/libraries/Api/Command/V1/SurveyResponses.php
  application/libraries/Api/Command/V1/SurveyResponses/FilterPatcher.php
  application/libraries/Api/Command/V1/SurveyResponses/HandlerInterface.php
  application/libraries/Api/Command/V1/SurveyResponses/PatcherSurveyResponses.php
  application/libraries/Api/Command/V1/SurveyResponses/SortingHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/ConditionHandlerHelperTrait.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/ContainConditionHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/DateRangeConditionHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/EqualConditionHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/MultiSelectConditionHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/NullConditionHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/conditions/RangeConditionHandler.php
  application/libraries/Api/Command/V1/SurveyResponses/patch/OpHandlerResponsesDelete.php
  application/libraries/Api/Command/V1/SurveyResponses/patch/OpHandlerResponsesFileDelete.php
  application/libraries/Api/Command/V1/SurveyResponses/patch/OpHandlerResponsesUpdate.php
  application/libraries/Api/Command/V1/SurveyResponsesPatch.php
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputSurveyResponses.php
  application/libraries/Api/Rest/V1/SchemaFactory/SchemaFactorySurveyResponses.php
  application/libraries/Api/Rest/V1/SchemaFactory/SchemaFactorySurveyResponsesPatch.php
  application/models/services/SurveyResponseService.php
  docs/open-api/v1.json
  tests/unit/api/opHandlers/OpHandlerResponseContainConditionTest.php
  tests/unit/api/opHandlers/OpHandlerResponseDateRangeConditionTest.php
  tests/unit/api/opHandlers/OpHandlerResponseEqualConditionTest.php
  tests/unit/api/opHandlers/OpHandlerResponseMultiSelectConditionTest.php
  tests/unit/api/opHandlers/OpHandlerResponseNullConditionTest.php
  tests/unit/api/opHandlers/OpHandlerResponseRangeConditionTest.php
  tests/unit/api/opHandlers/OpHandlerResponsesDeleteTest.php
  tests/unit/api/opHandlers/OpHandlerResponsesFileDeleteTest.php
  tests/unit/api/opHandlers/OpHandlerResponsesUpdateTest.php
Labels: Review effort 3/5

#4425 AT-1594: v1 editor tutorial
  application/config/rest/v1/user.php
  application/libraries/Api/Command/V1/UserSettingGetValue.php
  application/libraries/Api/Command/V1/UserSettingSetValue.php
  application/libraries/Api/Rest/V1/SchemaFactory/SchemaFactoryUserSetting.php
  application/models/SettingsUser.php
  docs/open-api/v1.json
Labels: Review effort 3/5, Possible security concern

#4427 Fixed issue #19812: fruity, bootswatch and vanilla truncate question index dropdown text
  themes/survey/vanilla/views/subviews/navigation/question_index_menu.twig
Labels: Tested OK, Code review done, Review effort 1/5

#4433 Fixed issue #AT-1745: storing answers from new editor
  application/libraries/Api/Command/V1/Transformer/Input/TransformerInputAnswer.php
  tests/unit/api/transformer/TransformerInputAnswerTest.php
  tests/unit/api/transformer/TransformerInputQuestionAggregateTest.php
Labels: Review effort 2/5

#4439 Fixed issue #20243: Attribute names disappear and automatic mapping breaks when adding CPDB participants to a survey
  application/models/Participant.php
Labels: Tested OK, Code review done, Review effort 2/5

#4365 AT-1679: Add user permission check endpoint
  application/config/rest/v1/permissions.php
  application/libraries/Api/Command/V1/Transformer/Output/TransformerOutputUserPermissions.php
  application/libraries/Api/Command/V1/UserPermission.php
  application/libraries/Api/Rest/V1/SchemaFactory/SchemaFactoryPermission.php
  application/libraries/Api/Rest/V1/SchemaFactory/SchemaFactoryUserPermission.php
Labels: Review effort 4/5, Possible security concern

#4431 Fixed issue #20256: Date question doesn't show AM/PM correctly
  application/extensions/DateTimePickerWidget/DateTimePicker.php
Labels: Tested OK, Code review done, Review effort 2/5

#4453 LE-428: Fixed the performance issue
  application/models/services/SurveyCondition.php
Labels: Tested OK, Code review done, Review effort 2/5
