Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-05, with the labels that each got.

#4261 Fixed issue #20085: Debug 2, PHP8.3 : unable to upload valid plugin
  application/helpers/common_helper.php
Labels: Needs code review, Needs testing, Review effort 1/5

#4259 Fixed issue #20064: Group order not set correctly when copying a question to a group such that subsequent copied questions end up in the wrong order
  application/controllers/QuestionAdministrationController.php
Labels: Tested OK, Code review done, Review effort 2/5

#4241 Fixed issue #20058: Can't retreive a file uploaded with RC api
  application/helpers/remotecontrol/remotecontrol_handle.php
Labels: Tested OK, Code review done

#4265 Fixed issue: If the database is using a different timezone than PHP the created/modified timestamps for certain records would differ
  application/models/LSActiveRecord.php
Labels: Review effort 2/5

#4255 Fixed issue #20063: Loading spinner prevents modal button press when adding an empty participant
  assets/packages/adminbasics/build/adminbasics.js
  assets/packages/adminbasics/build/adminbasics.min.js
  assets/packages/adminbasics/src/parts/save.js
  assets/scripts/admin/tokens.js
Labels: Tested OK, Code review done, Review effort 2/5

#4253 Fixed issue #20080: Disable plugins without way to alert administrator
  application/config/internal.php
  application/models/Plugin.php
Labels: Needs testing, Code review done, Review effort 1/5

#4271 Fixed issue QE-1572: 2 typeErrors reported on sentry
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerAnswer.php
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerQuestionAttributeUpdate.php
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerQuestionGroup.php
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerQuestionGroupL10n.php
  application/libraries/Api/Command/V1/SurveyPatch/OpHandlerSubQuestion.php
Labels: Review effort 2/5

#4218 Fixed issue #19986: List with comment with Dropdown presentation set to On doesn't offer placeholder value
  application/core/QuestionTypes/ListWithComment/RenderListComment.php
Labels: Tested OK, Code review done

#4267 APE-34: Adjusted the participants feature at the core
  application/controllers/admin/Tokens.php
  application/core/TopbarConfiguration.php
  application/models/services/SurveyActivate.php
  application/views/admin/token/surveyParticipantView.php
  application/views/surveyAdministration/partial/topbar_tokens/leftSideButtons.php
  application/views/surveyAdministration/partial/topbar_tokens/rightSideButtons.php
  tests/functional/backend/ImportResponsesTest.php
Labels: Review effort 3/5

#4266 QE-1547 activate icon link in box
  application/controllers/SurveyAdministrationController.php
  application/extensions/admin/BoxesWidget/views/box.php
  application/models/Survey.php
Labels: Review effort 2/5

#4158 MW-1460: Move question/subquestion/answer options code prefixes to global settings & survey settings
  application/config/config-defaults.php
  application/config/version.php
  application/controllers/SurveyAdministrationController.php
  application/controllers/admin/Database.php
  application/controllers/admin/SurveysGroupsController.php
  application/controllers/admin/UserAction.php
  application/controllers/admin/globalsettings.php
  application/core/LsDefaultDataSets.php
  application/datavalueobjects/SimpleSurveyValues.php
  application/helpers/update/updatedb_helper.php
  application/helpers/update/updates/Update_631.php
  application/libraries/Api/Rest/V1/SchemaFactory/SchemaFactoryUser.php
  application/models/Question.php
  application/models/QuestionCreate.php
  application/models/Survey.php
  application/models/SurveysGroupsettings.php
  application/models/services/SurveyAggregateService/GeneralSettings.php
  application/views/admin/survey/subview/accordion/_generaloptions_panel.php
  application/views/admin/user/personalsettings.php
  installer/create-database.php
  tests/TestBaseClassView.php
Labels: Needs testing, Code review done

#4264 Fixing Accessibility Issue on "Survey list" Screen
  themes/survey/fruity_twentythree/views/layout_survey_list.twig
  themes/survey/fruity_twentythree/views/subviews/header/nav_bar.twig
  themes/survey/fruity_twentythree/views/subviews/navigation/language_changer_top_menu.twig
Labels: Review effort 2/5

#4277 Fixed issue #20091: Eternal redirections
  application/controllers/OptinController.php
  application/controllers/OptoutController.php
Labels: Tested OK, Code review done

#4280 Fixed issue #20086: English text string makes no sense, can't be translated
  application/core/plugins/TwoFactorAdminLogin/helper/TFAYubikeyOtpHelper.php
Labels: Needs code review, Needs testing

#4276 Fixed issue #20090: Return 1st existing surey with specific link
  application/core/LSYii_Application.php
Labels: Tested OK, Code review done

#4270 Fixed issue #20087: Modal content not shown inside a modal but as a page itself with no style
  application/controllers/SurveyPermissionsController.php
  application/views/surveyPermissions/index.php
  assets/packages/usermanagement/js/usermanagement.js
  assets/scripts/admin/surveypermissions.js
Labels: Tested OK, Code review done, Review effort 2/5

#4278 APE-29: sideMenu widget redirect to react themeOptions
  application/extensions/admin/survey/SurveySidemenuWidget/SurveySidemenuWidget.php
  application/extensions/admin/survey/SurveySidemenuWidget/views/sidemenu.php
Labels: Review effort 2/5
