Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-01, with the labels that each got.

#4117 QE-1295: Redirecting to editor if it's switch on upon copy or import
  application/controllers/SurveyAdministrationController.php
Labels: Code review done

#4125 Fixed issue #19892: Activate survey modal is ignoring the global survey setting
  application/models/services/CreateSurvey.php
Labels: Tested OK, Code review done

#4114 Fixed issue #19848: Array questions split on iPad 7 despite its large screen (Vanilla theme)
  assets/packages/template-core/template-core.css
  themes/survey/bootswatch/css/theme.css
  themes/survey/fruity_twentythree/css/variations/theme_apple-rtl.css
  themes/survey/fruity_twentythree/css/variations/theme_apple.css
  themes/survey/fruity_twentythree/css/variations/theme_blueberry-rtl.css
  themes/survey/fruity_twentythree/css/variations/theme_blueberry.css
  themes/survey/fruity_twentythree/css/variations/theme_grape-rtl.css
  themes/survey/fruity_twentythree/css/variations/theme_grape.css
  themes/survey/fruity_twentythree/css/variations/theme_mango-rtl.css
  themes/survey/fruity_twentythree/css/variations/theme_mango.css
  themes/survey/vanilla/css/noTablesOnMobile.css
  themes/survey/vanilla/css/theme.css
Labels: Tested OK, Code review done

#4130 Fixed issue #19896: zend.assertions warning if debug set
  setdebug.php
Labels: Needs code review

#4120 Fixed issue [security][minor] #19905: Any user can get any user SurveyList
  application/helpers/remotecontrol/remotecontrol_handle.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#4138 Fixed issue #19924: Multiplication of #pjaxClickInhibitor DOM element when switching response view mode in LimeSurvey
  assets/scripts/admin/listresponse.js
Labels: Tested OK, Code review done

#4126 Fixed issue #19908: Import participants to survey: Can't import CSV without tokens
  application/models/Token.php
Labels: Tested OK, Code review done

#4149 Fixed issue #19939: Correction to the path pointing the images in log-in page
  assets/admin_themes/Sea_Green/authentication/authentication.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Tested OK, Code review done

#4137 Fixed issue #19927: postgres and unit tests
  tests/unit/LSYiiValidatorsTest.php
  tests/unit/helpers/GroupHelperTest.php
  tests/unit/helpers/remotecontrol/CPDImportParticpantsTest.php
Labels: Needs testing, Code review done

#4101 Fixed issue #19856: Import LDAP - error 500 - ldap_set_option
  application/controllers/admin/Tokens.php
Labels: Needs testing, Code review done

#4099 Dev #19825: Replace PclZip class with ZipArchive
  application/controllers/SurveyAdministrationController.php
  application/controllers/UserRoleController.php
  application/controllers/admin/Export.php
  application/controllers/admin/Labels.php
  application/controllers/admin/PluginManagerController.php
  application/controllers/admin/Themes.php
  application/controllers/admin/Update.php
  application/helpers/ZipHelper.php
  application/helpers/admin/import_helper.php
  application/helpers/admin/template_helper.php
  application/helpers/common_helper.php
  application/libraries/ExtensionInstaller/FileFetcherUploadZip.php
  application/libraries/Zip.php
  application/libraries/admin/pclzip.php
  application/models/UpdateForm.php
  application/models/services/ZipExtractor.php
  tests/phpstan/phpstan_bootstrap.php
  vendor/pclzip/pclzip.lib.php
  vendor/pclzip/todo.txt
Labels: Tested OK, Code review done

#3970 Dev: #19496: plugins in plugin directory shown in git diff
  .gitignore
Labels: Needs code review
