Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-03, with the labels that each got.

#4170 Fixed issue #19960: Registration Form spamming
  application/config/config-defaults.php
  application/controllers/RegisterController.php
Labels: Tested OK, Code review done

#4192 Fixed issue #19965: Lot of security issue in jspdf
  application/config/vendor.php
  assets/scripts/admin/createpdf_worker.js
  node_modules/jspdf/LICENSE
  node_modules/jspdf/README.md
  node_modules/jspdf/dist/jspdf.debug.js
  node_modules/jspdf/dist/jspdf.es.js
  node_modules/jspdf/dist/jspdf.es.min.js
  node_modules/jspdf/dist/jspdf.min.js
  node_modules/jspdf/dist/jspdf.node.debug.js
  node_modules/jspdf/dist/jspdf.node.js
  node_modules/jspdf/dist/jspdf.node.min.js
  node_modules/jspdf/dist/jspdf.umd.js
  node_modules/jspdf/dist/jspdf.umd.min.js
  node_modules/jspdf/dist/polyfills.es.js
  node_modules/jspdf/dist/polyfills.umd.js
  node_modules/jspdf/package.json
  node_modules/jspdf/types/index.d.ts
  package.json
Labels: Tested OK, Code review done

#4189 Fixed issue #19992: Errors after importing surveys related to quota l…
  application/helpers/admin/import_helper.php
  application/models/QuotaLanguageSetting.php
Labels: Tested OK, Code review done

#4190 Fixed issue #19994: Unable to get to dashboard in some condition
  application/core/LSETwigViewRenderer.php
Labels: Needs testing, Code review done

#4182 Fixed issue #19904: Last survey and last question must be in SettingsUser
  application/commands/DemomodeCommand.php
  application/commands/WipeCommand.php
  application/config/version.php
  application/controllers/DashboardController.php
  application/controllers/QuestionAdministrationController.php
  application/controllers/SurveyAdministrationController.php
  application/helpers/update/updates/Update_628.php
  application/models/Question.php
  application/models/Survey.php
Labels: Tested OK, Code review done

#4181 Fixed issue #19947: Exporting to tab-separated-values error
  application/helpers/export_helper.php
Labels: Tested OK, Code review done

#4195 Fixed issue #19773: Translation function added to Reordering title
  application/views/admin/survey/organizeGroupsAndQuestions_view.php
Labels: Tested OK, Code review done

#4196 Fixed issue #20004: User massive action drop-down list not translated
  application/views/userManagement/massiveAction/_updatestatus.php
Labels: Tested OK, Code review done

#4202 New feature #20002: Create 2FA enforcement setting for 2FA plugin
  application/core/plugins/TwoFactorAdminLogin/TwoFactorAdminLogin.php
  application/core/plugins/TwoFactorAdminLogin/config.xml
  application/core/plugins/TwoFactorAdminLogin/views/userindex.php
Labels: Tested OK, Code review done

#4210 Fixed issue #19966: Npm show a lot of security issue
  gulpfile.js
  package.json
Labels: Needs testing, Code review done

#4215 Fixed issue #20022: Encryption of the Client Secret - AzureOAuthSMTP Plugin
  application/core/plugins/AzureOAuthSMTP/AzureOAuthSMTP.php
Labels: Needs testing, Code review done

#4016 Fixed issue #19552: Breadcrumb is badly placed, cut off, and doesn't show survey name, group name etc
  application/config/config-defaults.php
  application/controllers/admin/UserAction.php
  application/controllers/admin/globalsettings.php
  application/core/LsDefaultDataSets.php
  application/extensions/BreadcrumbWidget/BreadcrumbWidget.php
  application/extensions/BreadcrumbWidget/views/breadcrumb.php
  application/extensions/LimeTopbarWidget/views/topbar.php
  application/views/admin/globalsettings/_general.php
  application/views/admin/user/personalsettings.php
  application/views/layouts/title_bar.php
  application/views/questionAdministration/partial/topbarBtns/questionTopbar_view.php
  assets/admin_themes/Sea_Green/breadcrumb/breadcrumb.scss
  themes/admin/Sea_Green/css/sea_green-rtl.css
  themes/admin/Sea_Green/css/sea_green-rtl.min.css
  themes/admin/Sea_Green/css/sea_green.css
  themes/admin/Sea_Green/css/sea_green.min.css
Labels: Needs code review, Needs testing

#4211 Fixed issue #19956: Ugly error message after trying to import not compatible responses
  application/controllers/admin/DataEntry.php
  application/views/admin/dataentry/import_result.php
Labels: Tested OK, Code review done

#4199 Fixed Issue #19743 : Copy survey button was too small
  application/views/surveyAdministration/tabCopy_view.php
Labels: Tested OK, Code review done

#4205 Fixed issue #20008: XSS on survey theme description
  application/models/TemplateManifest.php
Labels: Needs code review, Tested OK
