Repository LimeSurvey/LimeSurvey, pull requests merged in 2025-06, with the labels that each got.

#4298 Fixed issue #20107: Statistics PDF export with Pie Charts not working
  application/views/admin/export/statistics_subviews/_outputoptions.php
  assets/scripts/admin/statistics.js
Labels: Tested OK, Code review done

#4310 Fixed issue #20132: With debug=2 I am getting an error when exporting responses to SPSS
  application/helpers/export_helper.php
Labels: Tested OK, Code review done, Review effort 1/5

#4313 Fixed issue #20047: Unable to open survey on new tab in Survey listing
  application/models/Survey.php
Labels: Tested OK, Code review done, Review effort 2/5

#4301 Fixed issue #20034: Exceeding the number of maximum access code validation attempts
  application/config/config-defaults.php
  application/helpers/common_helper.php
Labels: Tested OK, Code review done

#4320 LE-253: Ensured that the new setting is displayed when appropriate
  application/helpers/SurveyRuntimeHelper.php
Labels: Review effort 2/5

#4324 LE-250: Implemented support for all
  application/libraries/Api/Command/V1/SurveyArchive.php
Labels: Review effort 3/5

#4321 LE-252: backend unit test
  application/helpers/admin/import_helper.php
  application/models/services/SurveyAccessModeService.php
  tests/data/surveys/access_modes_368399.lsa
  tests/data/surveys/access_modes_553745.lsa
  tests/data/surveys/access_modes_797496.lsa
  tests/data/surveys/access_modes_976917.lsa
  tests/functional/backend/AccessModeChangeTest.php
Labels: Review effort 3/5, Possible security concern

#4319 Fixed issue #20070: Enabling custom twig extension goes to 500 if HelloWorld extension is present
  upload/twig/extensions/HelloWorld_Twig_Extension/HelloWorld_Twig_Extension.php
Labels: Tested OK, Code review done, Review effort 2/5

#4327 Dev AT-1608 always open simple statistics first
  application/config/version.php
  application/core/LsDefaultDataSets.php
  application/helpers/update/updates/Update_633.php
Labels: Review effort 2/5

#4315 Fixed issue #20083: Pre-Installation check: Session writable re-check is impossible - Attempt II
  application/controllers/InstallerController.php
  application/views/installer/dbconfig_view.php
  application/views/installer/precheck_view.php
Labels: Tested OK, Code review done, Review effort 2/5

#4309 Fixed issue #20098: Sensitive information exposed to public in session errors
  application/controllers/SurveysController.php
Labels: Needs testing, Review effort 1/5

#4329 Fixed issue #20144: [Security] Unsafe unserialize lead to remote code…
  application/config/config-defaults.php
  application/helpers/common_helper.php
Labels: Tested OK, Review effort 3/5

#4340 Fixed issue #20055: Missing save confirmation with validation errors
  application/helpers/SurveyRuntimeHelper.php
Labels: Review effort 2/5
